// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package v1

import (
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Health defines model for Health.
type Health struct {
	StartedAt time.Time `json:"startedAt"`
	Status    string    `json:"status"`
	Version   string    `json:"version"`
}

// Status defines model for Status.
type Status struct {
	Agents      map[string]interface{} `json:"agents"`
	Config      map[string]interface{} `json:"config"`
	EventStream map[string]interface{} `json:"eventStream"`
	Mcp         map[string]interface{} `json:"mcp"`
	Setup       map[string]interface{} `json:"setup"`
	StartedAt   time.Time              `json:"startedAt"`
	Status      string                 `json:"status"`
	Version     string                 `json:"version"`
	Voice       map[string]interface{} `json:"voice"`
}

// PostAgentConversationJSONBody defines parameters for PostAgentConversation.
type PostAgentConversationJSONBody map[string]interface{}

// PostBackgroundMultipartBody defines parameters for PostBackground.
type PostBackgroundMultipartBody struct {
	File *openapi_types.File `json:"file,omitempty"`
}

// PostConnectionJSONBody defines parameters for PostConnection.
type PostConnectionJSONBody map[string]interface{}

// PatchHouseholdSettingsJSONBody defines parameters for PatchHouseholdSettings.
type PatchHouseholdSettingsJSONBody map[string]interface{}

// PutRoomsJSONBody defines parameters for PutRooms.
type PutRoomsJSONBody = []map[string]interface{}

// PutTilesJSONBody defines parameters for PutTiles.
type PutTilesJSONBody = []map[string]interface{}

// PostTTSSpeakJSONBody defines parameters for PostTTSSpeak.
type PostTTSSpeakJSONBody map[string]interface{}

// PostTTSStopJSONBody defines parameters for PostTTSStop.
type PostTTSStopJSONBody map[string]interface{}

// GetTTSVoicesParams defines parameters for GetTTSVoices.
type GetTTSVoicesParams struct {
	ProviderId      *string `form:"providerId,omitempty" json:"providerId,omitempty"`
	DeviceProfileId *string `form:"deviceProfileId,omitempty" json:"deviceProfileId,omitempty"`
}

// PostVoiceAudioParams defines parameters for PostVoiceAudio.
type PostVoiceAudioParams struct {
	Wake                 *bool   `form:"wake,omitempty" json:"wake,omitempty"`
	XJuteSampleRate      *int    `json:"X-Jute-Sample-Rate,omitempty"`
	XJuteChannels        *int    `json:"X-Jute-Channels,omitempty"`
	XJuteDeviceProfileId *string `json:"X-Jute-Device-Profile-Id,omitempty"`
	XJuteDeviceId        *string `json:"X-Jute-Device-Id,omitempty"`
	XJuteConversationId  *string `json:"X-Jute-Conversation-Id,omitempty"`
	XJuteAgentId         *string `json:"X-Jute-Agent-Id,omitempty"`
}

// PatchVoiceSettingsJSONBody defines parameters for PatchVoiceSettings.
type PatchVoiceSettingsJSONBody map[string]interface{}

// PostVoiceFinalTranscriptJSONBody defines parameters for PostVoiceFinalTranscript.
type PostVoiceFinalTranscriptJSONBody struct {
	AgentId         *string `json:"agentId,omitempty"`
	ConversationId  *string `json:"conversationId,omitempty"`
	DeviceId        *string `json:"deviceId,omitempty"`
	DeviceProfileId *string `json:"deviceProfileId,omitempty"`
	Text            string  `json:"text"`
}

// GetWidgetLayoutParams defines parameters for GetWidgetLayout.
type GetWidgetLayoutParams struct {
	ProfileId *string `form:"profileId,omitempty" json:"profileId,omitempty"`
}

// PutWidgetLayoutJSONBody defines parameters for PutWidgetLayout.
type PutWidgetLayoutJSONBody map[string]interface{}

// PatchWidgetLayoutActiveScreenJSONBody defines parameters for PatchWidgetLayoutActiveScreen.
type PatchWidgetLayoutActiveScreenJSONBody struct {
	ScreenId string `json:"screenId"`
}

// PostWidgetLayoutResetParams defines parameters for PostWidgetLayoutReset.
type PostWidgetLayoutResetParams struct {
	ProfileId *string `form:"profileId,omitempty" json:"profileId,omitempty"`
}

// PostAgentConversationJSONRequestBody defines body for PostAgentConversation for application/json ContentType.
type PostAgentConversationJSONRequestBody PostAgentConversationJSONBody

// PostBackgroundMultipartRequestBody defines body for PostBackground for multipart/form-data ContentType.
type PostBackgroundMultipartRequestBody PostBackgroundMultipartBody

// PostConnectionJSONRequestBody defines body for PostConnection for application/json ContentType.
type PostConnectionJSONRequestBody PostConnectionJSONBody

// PatchHouseholdSettingsJSONRequestBody defines body for PatchHouseholdSettings for application/json ContentType.
type PatchHouseholdSettingsJSONRequestBody PatchHouseholdSettingsJSONBody

// PutRoomsJSONRequestBody defines body for PutRooms for application/json ContentType.
type PutRoomsJSONRequestBody = PutRoomsJSONBody

// PutTilesJSONRequestBody defines body for PutTiles for application/json ContentType.
type PutTilesJSONRequestBody = PutTilesJSONBody

// PostTTSSpeakJSONRequestBody defines body for PostTTSSpeak for application/json ContentType.
type PostTTSSpeakJSONRequestBody PostTTSSpeakJSONBody

// PostTTSStopJSONRequestBody defines body for PostTTSStop for application/json ContentType.
type PostTTSStopJSONRequestBody PostTTSStopJSONBody

// PatchVoiceSettingsJSONRequestBody defines body for PatchVoiceSettings for application/json ContentType.
type PatchVoiceSettingsJSONRequestBody PatchVoiceSettingsJSONBody

// PostVoiceFinalTranscriptJSONRequestBody defines body for PostVoiceFinalTranscript for application/json ContentType.
type PostVoiceFinalTranscriptJSONRequestBody PostVoiceFinalTranscriptJSONBody

// PutWidgetLayoutJSONRequestBody defines body for PutWidgetLayout for application/json ContentType.
type PutWidgetLayoutJSONRequestBody PutWidgetLayoutJSONBody

// PatchWidgetLayoutActiveScreenJSONRequestBody defines body for PatchWidgetLayoutActiveScreen for application/json ContentType.
type PatchWidgetLayoutActiveScreenJSONRequestBody PatchWidgetLayoutActiveScreenJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/v1/agents)
	GetAgents(ctx echo.Context) error

	// (POST /api/v1/agents)
	PostAgentConversation(ctx echo.Context) error

	// (GET /api/v1/backgrounds)
	GetBackgrounds(ctx echo.Context) error

	// (POST /api/v1/backgrounds)
	PostBackground(ctx echo.Context) error

	// (GET /api/v1/config)
	GetConfig(ctx echo.Context) error

	// (GET /api/v1/events)
	GetEvents(ctx echo.Context) error

	// (GET /api/v1/home)
	GetHome(ctx echo.Context) error

	// (GET /api/v1/settings/connection-kinds)
	GetConnectionKinds(ctx echo.Context) error

	// (GET /api/v1/settings/connections)
	GetConnections(ctx echo.Context) error

	// (POST /api/v1/settings/connections)
	PostConnection(ctx echo.Context) error

	// (GET /api/v1/settings/household)
	GetHouseholdSettings(ctx echo.Context) error

	// (PATCH /api/v1/settings/household)
	PatchHouseholdSettings(ctx echo.Context) error

	// (GET /api/v1/settings/rooms)
	GetRooms(ctx echo.Context) error

	// (PUT /api/v1/settings/rooms)
	PutRooms(ctx echo.Context) error

	// (GET /api/v1/settings/tiles)
	GetTiles(ctx echo.Context) error

	// (PUT /api/v1/settings/tiles)
	PutTiles(ctx echo.Context) error

	// (GET /api/v1/setup/status)
	GetSetupStatus(ctx echo.Context) error

	// (GET /api/v1/status)
	GetStatus(ctx echo.Context) error

	// (GET /api/v1/tts/audio/{id})
	GetTTSAudio(ctx echo.Context, id string) error

	// (POST /api/v1/tts/speak)
	PostTTSSpeak(ctx echo.Context) error

	// (POST /api/v1/tts/stop)
	PostTTSStop(ctx echo.Context) error

	// (GET /api/v1/tts/voices)
	GetTTSVoices(ctx echo.Context, params GetTTSVoicesParams) error

	// (POST /api/v1/voice/audio)
	PostVoiceAudio(ctx echo.Context, params PostVoiceAudioParams) error

	// (POST /api/v1/voice/cancel)
	PostVoiceCancel(ctx echo.Context) error

	// (POST /api/v1/voice/mute)
	PostVoiceMute(ctx echo.Context) error

	// (GET /api/v1/voice/providers)
	GetVoiceProviders(ctx echo.Context) error

	// (PATCH /api/v1/voice/settings)
	PatchVoiceSettings(ctx echo.Context) error

	// (GET /api/v1/voice/status)
	GetVoiceStatus(ctx echo.Context) error

	// (POST /api/v1/voice/transcripts/final)
	PostVoiceFinalTranscript(ctx echo.Context) error

	// (POST /api/v1/voice/unmute)
	PostVoiceUnmute(ctx echo.Context) error

	// (GET /api/v1/widgets/catalog)
	GetWidgetCatalog(ctx echo.Context) error

	// (GET /api/v1/widgets/layout)
	GetWidgetLayout(ctx echo.Context, params GetWidgetLayoutParams) error

	// (PUT /api/v1/widgets/layout)
	PutWidgetLayout(ctx echo.Context) error

	// (PATCH /api/v1/widgets/layout/active-screen)
	PatchWidgetLayoutActiveScreen(ctx echo.Context) error

	// (POST /api/v1/widgets/layout/reset)
	PostWidgetLayoutReset(ctx echo.Context, params PostWidgetLayoutResetParams) error

	// (GET /healthz)
	GetHealth(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetAgents converts echo context to params.
func (w *ServerInterfaceWrapper) GetAgents(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetAgents(ctx)
	return err
}

// PostAgentConversation converts echo context to params.
func (w *ServerInterfaceWrapper) PostAgentConversation(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostAgentConversation(ctx)
	return err
}

// GetBackgrounds converts echo context to params.
func (w *ServerInterfaceWrapper) GetBackgrounds(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetBackgrounds(ctx)
	return err
}

// PostBackground converts echo context to params.
func (w *ServerInterfaceWrapper) PostBackground(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostBackground(ctx)
	return err
}

// GetConfig converts echo context to params.
func (w *ServerInterfaceWrapper) GetConfig(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetConfig(ctx)
	return err
}

// GetEvents converts echo context to params.
func (w *ServerInterfaceWrapper) GetEvents(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetEvents(ctx)
	return err
}

// GetHome converts echo context to params.
func (w *ServerInterfaceWrapper) GetHome(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHome(ctx)
	return err
}

// GetConnectionKinds converts echo context to params.
func (w *ServerInterfaceWrapper) GetConnectionKinds(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetConnectionKinds(ctx)
	return err
}

// GetConnections converts echo context to params.
func (w *ServerInterfaceWrapper) GetConnections(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetConnections(ctx)
	return err
}

// PostConnection converts echo context to params.
func (w *ServerInterfaceWrapper) PostConnection(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostConnection(ctx)
	return err
}

// GetHouseholdSettings converts echo context to params.
func (w *ServerInterfaceWrapper) GetHouseholdSettings(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHouseholdSettings(ctx)
	return err
}

// PatchHouseholdSettings converts echo context to params.
func (w *ServerInterfaceWrapper) PatchHouseholdSettings(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchHouseholdSettings(ctx)
	return err
}

// GetRooms converts echo context to params.
func (w *ServerInterfaceWrapper) GetRooms(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetRooms(ctx)
	return err
}

// PutRooms converts echo context to params.
func (w *ServerInterfaceWrapper) PutRooms(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutRooms(ctx)
	return err
}

// GetTiles converts echo context to params.
func (w *ServerInterfaceWrapper) GetTiles(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTiles(ctx)
	return err
}

// PutTiles converts echo context to params.
func (w *ServerInterfaceWrapper) PutTiles(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutTiles(ctx)
	return err
}

// GetSetupStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetSetupStatus(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSetupStatus(ctx)
	return err
}

// GetStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetStatus(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetStatus(ctx)
	return err
}

// GetTTSAudio converts echo context to params.
func (w *ServerInterfaceWrapper) GetTTSAudio(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTTSAudio(ctx, id)
	return err
}

// PostTTSSpeak converts echo context to params.
func (w *ServerInterfaceWrapper) PostTTSSpeak(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTTSSpeak(ctx)
	return err
}

// PostTTSStop converts echo context to params.
func (w *ServerInterfaceWrapper) PostTTSStop(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostTTSStop(ctx)
	return err
}

// GetTTSVoices converts echo context to params.
func (w *ServerInterfaceWrapper) GetTTSVoices(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTTSVoicesParams
	// ------------- Optional query parameter "providerId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "providerId", ctx.QueryParams(), &params.ProviderId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter providerId: %s", err))
	}

	// ------------- Optional query parameter "deviceProfileId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "deviceProfileId", ctx.QueryParams(), &params.DeviceProfileId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter deviceProfileId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetTTSVoices(ctx, params)
	return err
}

// PostVoiceAudio converts echo context to params.
func (w *ServerInterfaceWrapper) PostVoiceAudio(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostVoiceAudioParams
	// ------------- Optional query parameter "wake" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "wake", ctx.QueryParams(), &params.Wake, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter wake: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Optional header parameter "X-Jute-Sample-Rate" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Jute-Sample-Rate")]; found {
		var XJuteSampleRate int
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Jute-Sample-Rate, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Jute-Sample-Rate", valueList[0], &XJuteSampleRate, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Jute-Sample-Rate: %s", err))
		}

		params.XJuteSampleRate = &XJuteSampleRate
	}
	// ------------- Optional header parameter "X-Jute-Channels" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Jute-Channels")]; found {
		var XJuteChannels int
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Jute-Channels, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Jute-Channels", valueList[0], &XJuteChannels, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Jute-Channels: %s", err))
		}

		params.XJuteChannels = &XJuteChannels
	}
	// ------------- Optional header parameter "X-Jute-Device-Profile-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Jute-Device-Profile-Id")]; found {
		var XJuteDeviceProfileId string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Jute-Device-Profile-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Jute-Device-Profile-Id", valueList[0], &XJuteDeviceProfileId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Jute-Device-Profile-Id: %s", err))
		}

		params.XJuteDeviceProfileId = &XJuteDeviceProfileId
	}
	// ------------- Optional header parameter "X-Jute-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Jute-Device-Id")]; found {
		var XJuteDeviceId string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Jute-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Jute-Device-Id", valueList[0], &XJuteDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Jute-Device-Id: %s", err))
		}

		params.XJuteDeviceId = &XJuteDeviceId
	}
	// ------------- Optional header parameter "X-Jute-Conversation-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Jute-Conversation-Id")]; found {
		var XJuteConversationId string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Jute-Conversation-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Jute-Conversation-Id", valueList[0], &XJuteConversationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Jute-Conversation-Id: %s", err))
		}

		params.XJuteConversationId = &XJuteConversationId
	}
	// ------------- Optional header parameter "X-Jute-Agent-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Jute-Agent-Id")]; found {
		var XJuteAgentId string
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Jute-Agent-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Jute-Agent-Id", valueList[0], &XJuteAgentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Jute-Agent-Id: %s", err))
		}

		params.XJuteAgentId = &XJuteAgentId
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostVoiceAudio(ctx, params)
	return err
}

// PostVoiceCancel converts echo context to params.
func (w *ServerInterfaceWrapper) PostVoiceCancel(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostVoiceCancel(ctx)
	return err
}

// PostVoiceMute converts echo context to params.
func (w *ServerInterfaceWrapper) PostVoiceMute(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostVoiceMute(ctx)
	return err
}

// GetVoiceProviders converts echo context to params.
func (w *ServerInterfaceWrapper) GetVoiceProviders(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVoiceProviders(ctx)
	return err
}

// PatchVoiceSettings converts echo context to params.
func (w *ServerInterfaceWrapper) PatchVoiceSettings(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchVoiceSettings(ctx)
	return err
}

// GetVoiceStatus converts echo context to params.
func (w *ServerInterfaceWrapper) GetVoiceStatus(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetVoiceStatus(ctx)
	return err
}

// PostVoiceFinalTranscript converts echo context to params.
func (w *ServerInterfaceWrapper) PostVoiceFinalTranscript(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostVoiceFinalTranscript(ctx)
	return err
}

// PostVoiceUnmute converts echo context to params.
func (w *ServerInterfaceWrapper) PostVoiceUnmute(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostVoiceUnmute(ctx)
	return err
}

// GetWidgetCatalog converts echo context to params.
func (w *ServerInterfaceWrapper) GetWidgetCatalog(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWidgetCatalog(ctx)
	return err
}

// GetWidgetLayout converts echo context to params.
func (w *ServerInterfaceWrapper) GetWidgetLayout(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWidgetLayoutParams
	// ------------- Optional query parameter "profileId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "profileId", ctx.QueryParams(), &params.ProfileId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter profileId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetWidgetLayout(ctx, params)
	return err
}

// PutWidgetLayout converts echo context to params.
func (w *ServerInterfaceWrapper) PutWidgetLayout(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PutWidgetLayout(ctx)
	return err
}

// PatchWidgetLayoutActiveScreen converts echo context to params.
func (w *ServerInterfaceWrapper) PatchWidgetLayoutActiveScreen(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PatchWidgetLayoutActiveScreen(ctx)
	return err
}

// PostWidgetLayoutReset converts echo context to params.
func (w *ServerInterfaceWrapper) PostWidgetLayoutReset(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostWidgetLayoutResetParams
	// ------------- Optional query parameter "profileId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "profileId", ctx.QueryParams(), &params.ProfileId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter profileId: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostWidgetLayoutReset(ctx, params)
	return err
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/api/v1/agents", wrapper.GetAgents, options.OperationMiddlewares["getAgents"]...)
	router.POST(options.BaseURL+"/api/v1/agents", wrapper.PostAgentConversation, options.OperationMiddlewares["postAgentConversation"]...)
	router.GET(options.BaseURL+"/api/v1/backgrounds", wrapper.GetBackgrounds, options.OperationMiddlewares["getBackgrounds"]...)
	router.POST(options.BaseURL+"/api/v1/backgrounds", wrapper.PostBackground, options.OperationMiddlewares["postBackground"]...)
	router.GET(options.BaseURL+"/api/v1/config", wrapper.GetConfig, options.OperationMiddlewares["getConfig"]...)
	router.GET(options.BaseURL+"/api/v1/events", wrapper.GetEvents, options.OperationMiddlewares["getEvents"]...)
	router.GET(options.BaseURL+"/api/v1/home", wrapper.GetHome, options.OperationMiddlewares["getHome"]...)
	router.GET(options.BaseURL+"/api/v1/settings/connection-kinds", wrapper.GetConnectionKinds, options.OperationMiddlewares["getConnectionKinds"]...)
	router.GET(options.BaseURL+"/api/v1/settings/connections", wrapper.GetConnections, options.OperationMiddlewares["getConnections"]...)
	router.POST(options.BaseURL+"/api/v1/settings/connections", wrapper.PostConnection, options.OperationMiddlewares["postConnection"]...)
	router.GET(options.BaseURL+"/api/v1/settings/household", wrapper.GetHouseholdSettings, options.OperationMiddlewares["getHouseholdSettings"]...)
	router.PATCH(options.BaseURL+"/api/v1/settings/household", wrapper.PatchHouseholdSettings, options.OperationMiddlewares["patchHouseholdSettings"]...)
	router.GET(options.BaseURL+"/api/v1/settings/rooms", wrapper.GetRooms, options.OperationMiddlewares["getRooms"]...)
	router.PUT(options.BaseURL+"/api/v1/settings/rooms", wrapper.PutRooms, options.OperationMiddlewares["putRooms"]...)
	router.GET(options.BaseURL+"/api/v1/settings/tiles", wrapper.GetTiles, options.OperationMiddlewares["getTiles"]...)
	router.PUT(options.BaseURL+"/api/v1/settings/tiles", wrapper.PutTiles, options.OperationMiddlewares["putTiles"]...)
	router.GET(options.BaseURL+"/api/v1/setup/status", wrapper.GetSetupStatus, options.OperationMiddlewares["getSetupStatus"]...)
	router.GET(options.BaseURL+"/api/v1/status", wrapper.GetStatus, options.OperationMiddlewares["getStatus"]...)
	router.GET(options.BaseURL+"/api/v1/tts/audio/:id", wrapper.GetTTSAudio, options.OperationMiddlewares["getTTSAudio"]...)
	router.POST(options.BaseURL+"/api/v1/tts/speak", wrapper.PostTTSSpeak, options.OperationMiddlewares["postTTSSpeak"]...)
	router.POST(options.BaseURL+"/api/v1/tts/stop", wrapper.PostTTSStop, options.OperationMiddlewares["postTTSStop"]...)
	router.GET(options.BaseURL+"/api/v1/tts/voices", wrapper.GetTTSVoices, options.OperationMiddlewares["getTTSVoices"]...)
	router.POST(options.BaseURL+"/api/v1/voice/audio", wrapper.PostVoiceAudio, options.OperationMiddlewares["postVoiceAudio"]...)
	router.POST(options.BaseURL+"/api/v1/voice/cancel", wrapper.PostVoiceCancel, options.OperationMiddlewares["postVoiceCancel"]...)
	router.POST(options.BaseURL+"/api/v1/voice/mute", wrapper.PostVoiceMute, options.OperationMiddlewares["postVoiceMute"]...)
	router.GET(options.BaseURL+"/api/v1/voice/providers", wrapper.GetVoiceProviders, options.OperationMiddlewares["getVoiceProviders"]...)
	router.PATCH(options.BaseURL+"/api/v1/voice/settings", wrapper.PatchVoiceSettings, options.OperationMiddlewares["patchVoiceSettings"]...)
	router.GET(options.BaseURL+"/api/v1/voice/status", wrapper.GetVoiceStatus, options.OperationMiddlewares["getVoiceStatus"]...)
	router.POST(options.BaseURL+"/api/v1/voice/transcripts/final", wrapper.PostVoiceFinalTranscript, options.OperationMiddlewares["postVoiceFinalTranscript"]...)
	router.POST(options.BaseURL+"/api/v1/voice/unmute", wrapper.PostVoiceUnmute, options.OperationMiddlewares["postVoiceUnmute"]...)
	router.GET(options.BaseURL+"/api/v1/widgets/catalog", wrapper.GetWidgetCatalog, options.OperationMiddlewares["getWidgetCatalog"]...)
	router.GET(options.BaseURL+"/api/v1/widgets/layout", wrapper.GetWidgetLayout, options.OperationMiddlewares["getWidgetLayout"]...)
	router.PUT(options.BaseURL+"/api/v1/widgets/layout", wrapper.PutWidgetLayout, options.OperationMiddlewares["putWidgetLayout"]...)
	router.PATCH(options.BaseURL+"/api/v1/widgets/layout/active-screen", wrapper.PatchWidgetLayoutActiveScreen, options.OperationMiddlewares["patchWidgetLayoutActiveScreen"]...)
	router.POST(options.BaseURL+"/api/v1/widgets/layout/reset", wrapper.PostWidgetLayoutReset, options.OperationMiddlewares["postWidgetLayoutReset"]...)
	router.GET(options.BaseURL+"/healthz", wrapper.GetHealth, options.OperationMiddlewares["getHealth"]...)

}
