package applemusic

import (
	"context"
	"fmt"
	"log/slog"
	"strings"
	"sync"
	"time"

	"jute-dash/apps/hub/pkg/widgetskills"
	"jute-dash/widgets"
	"jute-dash/widgets/applemusic/hub/internal/provider"
)

const (
	Kind    = "apple-music"
	SkillID = "jute.applemusic.control"
)

type SecretString string

func (s SecretString) LogValue() slog.Value {
	if s == "" {
		return slog.StringValue("")
	}
	return slog.StringValue("[redacted]")
}

type Settings struct {
	DeveloperToken SecretString
	UserToken      SecretString
}

func (s Settings) LogValue() slog.Value {
	return slog.GroupValue(
		slog.Any("developer_token", s.DeveloperToken),
		slog.Any("user_token", s.UserToken),
	)
}

type AppleMusicWidget struct{}

var appleMusicSuggestions = newAppleMusicSuggestionCache()

func NewWidget() *AppleMusicWidget {
	return &AppleMusicWidget{}
}

func (w *AppleMusicWidget) Kind() string {
	return Kind
}

func (w *AppleMusicWidget) CatalogInfo() widgets.WidgetCatalogItem {
	return widgets.WidgetCatalogItem{
		Kind:                   Kind,
		Name:                   "Apple Music",
		Description:            "Control playback and view track info from Apple Music.",
		DefaultTitle:           "Apple Music",
		DefaultW:               6,
		DefaultH:               2,
		MinW:                   4,
		MinH:                   2,
		DefaultSize:            "wide",
		Overflow:               "clip",
		AllowMultiple:          false,
		ConnectionRequirements: w.RequiredConnections(),
	}
}

func (w *AppleMusicWidget) RequiredConnections() []widgets.ConnectionRequirement {
	return []widgets.ConnectionRequirement{{
		Slot:        "account",
		Kind:        "apple-music",
		DisplayName: "Apple Music Account",
		Description: "Apple Music developer and user token references.",
		Required:    true,
		SecretKeys:  []string{"developer_token"},
		Fields: []widgets.ConnectionField{
			{
				ID:       "developer_token",
				Type:     widgets.ConnectionFieldString,
				Label:    "Developer token reference",
				Required: true,
				Secret:   true,
				Help:     "Use a secret reference such as env:APPLE_MUSIC_DEVELOPER_TOKEN.",
			},
			{
				ID:     "user_token",
				Type:   widgets.ConnectionFieldString,
				Label:  "Music user token reference",
				Secret: true,
				Help:   "Optional. Generated by MusicKit login, or set manually with a secret reference.",
			},
		},
	}}
}

func (w *AppleMusicWidget) FetchData(_ context.Context, _ map[string]any) (any, error) {
	slog.Debug( //nolint:sloglint // default permitted for widgets
		"fetching apple music data",
	)
	return widgets.Unavailable(
		"connection.missing",
		"Apple Music account needed",
		"Choose an Apple Music Account connection in settings.",
	), nil
}

func (w *AppleMusicWidget) FetchDataWithConnections(
	ctx context.Context,
	input widgets.RuntimeInput,
) (widgets.RuntimePayload, error) {
	settings := appleMusicSettingsFromConnection(input.Connections["account"])
	if string(settings.DeveloperToken) == "" {
		return widgets.Unavailable(
			"connection.missing_credentials",
			"Apple Music account needed",
			"Choose an Apple Music Account connection in settings.",
		), nil
	}
	if string(settings.UserToken) == "" {
		return widgets.OK(map[string]any{
			"track_title":      "Not Playing",
			"artist_name":      "Unknown",
			"album_art_url":    "",
			"is_playing":       false,
			"volume":           50,
			"progress_ms":      0,
			"duration_ms":      0,
			"shuffle":          false,
			"repeat_state":     "off",
			"top_albums":       []map[string]any{},
			"needs_user_token": true,
		}), nil
	}
	client := provider.NewClient(providerSettings(settings))
	playback, err := client.FetchPlayback(ctx)
	if err != nil {
		return widgets.Unavailable( //nolint:nilerr // provider error is mapped to a safe widget issue
			"apple_music.unavailable",
			"Apple Music unavailable",
			"Jute could not load Apple Music playback.",
		), nil
	}
	if len(playback.TopAlbums) == 0 {
		playback.TopAlbums = appleMusicSuggestions.get(
			ctx,
			appleMusicSuggestionCacheKey(input),
			client.FetchSuggestedAlbums,
		)
	}
	return widgets.OK(appleMusicPlaybackData(playback)), nil
}

func appleMusicPlaybackData(playback provider.Playback) map[string]any {
	return map[string]any{
		"track_title":      playback.TrackTitle,
		"artist_name":      playback.ArtistName,
		"album_art_url":    playback.AlbumArtURL,
		"track_uri":        playback.URI,
		"is_playing":       playback.IsPlaying,
		"volume":           playback.Volume,
		"progress_ms":      playback.ProgressMS,
		"duration_ms":      playback.DurationMS,
		"shuffle":          playback.Shuffle,
		"repeat_state":     playback.RepeatState,
		"top_albums":       playback.TopAlbums,
		"needs_user_token": false,
	}
}

func (w *AppleMusicWidget) Skill() *widgetskills.Definition {
	return &widgetskills.Definition{
		SkillID:             SkillID,
		WidgetKind:          Kind,
		DisplayName:         "Apple Music Control",
		Summary:             "Read playback status and trigger playback control actions on Apple Music.",
		RequiredPermissions: []string{"agent:skill"},
		VisibilityPolicy:    "visible_or_focused",
		ContextFields: []widgetskills.Field{
			{Name: "track_title", Type: "string", Description: "Currently playing song title.", Sensitivity: "public"},
			{Name: "artist_name", Type: "string", Description: "Artist name.", Sensitivity: "public"},
			{Name: "album_art_url", Type: "string", Description: "Album art URL for display.", Sensitivity: "public"},
			{Name: "is_playing", Type: "boolean", Description: "Is music active.", Sensitivity: "public"},
			{
				Name:        "top_albums",
				Type:        "array",
				Description: "Album quick picks derived from Apple Music user data.",
				Sensitivity: "public",
			},
		},
		Actions: appleMusicSkillActions(),
	}
}

func providerSettings(settings Settings) provider.Settings {
	return provider.Settings{
		DeveloperToken: string(settings.DeveloperToken),
		UserToken:      string(settings.UserToken),
	}
}

func (w *AppleMusicWidget) InvokeActionWithConnections(
	ctx context.Context,
	input widgets.ActionInput,
) (map[string]any, error) {
	settings := appleMusicSettingsFromConnection(input.Connections["account"])
	slog.Info( //nolint:sloglint // use default global logger
		"apple music action invoked",
		"actionID", input.ActionID,
	)
	client := provider.NewClient(providerSettings(settings))
	return invokeAppleMusicAction(ctx, client, input.ActionID, input.Arguments)
}

func appleMusicSettingsFromConnection(connection widgets.ResolvedConnection) Settings {
	return Settings{
		DeveloperToken: SecretString(connection.Secrets["developer_token"]),
		UserToken:      SecretString(connection.Secrets["user_token"]),
	}
}

func init() {
	widgets.RegisterWithSkill(&AppleMusicWidget{}, func(snapshot widgetskills.Snapshot, instID string) map[string]any {
		for _, w := range snapshot.Layout.Widgets {
			if w.ID == instID {
				if m, ok := widgets.PayloadData(w.Data).(map[string]any); ok {
					return m
				}
			}
		}
		return map[string]any{
			"track_title":   "Not Playing",
			"artist_name":   "Unknown",
			"album_art_url": "",
			"is_playing":    false,
			"volume":        50,
			"progress_ms":   0,
			"duration_ms":   0,
			"shuffle":       false,
			"repeat_state":  "off",
			"top_albums":    []map[string]any{},
		}
	})
}

type appleMusicActionHandler func(
	ctx context.Context,
	client provider.Client,
	arguments map[string]any,
) (map[string]any, error)

type appleMusicActionCatalogItem struct {
	action widgetskills.Action
	handle appleMusicActionHandler
}

var appleMusicActionCatalog = []appleMusicActionCatalogItem{
	{
		action: widgetskills.ReadAction("status", "Get playback status", "Read current Apple Music track and status."),
		handle: func(ctx context.Context, client provider.Client, _ map[string]any) (map[string]any, error) {
			playback, err := client.FetchPlayback(ctx)
			if err != nil {
				return nil, err
			}
			return appleMusicPlaybackData(playback), nil
		},
	},
	{
		action: appleMusicSearchAction(),
		handle: func(ctx context.Context, client provider.Client, arguments map[string]any) (map[string]any, error) {
			query := stringArgument(arguments, "query")
			itemType := stringArgument(arguments, "type")
			if itemType == "" {
				itemType = "track"
			}
			limit := intArgument(arguments, "limit", 5)
			results, err := client.Search(ctx, query, itemType, limit)
			if err != nil {
				return nil, err
			}
			return map[string]any{"results": results}, nil
		},
	},
	appleMusicPlaybackCatalogItem("play", "Play", "Start Apple Music playback."),
	appleMusicPlaybackCatalogItem("pause", "Pause", "Pause Apple Music playback."),
	appleMusicPlaybackCatalogItem("next", "Next track", "Skip to the next Apple Music track."),
	appleMusicPlaybackCatalogItem("previous", "Previous track", "Return to the previous Apple Music track."),
	appleMusicPlaybackCatalogItem(
		"restart_track",
		"Restart track",
		"Restart the current Apple Music track from the beginning.",
	),
	appleMusicPlaybackCatalogItem("seek", "Seek", "Seek within the current Apple Music track."),
	appleMusicPlaybackCatalogItem(
		"play_album",
		"Play album",
		"Search for and play an Apple Music album by query or URI.",
	),
	appleMusicPlaybackCatalogItem(
		"play_track",
		"Play song",
		"Search for and play an Apple Music song by query or URI.",
	),
	appleMusicPlaybackCatalogItem(
		"play_playlist",
		"Play playlist",
		"Search for and play an Apple Music playlist by query or URI.",
	),
	appleMusicPlaybackCatalogItem("set_volume", "Set volume", "Set Apple Music player volume."),
	appleMusicPlaybackCatalogItem("set_shuffle", "Set shuffle", "Enable or disable Apple Music shuffle."),
	appleMusicPlaybackCatalogItem("set_repeat", "Set repeat", "Set Apple Music repeat mode to off, context, or track."),
}

func appleMusicSkillActions() []widgetskills.Action {
	actions := make([]widgetskills.Action, 0, len(appleMusicActionCatalog))
	for _, item := range appleMusicActionCatalog {
		actions = append(actions, item.action)
	}
	return actions
}

func invokeAppleMusicAction(
	ctx context.Context,
	client provider.Client,
	actionID string,
	arguments map[string]any,
) (map[string]any, error) {
	for _, item := range appleMusicActionCatalog {
		if item.action.ID == actionID {
			return item.handle(ctx, client, arguments)
		}
	}
	return nil, fmt.Errorf("unknown action: %s", actionID)
}

func appleMusicSearchAction() widgetskills.Action {
	return widgetskills.Action{
		ID:                   "search",
		Title:                "Search",
		Description:          "Search Apple Music albums, songs, or playlists and return safe suggestions.",
		SideEffect:           "read",
		RequiresConfirmation: false,
		InputSchema: map[string]any{
			"type": "object",
			"properties": map[string]any{
				"query": map[string]any{"type": "string", "description": "Apple Music search query."},
				"type": map[string]any{
					"type":        "string",
					"enum":        []string{"album", "track", "playlist"},
					"description": "Search result type.",
				},
				"limit": map[string]any{
					"type":        "number",
					"minimum":     1,
					"maximum":     10,
					"description": "Maximum number of suggestions.",
				},
			},
			"required":             []string{"query", "type"},
			"additionalProperties": false,
		},
		OutputSchema: map[string]any{
			"type":       "object",
			"properties": map[string]any{"results": map[string]any{"type": "array"}},
			"required":   []string{"results"},
		},
	}
}

func appleMusicPlaybackCatalogItem(id, title, description string) appleMusicActionCatalogItem {
	return appleMusicActionCatalogItem{
		action: appleMusicPlaybackAction(id, title, description),
		handle: func(ctx context.Context, client provider.Client, arguments map[string]any) (map[string]any, error) {
			if err := client.ApplyAction(ctx, id, arguments); err != nil {
				return nil, err
			}
			return map[string]any{"status": "ok"}, nil
		},
	}
}

func appleMusicPlaybackAction(id, title, description string) widgetskills.Action {
	properties := map[string]any{}
	switch id {
	case "set_volume":
		properties["volume"] = map[string]any{"type": "number", "minimum": 0, "maximum": 100}
	case "set_shuffle":
		properties["state"] = map[string]any{"type": "boolean"}
	case "set_repeat":
		properties["state"] = map[string]any{"type": "string", "enum": []string{"off", "context", "track"}}
	case "seek":
		properties["position_ms"] = map[string]any{"type": "number", "minimum": 0}
	case "play", "play_album", "play_track", "play_playlist":
		properties["uri"] = map[string]any{"type": "string"}
		properties["query"] = map[string]any{"type": "string"}
	}
	return widgetskills.Action{
		ID:                   id,
		Title:                title,
		Description:          description,
		SideEffect:           "home_action",
		RequiresConfirmation: false,
		InputSchema: map[string]any{
			"type":                 "object",
			"properties":           properties,
			"additionalProperties": true,
		},
		OutputSchema: map[string]any{
			"type":       "object",
			"properties": map[string]any{"status": map[string]any{"type": "string"}},
			"required":   []string{"status"},
		},
	}
}

func stringArgument(arguments map[string]any, key string) string {
	value, _ := arguments[key].(string)
	return strings.TrimSpace(value)
}

func intArgument(arguments map[string]any, key string, fallback int) int {
	switch value := arguments[key].(type) {
	case int:
		if value > 0 {
			return value
		}
	case float64:
		if value > 0 {
			return int(value)
		}
	}
	return fallback
}

func appleMusicSuggestionCacheKey(input widgets.RuntimeInput) string {
	if connection := input.Connections["account"]; connection.ID != "" {
		return connection.ID
	}
	if ref := input.ConnectionRefs["account"]; ref != "" {
		return ref
	}
	return input.InstanceID + ":account"
}

type appleMusicSuggestionFetcher func(context.Context, int) ([]provider.PlayableItem, error)

type appleMusicSuggestionCache struct {
	mu      sync.Mutex
	entries map[string]appleMusicSuggestionCacheEntry
	now     func() time.Time
}

type appleMusicSuggestionCacheEntry struct {
	items      []provider.PlayableItem
	expiresAt  time.Time
	retryAfter time.Time
}

func newAppleMusicSuggestionCache() *appleMusicSuggestionCache {
	return &appleMusicSuggestionCache{
		entries: map[string]appleMusicSuggestionCacheEntry{},
		now:     time.Now,
	}
}

func (c *appleMusicSuggestionCache) get(
	ctx context.Context,
	key string,
	fetch appleMusicSuggestionFetcher,
) []provider.PlayableItem {
	now := c.now()
	c.mu.Lock()
	entry := c.entries[key]
	if len(entry.items) > 0 && now.Before(entry.expiresAt) {
		items := cloneAppleMusicItems(entry.items)
		c.mu.Unlock()
		return items
	}
	if now.Before(entry.retryAfter) {
		items := cloneAppleMusicItems(entry.items)
		c.mu.Unlock()
		return items
	}
	c.mu.Unlock()

	items, err := fetch(ctx, 8)

	c.mu.Lock()
	defer c.mu.Unlock()
	if err != nil {
		entry.retryAfter = now.Add(5 * time.Minute)
		c.entries[key] = entry
		return cloneAppleMusicItems(entry.items)
	}
	entry.items = cloneAppleMusicItems(items)
	if len(items) > 0 {
		entry.expiresAt = now.Add(30 * time.Minute)
	} else {
		entry.expiresAt = now.Add(5 * time.Minute)
	}
	entry.retryAfter = time.Time{}
	c.entries[key] = entry
	return cloneAppleMusicItems(entry.items)
}

func cloneAppleMusicItems(items []provider.PlayableItem) []provider.PlayableItem {
	if len(items) == 0 {
		return nil
	}
	out := make([]provider.PlayableItem, len(items))
	copy(out, items)
	return out
}
