// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	widgetskills "jute-dash/apps/hub/pkg/widgetskills"

	mock "github.com/stretchr/testify/mock"
)

// ActionFunc is an autogenerated mock type for the ActionFunc type
type ActionFunc struct {
	mock.Mock
}

type ActionFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *ActionFunc) EXPECT() *ActionFunc_Expecter {
	return &ActionFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, snapshot, instanceID, actionID, arguments
func (_m *ActionFunc) Execute(ctx context.Context, snapshot widgetskills.Snapshot, instanceID string, actionID string, arguments map[string]interface{}) (map[string]interface{}, error) {
	ret := _m.Called(ctx, snapshot, instanceID, actionID, arguments)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, widgetskills.Snapshot, string, string, map[string]interface{}) (map[string]interface{}, error)); ok {
		return rf(ctx, snapshot, instanceID, actionID, arguments)
	}
	if rf, ok := ret.Get(0).(func(context.Context, widgetskills.Snapshot, string, string, map[string]interface{}) map[string]interface{}); ok {
		r0 = rf(ctx, snapshot, instanceID, actionID, arguments)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, widgetskills.Snapshot, string, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, snapshot, instanceID, actionID, arguments)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ActionFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ActionFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - snapshot widgetskills.Snapshot
//   - instanceID string
//   - actionID string
//   - arguments map[string]interface{}
func (_e *ActionFunc_Expecter) Execute(ctx interface{}, snapshot interface{}, instanceID interface{}, actionID interface{}, arguments interface{}) *ActionFunc_Execute_Call {
	return &ActionFunc_Execute_Call{Call: _e.mock.On("Execute", ctx, snapshot, instanceID, actionID, arguments)}
}

func (_c *ActionFunc_Execute_Call) Run(run func(ctx context.Context, snapshot widgetskills.Snapshot, instanceID string, actionID string, arguments map[string]interface{})) *ActionFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(widgetskills.Snapshot), args[2].(string), args[3].(string), args[4].(map[string]interface{}))
	})
	return _c
}

func (_c *ActionFunc_Execute_Call) Return(_a0 map[string]interface{}, _a1 error) *ActionFunc_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ActionFunc_Execute_Call) RunAndReturn(run func(context.Context, widgetskills.Snapshot, string, string, map[string]interface{}) (map[string]interface{}, error)) *ActionFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewActionFunc creates a new instance of ActionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewActionFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *ActionFunc {
	mock := &ActionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
