// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	homestate "jute-dash/apps/hub/internal/app/service/homestate"

	mock "github.com/stretchr/testify/mock"
)

// adapterConnectionStore is an autogenerated mock type for the adapterConnectionStore type
type adapterConnectionStore struct {
	mock.Mock
}

type adapterConnectionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *adapterConnectionStore) EXPECT() *adapterConnectionStore_Expecter {
	return &adapterConnectionStore_Expecter{mock: &_m.Mock}
}

// AdapterConnection provides a mock function with given fields: ctx, id
func (_m *adapterConnectionStore) AdapterConnection(ctx context.Context, id string) (homestate.AdapterConnection, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AdapterConnection")
	}

	var r0 homestate.AdapterConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (homestate.AdapterConnection, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) homestate.AdapterConnection); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(homestate.AdapterConnection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// adapterConnectionStore_AdapterConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdapterConnection'
type adapterConnectionStore_AdapterConnection_Call struct {
	*mock.Call
}

// AdapterConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *adapterConnectionStore_Expecter) AdapterConnection(ctx interface{}, id interface{}) *adapterConnectionStore_AdapterConnection_Call {
	return &adapterConnectionStore_AdapterConnection_Call{Call: _e.mock.On("AdapterConnection", ctx, id)}
}

func (_c *adapterConnectionStore_AdapterConnection_Call) Run(run func(ctx context.Context, id string)) *adapterConnectionStore_AdapterConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *adapterConnectionStore_AdapterConnection_Call) Return(_a0 homestate.AdapterConnection, _a1 error) *adapterConnectionStore_AdapterConnection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *adapterConnectionStore_AdapterConnection_Call) RunAndReturn(run func(context.Context, string) (homestate.AdapterConnection, error)) *adapterConnectionStore_AdapterConnection_Call {
	_c.Call.Return(run)
	return _c
}

// newAdapterConnectionStore creates a new instance of adapterConnectionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newAdapterConnectionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *adapterConnectionStore {
	mock := &adapterConnectionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
