// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	widgetskills "jute-dash/apps/hub/pkg/widgetskills"

	mock "github.com/stretchr/testify/mock"
)

// ContextFunc is an autogenerated mock type for the ContextFunc type
type ContextFunc struct {
	mock.Mock
}

type ContextFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *ContextFunc) EXPECT() *ContextFunc_Expecter {
	return &ContextFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: snapshot, instanceID
func (_m *ContextFunc) Execute(snapshot widgetskills.Snapshot, instanceID string) map[string]interface{} {
	ret := _m.Called(snapshot, instanceID)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(widgetskills.Snapshot, string) map[string]interface{}); ok {
		r0 = rf(snapshot, instanceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// ContextFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ContextFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - snapshot widgetskills.Snapshot
//   - instanceID string
func (_e *ContextFunc_Expecter) Execute(snapshot interface{}, instanceID interface{}) *ContextFunc_Execute_Call {
	return &ContextFunc_Execute_Call{Call: _e.mock.On("Execute", snapshot, instanceID)}
}

func (_c *ContextFunc_Execute_Call) Run(run func(snapshot widgetskills.Snapshot, instanceID string)) *ContextFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(widgetskills.Snapshot), args[1].(string))
	})
	return _c
}

func (_c *ContextFunc_Execute_Call) Return(_a0 map[string]interface{}) *ContextFunc_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ContextFunc_Execute_Call) RunAndReturn(run func(widgetskills.Snapshot, string) map[string]interface{}) *ContextFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewContextFunc creates a new instance of ContextFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewContextFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *ContextFunc {
	mock := &ContextFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
