// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "jute-dash/apps/hub/internal/app/model"
)

// DashboardLayoutStore is an autogenerated mock type for the DashboardLayoutStore type
type DashboardLayoutStore struct {
	mock.Mock
}

type DashboardLayoutStore_Expecter struct {
	mock *mock.Mock
}

func (_m *DashboardLayoutStore) EXPECT() *DashboardLayoutStore_Expecter {
	return &DashboardLayoutStore_Expecter{mock: &_m.Mock}
}

// ResetWidgetLayout provides a mock function with given fields: ctx, profileID
func (_m *DashboardLayoutStore) ResetWidgetLayout(ctx context.Context, profileID string) (model.WidgetLayout, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for ResetWidgetLayout")
	}

	var r0 model.WidgetLayout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.WidgetLayout, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.WidgetLayout); ok {
		r0 = rf(ctx, profileID)
	} else {
		r0 = ret.Get(0).(model.WidgetLayout)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DashboardLayoutStore_ResetWidgetLayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetWidgetLayout'
type DashboardLayoutStore_ResetWidgetLayout_Call struct {
	*mock.Call
}

// ResetWidgetLayout is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID string
func (_e *DashboardLayoutStore_Expecter) ResetWidgetLayout(ctx interface{}, profileID interface{}) *DashboardLayoutStore_ResetWidgetLayout_Call {
	return &DashboardLayoutStore_ResetWidgetLayout_Call{Call: _e.mock.On("ResetWidgetLayout", ctx, profileID)}
}

func (_c *DashboardLayoutStore_ResetWidgetLayout_Call) Run(run func(ctx context.Context, profileID string)) *DashboardLayoutStore_ResetWidgetLayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DashboardLayoutStore_ResetWidgetLayout_Call) Return(_a0 model.WidgetLayout, _a1 error) *DashboardLayoutStore_ResetWidgetLayout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DashboardLayoutStore_ResetWidgetLayout_Call) RunAndReturn(run func(context.Context, string) (model.WidgetLayout, error)) *DashboardLayoutStore_ResetWidgetLayout_Call {
	_c.Call.Return(run)
	return _c
}

// SaveWidgetLayout provides a mock function with given fields: ctx, layout
func (_m *DashboardLayoutStore) SaveWidgetLayout(ctx context.Context, layout model.WidgetLayout) (model.WidgetLayout, error) {
	ret := _m.Called(ctx, layout)

	if len(ret) == 0 {
		panic("no return value specified for SaveWidgetLayout")
	}

	var r0 model.WidgetLayout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.WidgetLayout) (model.WidgetLayout, error)); ok {
		return rf(ctx, layout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.WidgetLayout) model.WidgetLayout); ok {
		r0 = rf(ctx, layout)
	} else {
		r0 = ret.Get(0).(model.WidgetLayout)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.WidgetLayout) error); ok {
		r1 = rf(ctx, layout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DashboardLayoutStore_SaveWidgetLayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWidgetLayout'
type DashboardLayoutStore_SaveWidgetLayout_Call struct {
	*mock.Call
}

// SaveWidgetLayout is a helper method to define mock.On call
//   - ctx context.Context
//   - layout model.WidgetLayout
func (_e *DashboardLayoutStore_Expecter) SaveWidgetLayout(ctx interface{}, layout interface{}) *DashboardLayoutStore_SaveWidgetLayout_Call {
	return &DashboardLayoutStore_SaveWidgetLayout_Call{Call: _e.mock.On("SaveWidgetLayout", ctx, layout)}
}

func (_c *DashboardLayoutStore_SaveWidgetLayout_Call) Run(run func(ctx context.Context, layout model.WidgetLayout)) *DashboardLayoutStore_SaveWidgetLayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.WidgetLayout))
	})
	return _c
}

func (_c *DashboardLayoutStore_SaveWidgetLayout_Call) Return(_a0 model.WidgetLayout, _a1 error) *DashboardLayoutStore_SaveWidgetLayout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DashboardLayoutStore_SaveWidgetLayout_Call) RunAndReturn(run func(context.Context, model.WidgetLayout) (model.WidgetLayout, error)) *DashboardLayoutStore_SaveWidgetLayout_Call {
	_c.Call.Return(run)
	return _c
}

// SetActiveScreen provides a mock function with given fields: ctx, profileID, screenID
func (_m *DashboardLayoutStore) SetActiveScreen(ctx context.Context, profileID string, screenID string) (model.WidgetLayout, error) {
	ret := _m.Called(ctx, profileID, screenID)

	if len(ret) == 0 {
		panic("no return value specified for SetActiveScreen")
	}

	var r0 model.WidgetLayout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (model.WidgetLayout, error)); ok {
		return rf(ctx, profileID, screenID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) model.WidgetLayout); ok {
		r0 = rf(ctx, profileID, screenID)
	} else {
		r0 = ret.Get(0).(model.WidgetLayout)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, profileID, screenID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DashboardLayoutStore_SetActiveScreen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActiveScreen'
type DashboardLayoutStore_SetActiveScreen_Call struct {
	*mock.Call
}

// SetActiveScreen is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID string
//   - screenID string
func (_e *DashboardLayoutStore_Expecter) SetActiveScreen(ctx interface{}, profileID interface{}, screenID interface{}) *DashboardLayoutStore_SetActiveScreen_Call {
	return &DashboardLayoutStore_SetActiveScreen_Call{Call: _e.mock.On("SetActiveScreen", ctx, profileID, screenID)}
}

func (_c *DashboardLayoutStore_SetActiveScreen_Call) Run(run func(ctx context.Context, profileID string, screenID string)) *DashboardLayoutStore_SetActiveScreen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *DashboardLayoutStore_SetActiveScreen_Call) Return(_a0 model.WidgetLayout, _a1 error) *DashboardLayoutStore_SetActiveScreen_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DashboardLayoutStore_SetActiveScreen_Call) RunAndReturn(run func(context.Context, string, string) (model.WidgetLayout, error)) *DashboardLayoutStore_SetActiveScreen_Call {
	_c.Call.Return(run)
	return _c
}

// WidgetLayout provides a mock function with given fields: ctx, profileID
func (_m *DashboardLayoutStore) WidgetLayout(ctx context.Context, profileID string) (model.WidgetLayout, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for WidgetLayout")
	}

	var r0 model.WidgetLayout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.WidgetLayout, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.WidgetLayout); ok {
		r0 = rf(ctx, profileID)
	} else {
		r0 = ret.Get(0).(model.WidgetLayout)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DashboardLayoutStore_WidgetLayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WidgetLayout'
type DashboardLayoutStore_WidgetLayout_Call struct {
	*mock.Call
}

// WidgetLayout is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID string
func (_e *DashboardLayoutStore_Expecter) WidgetLayout(ctx interface{}, profileID interface{}) *DashboardLayoutStore_WidgetLayout_Call {
	return &DashboardLayoutStore_WidgetLayout_Call{Call: _e.mock.On("WidgetLayout", ctx, profileID)}
}

func (_c *DashboardLayoutStore_WidgetLayout_Call) Run(run func(ctx context.Context, profileID string)) *DashboardLayoutStore_WidgetLayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *DashboardLayoutStore_WidgetLayout_Call) Return(_a0 model.WidgetLayout, _a1 error) *DashboardLayoutStore_WidgetLayout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DashboardLayoutStore_WidgetLayout_Call) RunAndReturn(run func(context.Context, string) (model.WidgetLayout, error)) *DashboardLayoutStore_WidgetLayout_Call {
	_c.Call.Return(run)
	return _c
}

// NewDashboardLayoutStore creates a new instance of DashboardLayoutStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDashboardLayoutStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *DashboardLayoutStore {
	mock := &DashboardLayoutStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
