// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	displayactions "jute-dash/apps/hub/internal/pkg/displayactions"

	mock "github.com/stretchr/testify/mock"
)

// DisplayActions is an autogenerated mock type for the DisplayActions type
type DisplayActions struct {
	mock.Mock
}

type DisplayActions_Expecter struct {
	mock *mock.Mock
}

func (_m *DisplayActions) EXPECT() *DisplayActions_Expecter {
	return &DisplayActions_Expecter{mock: &_m.Mock}
}

// FocusWidget provides a mock function with given fields: widgetInstanceID, reason
func (_m *DisplayActions) FocusWidget(widgetInstanceID string, reason string) (displayactions.FocusWidget, error) {
	ret := _m.Called(widgetInstanceID, reason)

	if len(ret) == 0 {
		panic("no return value specified for FocusWidget")
	}

	var r0 displayactions.FocusWidget
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (displayactions.FocusWidget, error)); ok {
		return rf(widgetInstanceID, reason)
	}
	if rf, ok := ret.Get(0).(func(string, string) displayactions.FocusWidget); ok {
		r0 = rf(widgetInstanceID, reason)
	} else {
		r0 = ret.Get(0).(displayactions.FocusWidget)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(widgetInstanceID, reason)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DisplayActions_FocusWidget_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FocusWidget'
type DisplayActions_FocusWidget_Call struct {
	*mock.Call
}

// FocusWidget is a helper method to define mock.On call
//   - widgetInstanceID string
//   - reason string
func (_e *DisplayActions_Expecter) FocusWidget(widgetInstanceID interface{}, reason interface{}) *DisplayActions_FocusWidget_Call {
	return &DisplayActions_FocusWidget_Call{Call: _e.mock.On("FocusWidget", widgetInstanceID, reason)}
}

func (_c *DisplayActions_FocusWidget_Call) Run(run func(widgetInstanceID string, reason string)) *DisplayActions_FocusWidget_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *DisplayActions_FocusWidget_Call) Return(_a0 displayactions.FocusWidget, _a1 error) *DisplayActions_FocusWidget_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DisplayActions_FocusWidget_Call) RunAndReturn(run func(string, string) (displayactions.FocusWidget, error)) *DisplayActions_FocusWidget_Call {
	_c.Call.Return(run)
	return _c
}

// Notify provides a mock function with given fields: message, severity
func (_m *DisplayActions) Notify(message string, severity string) (displayactions.Notification, error) {
	ret := _m.Called(message, severity)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 displayactions.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (displayactions.Notification, error)); ok {
		return rf(message, severity)
	}
	if rf, ok := ret.Get(0).(func(string, string) displayactions.Notification); ok {
		r0 = rf(message, severity)
	} else {
		r0 = ret.Get(0).(displayactions.Notification)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(message, severity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DisplayActions_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type DisplayActions_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - message string
//   - severity string
func (_e *DisplayActions_Expecter) Notify(message interface{}, severity interface{}) *DisplayActions_Notify_Call {
	return &DisplayActions_Notify_Call{Call: _e.mock.On("Notify", message, severity)}
}

func (_c *DisplayActions_Notify_Call) Run(run func(message string, severity string)) *DisplayActions_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *DisplayActions_Notify_Call) Return(_a0 displayactions.Notification, _a1 error) *DisplayActions_Notify_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *DisplayActions_Notify_Call) RunAndReturn(run func(string, string) (displayactions.Notification, error)) *DisplayActions_Notify_Call {
	_c.Call.Return(run)
	return _c
}

// NewDisplayActions creates a new instance of DisplayActions. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDisplayActions(t interface {
	mock.TestingT
	Cleanup(func())
}) *DisplayActions {
	mock := &DisplayActions{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
