// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// EchoRouter is an autogenerated mock type for the EchoRouter type
type EchoRouter struct {
	mock.Mock
}

type EchoRouter_Expecter struct {
	mock *mock.Mock
}

func (_m *EchoRouter) EXPECT() *EchoRouter_Expecter {
	return &EchoRouter_Expecter{mock: &_m.Mock}
}

// CONNECT provides a mock function with given fields: path, h, m
func (_m *EchoRouter) CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route {
	_va := make([]interface{}, len(m))
	for _i := range m {
		_va[_i] = m[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, path, h)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CONNECT")
	}

	var r0 *echo.Route
	if rf, ok := ret.Get(0).(func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route); ok {
		r0 = rf(path, h, m...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*echo.Route)
		}
	}

	return r0
}

// EchoRouter_CONNECT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CONNECT'
type EchoRouter_CONNECT_Call struct {
	*mock.Call
}

// CONNECT is a helper method to define mock.On call
//   - path string
//   - h echo.HandlerFunc
//   - m ...echo.MiddlewareFunc
func (_e *EchoRouter_Expecter) CONNECT(path interface{}, h interface{}, m ...interface{}) *EchoRouter_CONNECT_Call {
	return &EchoRouter_CONNECT_Call{Call: _e.mock.On("CONNECT",
		append([]interface{}{path, h}, m...)...)}
}

func (_c *EchoRouter_CONNECT_Call) Run(run func(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc)) *EchoRouter_CONNECT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]echo.MiddlewareFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(echo.MiddlewareFunc)
			}
		}
		run(args[0].(string), args[1].(echo.HandlerFunc), variadicArgs...)
	})
	return _c
}

func (_c *EchoRouter_CONNECT_Call) Return(_a0 *echo.Route) *EchoRouter_CONNECT_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EchoRouter_CONNECT_Call) RunAndReturn(run func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route) *EchoRouter_CONNECT_Call {
	_c.Call.Return(run)
	return _c
}

// DELETE provides a mock function with given fields: path, h, m
func (_m *EchoRouter) DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route {
	_va := make([]interface{}, len(m))
	for _i := range m {
		_va[_i] = m[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, path, h)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DELETE")
	}

	var r0 *echo.Route
	if rf, ok := ret.Get(0).(func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route); ok {
		r0 = rf(path, h, m...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*echo.Route)
		}
	}

	return r0
}

// EchoRouter_DELETE_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DELETE'
type EchoRouter_DELETE_Call struct {
	*mock.Call
}

// DELETE is a helper method to define mock.On call
//   - path string
//   - h echo.HandlerFunc
//   - m ...echo.MiddlewareFunc
func (_e *EchoRouter_Expecter) DELETE(path interface{}, h interface{}, m ...interface{}) *EchoRouter_DELETE_Call {
	return &EchoRouter_DELETE_Call{Call: _e.mock.On("DELETE",
		append([]interface{}{path, h}, m...)...)}
}

func (_c *EchoRouter_DELETE_Call) Run(run func(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc)) *EchoRouter_DELETE_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]echo.MiddlewareFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(echo.MiddlewareFunc)
			}
		}
		run(args[0].(string), args[1].(echo.HandlerFunc), variadicArgs...)
	})
	return _c
}

func (_c *EchoRouter_DELETE_Call) Return(_a0 *echo.Route) *EchoRouter_DELETE_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EchoRouter_DELETE_Call) RunAndReturn(run func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route) *EchoRouter_DELETE_Call {
	_c.Call.Return(run)
	return _c
}

// GET provides a mock function with given fields: path, h, m
func (_m *EchoRouter) GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route {
	_va := make([]interface{}, len(m))
	for _i := range m {
		_va[_i] = m[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, path, h)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GET")
	}

	var r0 *echo.Route
	if rf, ok := ret.Get(0).(func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route); ok {
		r0 = rf(path, h, m...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*echo.Route)
		}
	}

	return r0
}

// EchoRouter_GET_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GET'
type EchoRouter_GET_Call struct {
	*mock.Call
}

// GET is a helper method to define mock.On call
//   - path string
//   - h echo.HandlerFunc
//   - m ...echo.MiddlewareFunc
func (_e *EchoRouter_Expecter) GET(path interface{}, h interface{}, m ...interface{}) *EchoRouter_GET_Call {
	return &EchoRouter_GET_Call{Call: _e.mock.On("GET",
		append([]interface{}{path, h}, m...)...)}
}

func (_c *EchoRouter_GET_Call) Run(run func(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc)) *EchoRouter_GET_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]echo.MiddlewareFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(echo.MiddlewareFunc)
			}
		}
		run(args[0].(string), args[1].(echo.HandlerFunc), variadicArgs...)
	})
	return _c
}

func (_c *EchoRouter_GET_Call) Return(_a0 *echo.Route) *EchoRouter_GET_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EchoRouter_GET_Call) RunAndReturn(run func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route) *EchoRouter_GET_Call {
	_c.Call.Return(run)
	return _c
}

// HEAD provides a mock function with given fields: path, h, m
func (_m *EchoRouter) HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route {
	_va := make([]interface{}, len(m))
	for _i := range m {
		_va[_i] = m[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, path, h)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for HEAD")
	}

	var r0 *echo.Route
	if rf, ok := ret.Get(0).(func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route); ok {
		r0 = rf(path, h, m...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*echo.Route)
		}
	}

	return r0
}

// EchoRouter_HEAD_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HEAD'
type EchoRouter_HEAD_Call struct {
	*mock.Call
}

// HEAD is a helper method to define mock.On call
//   - path string
//   - h echo.HandlerFunc
//   - m ...echo.MiddlewareFunc
func (_e *EchoRouter_Expecter) HEAD(path interface{}, h interface{}, m ...interface{}) *EchoRouter_HEAD_Call {
	return &EchoRouter_HEAD_Call{Call: _e.mock.On("HEAD",
		append([]interface{}{path, h}, m...)...)}
}

func (_c *EchoRouter_HEAD_Call) Run(run func(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc)) *EchoRouter_HEAD_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]echo.MiddlewareFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(echo.MiddlewareFunc)
			}
		}
		run(args[0].(string), args[1].(echo.HandlerFunc), variadicArgs...)
	})
	return _c
}

func (_c *EchoRouter_HEAD_Call) Return(_a0 *echo.Route) *EchoRouter_HEAD_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EchoRouter_HEAD_Call) RunAndReturn(run func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route) *EchoRouter_HEAD_Call {
	_c.Call.Return(run)
	return _c
}

// OPTIONS provides a mock function with given fields: path, h, m
func (_m *EchoRouter) OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route {
	_va := make([]interface{}, len(m))
	for _i := range m {
		_va[_i] = m[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, path, h)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for OPTIONS")
	}

	var r0 *echo.Route
	if rf, ok := ret.Get(0).(func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route); ok {
		r0 = rf(path, h, m...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*echo.Route)
		}
	}

	return r0
}

// EchoRouter_OPTIONS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OPTIONS'
type EchoRouter_OPTIONS_Call struct {
	*mock.Call
}

// OPTIONS is a helper method to define mock.On call
//   - path string
//   - h echo.HandlerFunc
//   - m ...echo.MiddlewareFunc
func (_e *EchoRouter_Expecter) OPTIONS(path interface{}, h interface{}, m ...interface{}) *EchoRouter_OPTIONS_Call {
	return &EchoRouter_OPTIONS_Call{Call: _e.mock.On("OPTIONS",
		append([]interface{}{path, h}, m...)...)}
}

func (_c *EchoRouter_OPTIONS_Call) Run(run func(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc)) *EchoRouter_OPTIONS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]echo.MiddlewareFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(echo.MiddlewareFunc)
			}
		}
		run(args[0].(string), args[1].(echo.HandlerFunc), variadicArgs...)
	})
	return _c
}

func (_c *EchoRouter_OPTIONS_Call) Return(_a0 *echo.Route) *EchoRouter_OPTIONS_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EchoRouter_OPTIONS_Call) RunAndReturn(run func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route) *EchoRouter_OPTIONS_Call {
	_c.Call.Return(run)
	return _c
}

// PATCH provides a mock function with given fields: path, h, m
func (_m *EchoRouter) PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route {
	_va := make([]interface{}, len(m))
	for _i := range m {
		_va[_i] = m[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, path, h)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PATCH")
	}

	var r0 *echo.Route
	if rf, ok := ret.Get(0).(func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route); ok {
		r0 = rf(path, h, m...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*echo.Route)
		}
	}

	return r0
}

// EchoRouter_PATCH_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PATCH'
type EchoRouter_PATCH_Call struct {
	*mock.Call
}

// PATCH is a helper method to define mock.On call
//   - path string
//   - h echo.HandlerFunc
//   - m ...echo.MiddlewareFunc
func (_e *EchoRouter_Expecter) PATCH(path interface{}, h interface{}, m ...interface{}) *EchoRouter_PATCH_Call {
	return &EchoRouter_PATCH_Call{Call: _e.mock.On("PATCH",
		append([]interface{}{path, h}, m...)...)}
}

func (_c *EchoRouter_PATCH_Call) Run(run func(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc)) *EchoRouter_PATCH_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]echo.MiddlewareFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(echo.MiddlewareFunc)
			}
		}
		run(args[0].(string), args[1].(echo.HandlerFunc), variadicArgs...)
	})
	return _c
}

func (_c *EchoRouter_PATCH_Call) Return(_a0 *echo.Route) *EchoRouter_PATCH_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EchoRouter_PATCH_Call) RunAndReturn(run func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route) *EchoRouter_PATCH_Call {
	_c.Call.Return(run)
	return _c
}

// POST provides a mock function with given fields: path, h, m
func (_m *EchoRouter) POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route {
	_va := make([]interface{}, len(m))
	for _i := range m {
		_va[_i] = m[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, path, h)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for POST")
	}

	var r0 *echo.Route
	if rf, ok := ret.Get(0).(func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route); ok {
		r0 = rf(path, h, m...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*echo.Route)
		}
	}

	return r0
}

// EchoRouter_POST_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'POST'
type EchoRouter_POST_Call struct {
	*mock.Call
}

// POST is a helper method to define mock.On call
//   - path string
//   - h echo.HandlerFunc
//   - m ...echo.MiddlewareFunc
func (_e *EchoRouter_Expecter) POST(path interface{}, h interface{}, m ...interface{}) *EchoRouter_POST_Call {
	return &EchoRouter_POST_Call{Call: _e.mock.On("POST",
		append([]interface{}{path, h}, m...)...)}
}

func (_c *EchoRouter_POST_Call) Run(run func(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc)) *EchoRouter_POST_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]echo.MiddlewareFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(echo.MiddlewareFunc)
			}
		}
		run(args[0].(string), args[1].(echo.HandlerFunc), variadicArgs...)
	})
	return _c
}

func (_c *EchoRouter_POST_Call) Return(_a0 *echo.Route) *EchoRouter_POST_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EchoRouter_POST_Call) RunAndReturn(run func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route) *EchoRouter_POST_Call {
	_c.Call.Return(run)
	return _c
}

// PUT provides a mock function with given fields: path, h, m
func (_m *EchoRouter) PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route {
	_va := make([]interface{}, len(m))
	for _i := range m {
		_va[_i] = m[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, path, h)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PUT")
	}

	var r0 *echo.Route
	if rf, ok := ret.Get(0).(func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route); ok {
		r0 = rf(path, h, m...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*echo.Route)
		}
	}

	return r0
}

// EchoRouter_PUT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PUT'
type EchoRouter_PUT_Call struct {
	*mock.Call
}

// PUT is a helper method to define mock.On call
//   - path string
//   - h echo.HandlerFunc
//   - m ...echo.MiddlewareFunc
func (_e *EchoRouter_Expecter) PUT(path interface{}, h interface{}, m ...interface{}) *EchoRouter_PUT_Call {
	return &EchoRouter_PUT_Call{Call: _e.mock.On("PUT",
		append([]interface{}{path, h}, m...)...)}
}

func (_c *EchoRouter_PUT_Call) Run(run func(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc)) *EchoRouter_PUT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]echo.MiddlewareFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(echo.MiddlewareFunc)
			}
		}
		run(args[0].(string), args[1].(echo.HandlerFunc), variadicArgs...)
	})
	return _c
}

func (_c *EchoRouter_PUT_Call) Return(_a0 *echo.Route) *EchoRouter_PUT_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EchoRouter_PUT_Call) RunAndReturn(run func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route) *EchoRouter_PUT_Call {
	_c.Call.Return(run)
	return _c
}

// TRACE provides a mock function with given fields: path, h, m
func (_m *EchoRouter) TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route {
	_va := make([]interface{}, len(m))
	for _i := range m {
		_va[_i] = m[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, path, h)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for TRACE")
	}

	var r0 *echo.Route
	if rf, ok := ret.Get(0).(func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route); ok {
		r0 = rf(path, h, m...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*echo.Route)
		}
	}

	return r0
}

// EchoRouter_TRACE_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TRACE'
type EchoRouter_TRACE_Call struct {
	*mock.Call
}

// TRACE is a helper method to define mock.On call
//   - path string
//   - h echo.HandlerFunc
//   - m ...echo.MiddlewareFunc
func (_e *EchoRouter_Expecter) TRACE(path interface{}, h interface{}, m ...interface{}) *EchoRouter_TRACE_Call {
	return &EchoRouter_TRACE_Call{Call: _e.mock.On("TRACE",
		append([]interface{}{path, h}, m...)...)}
}

func (_c *EchoRouter_TRACE_Call) Run(run func(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc)) *EchoRouter_TRACE_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]echo.MiddlewareFunc, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(echo.MiddlewareFunc)
			}
		}
		run(args[0].(string), args[1].(echo.HandlerFunc), variadicArgs...)
	})
	return _c
}

func (_c *EchoRouter_TRACE_Call) Return(_a0 *echo.Route) *EchoRouter_TRACE_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EchoRouter_TRACE_Call) RunAndReturn(run func(string, echo.HandlerFunc, ...echo.MiddlewareFunc) *echo.Route) *EchoRouter_TRACE_Call {
	_c.Call.Return(run)
	return _c
}

// NewEchoRouter creates a new instance of EchoRouter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEchoRouter(t interface {
	mock.TestingT
	Cleanup(func())
}) *EchoRouter {
	mock := &EchoRouter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
