// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "jute-dash/apps/hub/internal/app/model"
)

// HomeSettingsStore is an autogenerated mock type for the HomeSettingsStore type
type HomeSettingsStore struct {
	mock.Mock
}

type HomeSettingsStore_Expecter struct {
	mock *mock.Mock
}

func (_m *HomeSettingsStore) EXPECT() *HomeSettingsStore_Expecter {
	return &HomeSettingsStore_Expecter{mock: &_m.Mock}
}

// AdapterConnection provides a mock function with given fields: ctx, id
func (_m *HomeSettingsStore) AdapterConnection(ctx context.Context, id string) (model.AdapterConnection, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for AdapterConnection")
	}

	var r0 model.AdapterConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.AdapterConnection, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.AdapterConnection); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(model.AdapterConnection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HomeSettingsStore_AdapterConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdapterConnection'
type HomeSettingsStore_AdapterConnection_Call struct {
	*mock.Call
}

// AdapterConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *HomeSettingsStore_Expecter) AdapterConnection(ctx interface{}, id interface{}) *HomeSettingsStore_AdapterConnection_Call {
	return &HomeSettingsStore_AdapterConnection_Call{Call: _e.mock.On("AdapterConnection", ctx, id)}
}

func (_c *HomeSettingsStore_AdapterConnection_Call) Run(run func(ctx context.Context, id string)) *HomeSettingsStore_AdapterConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *HomeSettingsStore_AdapterConnection_Call) Return(_a0 model.AdapterConnection, _a1 error) *HomeSettingsStore_AdapterConnection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HomeSettingsStore_AdapterConnection_Call) RunAndReturn(run func(context.Context, string) (model.AdapterConnection, error)) *HomeSettingsStore_AdapterConnection_Call {
	_c.Call.Return(run)
	return _c
}

// AdapterConnections provides a mock function with given fields: ctx
func (_m *HomeSettingsStore) AdapterConnections(ctx context.Context) ([]model.AdapterConnection, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AdapterConnections")
	}

	var r0 []model.AdapterConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.AdapterConnection, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.AdapterConnection); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.AdapterConnection)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HomeSettingsStore_AdapterConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdapterConnections'
type HomeSettingsStore_AdapterConnections_Call struct {
	*mock.Call
}

// AdapterConnections is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HomeSettingsStore_Expecter) AdapterConnections(ctx interface{}) *HomeSettingsStore_AdapterConnections_Call {
	return &HomeSettingsStore_AdapterConnections_Call{Call: _e.mock.On("AdapterConnections", ctx)}
}

func (_c *HomeSettingsStore_AdapterConnections_Call) Run(run func(ctx context.Context)) *HomeSettingsStore_AdapterConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *HomeSettingsStore_AdapterConnections_Call) Return(_a0 []model.AdapterConnection, _a1 error) *HomeSettingsStore_AdapterConnections_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HomeSettingsStore_AdapterConnections_Call) RunAndReturn(run func(context.Context) ([]model.AdapterConnection, error)) *HomeSettingsStore_AdapterConnections_Call {
	_c.Call.Return(run)
	return _c
}

// HouseholdSettings provides a mock function with given fields: ctx
func (_m *HomeSettingsStore) HouseholdSettings(ctx context.Context) (model.HouseholdSettings, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HouseholdSettings")
	}

	var r0 model.HouseholdSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (model.HouseholdSettings, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) model.HouseholdSettings); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(model.HouseholdSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HomeSettingsStore_HouseholdSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HouseholdSettings'
type HomeSettingsStore_HouseholdSettings_Call struct {
	*mock.Call
}

// HouseholdSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HomeSettingsStore_Expecter) HouseholdSettings(ctx interface{}) *HomeSettingsStore_HouseholdSettings_Call {
	return &HomeSettingsStore_HouseholdSettings_Call{Call: _e.mock.On("HouseholdSettings", ctx)}
}

func (_c *HomeSettingsStore_HouseholdSettings_Call) Run(run func(ctx context.Context)) *HomeSettingsStore_HouseholdSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *HomeSettingsStore_HouseholdSettings_Call) Return(_a0 model.HouseholdSettings, _a1 error) *HomeSettingsStore_HouseholdSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HomeSettingsStore_HouseholdSettings_Call) RunAndReturn(run func(context.Context) (model.HouseholdSettings, error)) *HomeSettingsStore_HouseholdSettings_Call {
	_c.Call.Return(run)
	return _c
}

// Rooms provides a mock function with given fields: ctx
func (_m *HomeSettingsStore) Rooms(ctx context.Context) ([]model.RoomConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rooms")
	}

	var r0 []model.RoomConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.RoomConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.RoomConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RoomConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HomeSettingsStore_Rooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rooms'
type HomeSettingsStore_Rooms_Call struct {
	*mock.Call
}

// Rooms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HomeSettingsStore_Expecter) Rooms(ctx interface{}) *HomeSettingsStore_Rooms_Call {
	return &HomeSettingsStore_Rooms_Call{Call: _e.mock.On("Rooms", ctx)}
}

func (_c *HomeSettingsStore_Rooms_Call) Run(run func(ctx context.Context)) *HomeSettingsStore_Rooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *HomeSettingsStore_Rooms_Call) Return(_a0 []model.RoomConfig, _a1 error) *HomeSettingsStore_Rooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HomeSettingsStore_Rooms_Call) RunAndReturn(run func(context.Context) ([]model.RoomConfig, error)) *HomeSettingsStore_Rooms_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAdapterConnection provides a mock function with given fields: ctx, connection
func (_m *HomeSettingsStore) SaveAdapterConnection(ctx context.Context, connection model.AdapterConnection) (model.AdapterConnection, error) {
	ret := _m.Called(ctx, connection)

	if len(ret) == 0 {
		panic("no return value specified for SaveAdapterConnection")
	}

	var r0 model.AdapterConnection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.AdapterConnection) (model.AdapterConnection, error)); ok {
		return rf(ctx, connection)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.AdapterConnection) model.AdapterConnection); ok {
		r0 = rf(ctx, connection)
	} else {
		r0 = ret.Get(0).(model.AdapterConnection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.AdapterConnection) error); ok {
		r1 = rf(ctx, connection)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HomeSettingsStore_SaveAdapterConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAdapterConnection'
type HomeSettingsStore_SaveAdapterConnection_Call struct {
	*mock.Call
}

// SaveAdapterConnection is a helper method to define mock.On call
//   - ctx context.Context
//   - connection model.AdapterConnection
func (_e *HomeSettingsStore_Expecter) SaveAdapterConnection(ctx interface{}, connection interface{}) *HomeSettingsStore_SaveAdapterConnection_Call {
	return &HomeSettingsStore_SaveAdapterConnection_Call{Call: _e.mock.On("SaveAdapterConnection", ctx, connection)}
}

func (_c *HomeSettingsStore_SaveAdapterConnection_Call) Run(run func(ctx context.Context, connection model.AdapterConnection)) *HomeSettingsStore_SaveAdapterConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.AdapterConnection))
	})
	return _c
}

func (_c *HomeSettingsStore_SaveAdapterConnection_Call) Return(_a0 model.AdapterConnection, _a1 error) *HomeSettingsStore_SaveAdapterConnection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HomeSettingsStore_SaveAdapterConnection_Call) RunAndReturn(run func(context.Context, model.AdapterConnection) (model.AdapterConnection, error)) *HomeSettingsStore_SaveAdapterConnection_Call {
	_c.Call.Return(run)
	return _c
}

// SaveHouseholdSettings provides a mock function with given fields: ctx, settings
func (_m *HomeSettingsStore) SaveHouseholdSettings(ctx context.Context, settings model.HouseholdSettings) (model.HouseholdSettings, error) {
	ret := _m.Called(ctx, settings)

	if len(ret) == 0 {
		panic("no return value specified for SaveHouseholdSettings")
	}

	var r0 model.HouseholdSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.HouseholdSettings) (model.HouseholdSettings, error)); ok {
		return rf(ctx, settings)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.HouseholdSettings) model.HouseholdSettings); ok {
		r0 = rf(ctx, settings)
	} else {
		r0 = ret.Get(0).(model.HouseholdSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.HouseholdSettings) error); ok {
		r1 = rf(ctx, settings)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HomeSettingsStore_SaveHouseholdSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveHouseholdSettings'
type HomeSettingsStore_SaveHouseholdSettings_Call struct {
	*mock.Call
}

// SaveHouseholdSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - settings model.HouseholdSettings
func (_e *HomeSettingsStore_Expecter) SaveHouseholdSettings(ctx interface{}, settings interface{}) *HomeSettingsStore_SaveHouseholdSettings_Call {
	return &HomeSettingsStore_SaveHouseholdSettings_Call{Call: _e.mock.On("SaveHouseholdSettings", ctx, settings)}
}

func (_c *HomeSettingsStore_SaveHouseholdSettings_Call) Run(run func(ctx context.Context, settings model.HouseholdSettings)) *HomeSettingsStore_SaveHouseholdSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.HouseholdSettings))
	})
	return _c
}

func (_c *HomeSettingsStore_SaveHouseholdSettings_Call) Return(_a0 model.HouseholdSettings, _a1 error) *HomeSettingsStore_SaveHouseholdSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HomeSettingsStore_SaveHouseholdSettings_Call) RunAndReturn(run func(context.Context, model.HouseholdSettings) (model.HouseholdSettings, error)) *HomeSettingsStore_SaveHouseholdSettings_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRooms provides a mock function with given fields: ctx, rooms
func (_m *HomeSettingsStore) SaveRooms(ctx context.Context, rooms []model.RoomConfig) ([]model.RoomConfig, error) {
	ret := _m.Called(ctx, rooms)

	if len(ret) == 0 {
		panic("no return value specified for SaveRooms")
	}

	var r0 []model.RoomConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.RoomConfig) ([]model.RoomConfig, error)); ok {
		return rf(ctx, rooms)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []model.RoomConfig) []model.RoomConfig); ok {
		r0 = rf(ctx, rooms)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.RoomConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []model.RoomConfig) error); ok {
		r1 = rf(ctx, rooms)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HomeSettingsStore_SaveRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRooms'
type HomeSettingsStore_SaveRooms_Call struct {
	*mock.Call
}

// SaveRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - rooms []model.RoomConfig
func (_e *HomeSettingsStore_Expecter) SaveRooms(ctx interface{}, rooms interface{}) *HomeSettingsStore_SaveRooms_Call {
	return &HomeSettingsStore_SaveRooms_Call{Call: _e.mock.On("SaveRooms", ctx, rooms)}
}

func (_c *HomeSettingsStore_SaveRooms_Call) Run(run func(ctx context.Context, rooms []model.RoomConfig)) *HomeSettingsStore_SaveRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.RoomConfig))
	})
	return _c
}

func (_c *HomeSettingsStore_SaveRooms_Call) Return(_a0 []model.RoomConfig, _a1 error) *HomeSettingsStore_SaveRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HomeSettingsStore_SaveRooms_Call) RunAndReturn(run func(context.Context, []model.RoomConfig) ([]model.RoomConfig, error)) *HomeSettingsStore_SaveRooms_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTiles provides a mock function with given fields: ctx, tiles
func (_m *HomeSettingsStore) SaveTiles(ctx context.Context, tiles []model.TileConfig) ([]model.TileConfig, error) {
	ret := _m.Called(ctx, tiles)

	if len(ret) == 0 {
		panic("no return value specified for SaveTiles")
	}

	var r0 []model.TileConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.TileConfig) ([]model.TileConfig, error)); ok {
		return rf(ctx, tiles)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []model.TileConfig) []model.TileConfig); ok {
		r0 = rf(ctx, tiles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TileConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []model.TileConfig) error); ok {
		r1 = rf(ctx, tiles)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HomeSettingsStore_SaveTiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTiles'
type HomeSettingsStore_SaveTiles_Call struct {
	*mock.Call
}

// SaveTiles is a helper method to define mock.On call
//   - ctx context.Context
//   - tiles []model.TileConfig
func (_e *HomeSettingsStore_Expecter) SaveTiles(ctx interface{}, tiles interface{}) *HomeSettingsStore_SaveTiles_Call {
	return &HomeSettingsStore_SaveTiles_Call{Call: _e.mock.On("SaveTiles", ctx, tiles)}
}

func (_c *HomeSettingsStore_SaveTiles_Call) Run(run func(ctx context.Context, tiles []model.TileConfig)) *HomeSettingsStore_SaveTiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.TileConfig))
	})
	return _c
}

func (_c *HomeSettingsStore_SaveTiles_Call) Return(_a0 []model.TileConfig, _a1 error) *HomeSettingsStore_SaveTiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HomeSettingsStore_SaveTiles_Call) RunAndReturn(run func(context.Context, []model.TileConfig) ([]model.TileConfig, error)) *HomeSettingsStore_SaveTiles_Call {
	_c.Call.Return(run)
	return _c
}

// SetupStatus provides a mock function with given fields: ctx
func (_m *HomeSettingsStore) SetupStatus(ctx context.Context) (model.SetupStatus, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SetupStatus")
	}

	var r0 model.SetupStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (model.SetupStatus, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) model.SetupStatus); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(model.SetupStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HomeSettingsStore_SetupStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupStatus'
type HomeSettingsStore_SetupStatus_Call struct {
	*mock.Call
}

// SetupStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HomeSettingsStore_Expecter) SetupStatus(ctx interface{}) *HomeSettingsStore_SetupStatus_Call {
	return &HomeSettingsStore_SetupStatus_Call{Call: _e.mock.On("SetupStatus", ctx)}
}

func (_c *HomeSettingsStore_SetupStatus_Call) Run(run func(ctx context.Context)) *HomeSettingsStore_SetupStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *HomeSettingsStore_SetupStatus_Call) Return(_a0 model.SetupStatus, _a1 error) *HomeSettingsStore_SetupStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HomeSettingsStore_SetupStatus_Call) RunAndReturn(run func(context.Context) (model.SetupStatus, error)) *HomeSettingsStore_SetupStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Tiles provides a mock function with given fields: ctx
func (_m *HomeSettingsStore) Tiles(ctx context.Context) ([]model.TileConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Tiles")
	}

	var r0 []model.TileConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.TileConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.TileConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.TileConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HomeSettingsStore_Tiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tiles'
type HomeSettingsStore_Tiles_Call struct {
	*mock.Call
}

// Tiles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *HomeSettingsStore_Expecter) Tiles(ctx interface{}) *HomeSettingsStore_Tiles_Call {
	return &HomeSettingsStore_Tiles_Call{Call: _e.mock.On("Tiles", ctx)}
}

func (_c *HomeSettingsStore_Tiles_Call) Run(run func(ctx context.Context)) *HomeSettingsStore_Tiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *HomeSettingsStore_Tiles_Call) Return(_a0 []model.TileConfig, _a1 error) *HomeSettingsStore_Tiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *HomeSettingsStore_Tiles_Call) RunAndReturn(run func(context.Context) ([]model.TileConfig, error)) *HomeSettingsStore_Tiles_Call {
	_c.Call.Return(run)
	return _c
}

// NewHomeSettingsStore creates a new instance of HomeSettingsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHomeSettingsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *HomeSettingsStore {
	mock := &HomeSettingsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
