// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dashboard "jute-dash/apps/hub/internal/app/service/dashboard"

	mock "github.com/stretchr/testify/mock"
)

// LayoutStore is an autogenerated mock type for the LayoutStore type
type LayoutStore struct {
	mock.Mock
}

type LayoutStore_Expecter struct {
	mock *mock.Mock
}

func (_m *LayoutStore) EXPECT() *LayoutStore_Expecter {
	return &LayoutStore_Expecter{mock: &_m.Mock}
}

// ResetWidgetLayout provides a mock function with given fields: ctx, profileID
func (_m *LayoutStore) ResetWidgetLayout(ctx context.Context, profileID string) (dashboard.WidgetLayout, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for ResetWidgetLayout")
	}

	var r0 dashboard.WidgetLayout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (dashboard.WidgetLayout, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dashboard.WidgetLayout); ok {
		r0 = rf(ctx, profileID)
	} else {
		r0 = ret.Get(0).(dashboard.WidgetLayout)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LayoutStore_ResetWidgetLayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetWidgetLayout'
type LayoutStore_ResetWidgetLayout_Call struct {
	*mock.Call
}

// ResetWidgetLayout is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID string
func (_e *LayoutStore_Expecter) ResetWidgetLayout(ctx interface{}, profileID interface{}) *LayoutStore_ResetWidgetLayout_Call {
	return &LayoutStore_ResetWidgetLayout_Call{Call: _e.mock.On("ResetWidgetLayout", ctx, profileID)}
}

func (_c *LayoutStore_ResetWidgetLayout_Call) Run(run func(ctx context.Context, profileID string)) *LayoutStore_ResetWidgetLayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *LayoutStore_ResetWidgetLayout_Call) Return(_a0 dashboard.WidgetLayout, _a1 error) *LayoutStore_ResetWidgetLayout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LayoutStore_ResetWidgetLayout_Call) RunAndReturn(run func(context.Context, string) (dashboard.WidgetLayout, error)) *LayoutStore_ResetWidgetLayout_Call {
	_c.Call.Return(run)
	return _c
}

// SaveWidgetLayout provides a mock function with given fields: ctx, layout
func (_m *LayoutStore) SaveWidgetLayout(ctx context.Context, layout dashboard.WidgetLayout) (dashboard.WidgetLayout, error) {
	ret := _m.Called(ctx, layout)

	if len(ret) == 0 {
		panic("no return value specified for SaveWidgetLayout")
	}

	var r0 dashboard.WidgetLayout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, dashboard.WidgetLayout) (dashboard.WidgetLayout, error)); ok {
		return rf(ctx, layout)
	}
	if rf, ok := ret.Get(0).(func(context.Context, dashboard.WidgetLayout) dashboard.WidgetLayout); ok {
		r0 = rf(ctx, layout)
	} else {
		r0 = ret.Get(0).(dashboard.WidgetLayout)
	}

	if rf, ok := ret.Get(1).(func(context.Context, dashboard.WidgetLayout) error); ok {
		r1 = rf(ctx, layout)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LayoutStore_SaveWidgetLayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveWidgetLayout'
type LayoutStore_SaveWidgetLayout_Call struct {
	*mock.Call
}

// SaveWidgetLayout is a helper method to define mock.On call
//   - ctx context.Context
//   - layout dashboard.WidgetLayout
func (_e *LayoutStore_Expecter) SaveWidgetLayout(ctx interface{}, layout interface{}) *LayoutStore_SaveWidgetLayout_Call {
	return &LayoutStore_SaveWidgetLayout_Call{Call: _e.mock.On("SaveWidgetLayout", ctx, layout)}
}

func (_c *LayoutStore_SaveWidgetLayout_Call) Run(run func(ctx context.Context, layout dashboard.WidgetLayout)) *LayoutStore_SaveWidgetLayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dashboard.WidgetLayout))
	})
	return _c
}

func (_c *LayoutStore_SaveWidgetLayout_Call) Return(_a0 dashboard.WidgetLayout, _a1 error) *LayoutStore_SaveWidgetLayout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LayoutStore_SaveWidgetLayout_Call) RunAndReturn(run func(context.Context, dashboard.WidgetLayout) (dashboard.WidgetLayout, error)) *LayoutStore_SaveWidgetLayout_Call {
	_c.Call.Return(run)
	return _c
}

// SetActiveScreen provides a mock function with given fields: ctx, profileID, screenID
func (_m *LayoutStore) SetActiveScreen(ctx context.Context, profileID string, screenID string) (dashboard.WidgetLayout, error) {
	ret := _m.Called(ctx, profileID, screenID)

	if len(ret) == 0 {
		panic("no return value specified for SetActiveScreen")
	}

	var r0 dashboard.WidgetLayout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (dashboard.WidgetLayout, error)); ok {
		return rf(ctx, profileID, screenID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) dashboard.WidgetLayout); ok {
		r0 = rf(ctx, profileID, screenID)
	} else {
		r0 = ret.Get(0).(dashboard.WidgetLayout)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, profileID, screenID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LayoutStore_SetActiveScreen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetActiveScreen'
type LayoutStore_SetActiveScreen_Call struct {
	*mock.Call
}

// SetActiveScreen is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID string
//   - screenID string
func (_e *LayoutStore_Expecter) SetActiveScreen(ctx interface{}, profileID interface{}, screenID interface{}) *LayoutStore_SetActiveScreen_Call {
	return &LayoutStore_SetActiveScreen_Call{Call: _e.mock.On("SetActiveScreen", ctx, profileID, screenID)}
}

func (_c *LayoutStore_SetActiveScreen_Call) Run(run func(ctx context.Context, profileID string, screenID string)) *LayoutStore_SetActiveScreen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *LayoutStore_SetActiveScreen_Call) Return(_a0 dashboard.WidgetLayout, _a1 error) *LayoutStore_SetActiveScreen_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LayoutStore_SetActiveScreen_Call) RunAndReturn(run func(context.Context, string, string) (dashboard.WidgetLayout, error)) *LayoutStore_SetActiveScreen_Call {
	_c.Call.Return(run)
	return _c
}

// WidgetLayout provides a mock function with given fields: ctx, profileID
func (_m *LayoutStore) WidgetLayout(ctx context.Context, profileID string) (dashboard.WidgetLayout, error) {
	ret := _m.Called(ctx, profileID)

	if len(ret) == 0 {
		panic("no return value specified for WidgetLayout")
	}

	var r0 dashboard.WidgetLayout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (dashboard.WidgetLayout, error)); ok {
		return rf(ctx, profileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) dashboard.WidgetLayout); ok {
		r0 = rf(ctx, profileID)
	} else {
		r0 = ret.Get(0).(dashboard.WidgetLayout)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, profileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LayoutStore_WidgetLayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WidgetLayout'
type LayoutStore_WidgetLayout_Call struct {
	*mock.Call
}

// WidgetLayout is a helper method to define mock.On call
//   - ctx context.Context
//   - profileID string
func (_e *LayoutStore_Expecter) WidgetLayout(ctx interface{}, profileID interface{}) *LayoutStore_WidgetLayout_Call {
	return &LayoutStore_WidgetLayout_Call{Call: _e.mock.On("WidgetLayout", ctx, profileID)}
}

func (_c *LayoutStore_WidgetLayout_Call) Run(run func(ctx context.Context, profileID string)) *LayoutStore_WidgetLayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *LayoutStore_WidgetLayout_Call) Return(_a0 dashboard.WidgetLayout, _a1 error) *LayoutStore_WidgetLayout_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LayoutStore_WidgetLayout_Call) RunAndReturn(run func(context.Context, string) (dashboard.WidgetLayout, error)) *LayoutStore_WidgetLayout_Call {
	_c.Call.Return(run)
	return _c
}

// NewLayoutStore creates a new instance of LayoutStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLayoutStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *LayoutStore {
	mock := &LayoutStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
