// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mcp "jute-dash/apps/hub/internal/pkg/mcp"

	mock "github.com/stretchr/testify/mock"

	widgetskills "jute-dash/apps/hub/pkg/widgetskills"
)

// ResourceRoute is an autogenerated mock type for the ResourceRoute type
type ResourceRoute struct {
	mock.Mock
}

type ResourceRoute_Expecter struct {
	mock *mock.Mock
}

func (_m *ResourceRoute) EXPECT() *ResourceRoute_Expecter {
	return &ResourceRoute_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: snapshot
func (_m *ResourceRoute) List(snapshot widgetskills.Snapshot) []map[string]interface{} {
	ret := _m.Called(snapshot)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []map[string]interface{}
	if rf, ok := ret.Get(0).(func(widgetskills.Snapshot) []map[string]interface{}); ok {
		r0 = rf(snapshot)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	return r0
}

// ResourceRoute_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type ResourceRoute_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - snapshot widgetskills.Snapshot
func (_e *ResourceRoute_Expecter) List(snapshot interface{}) *ResourceRoute_List_Call {
	return &ResourceRoute_List_Call{Call: _e.mock.On("List", snapshot)}
}

func (_c *ResourceRoute_List_Call) Run(run func(snapshot widgetskills.Snapshot)) *ResourceRoute_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(widgetskills.Snapshot))
	})
	return _c
}

func (_c *ResourceRoute_List_Call) Return(_a0 []map[string]interface{}) *ResourceRoute_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResourceRoute_List_Call) RunAndReturn(run func(widgetskills.Snapshot) []map[string]interface{}) *ResourceRoute_List_Call {
	_c.Call.Return(run)
	return _c
}

// Match provides a mock function with given fields: uri
func (_m *ResourceRoute) Match(uri string) bool {
	ret := _m.Called(uri)

	if len(ret) == 0 {
		panic("no return value specified for Match")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(uri)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// ResourceRoute_Match_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Match'
type ResourceRoute_Match_Call struct {
	*mock.Call
}

// Match is a helper method to define mock.On call
//   - uri string
func (_e *ResourceRoute_Expecter) Match(uri interface{}) *ResourceRoute_Match_Call {
	return &ResourceRoute_Match_Call{Call: _e.mock.On("Match", uri)}
}

func (_c *ResourceRoute_Match_Call) Run(run func(uri string)) *ResourceRoute_Match_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *ResourceRoute_Match_Call) Return(_a0 bool) *ResourceRoute_Match_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResourceRoute_Match_Call) RunAndReturn(run func(string) bool) *ResourceRoute_Match_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: ctx, uri
func (_m *ResourceRoute) Read(ctx mcp.RouteContext, uri string) (interface{}, error) {
	ret := _m.Called(ctx, uri)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(mcp.RouteContext, string) (interface{}, error)); ok {
		return rf(ctx, uri)
	}
	if rf, ok := ret.Get(0).(func(mcp.RouteContext, string) interface{}); ok {
		r0 = rf(ctx, uri)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(mcp.RouteContext, string) error); ok {
		r1 = rf(ctx, uri)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ResourceRoute_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type ResourceRoute_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx mcp.RouteContext
//   - uri string
func (_e *ResourceRoute_Expecter) Read(ctx interface{}, uri interface{}) *ResourceRoute_Read_Call {
	return &ResourceRoute_Read_Call{Call: _e.mock.On("Read", ctx, uri)}
}

func (_c *ResourceRoute_Read_Call) Run(run func(ctx mcp.RouteContext, uri string)) *ResourceRoute_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(mcp.RouteContext), args[1].(string))
	})
	return _c
}

func (_c *ResourceRoute_Read_Call) Return(_a0 interface{}, _a1 error) *ResourceRoute_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ResourceRoute_Read_Call) RunAndReturn(run func(mcp.RouteContext, string) (interface{}, error)) *ResourceRoute_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Scope provides a mock function with no fields
func (_m *ResourceRoute) Scope() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Scope")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ResourceRoute_Scope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scope'
type ResourceRoute_Scope_Call struct {
	*mock.Call
}

// Scope is a helper method to define mock.On call
func (_e *ResourceRoute_Expecter) Scope() *ResourceRoute_Scope_Call {
	return &ResourceRoute_Scope_Call{Call: _e.mock.On("Scope")}
}

func (_c *ResourceRoute_Scope_Call) Run(run func()) *ResourceRoute_Scope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ResourceRoute_Scope_Call) Return(_a0 string) *ResourceRoute_Scope_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ResourceRoute_Scope_Call) RunAndReturn(run func() string) *ResourceRoute_Scope_Call {
	_c.Call.Return(run)
	return _c
}

// NewResourceRoute creates a new instance of ResourceRoute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResourceRoute(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResourceRoute {
	mock := &ResourceRoute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
