// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// secretResolver is an autogenerated mock type for the secretResolver type
type secretResolver struct {
	mock.Mock
}

type secretResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *secretResolver) EXPECT() *secretResolver_Expecter {
	return &secretResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function with given fields: ctx, id
func (_m *secretResolver) Resolve(ctx context.Context, id string) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// secretResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type secretResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *secretResolver_Expecter) Resolve(ctx interface{}, id interface{}) *secretResolver_Resolve_Call {
	return &secretResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx, id)}
}

func (_c *secretResolver_Resolve_Call) Run(run func(ctx context.Context, id string)) *secretResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *secretResolver_Resolve_Call) Return(_a0 string, _a1 error) *secretResolver_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *secretResolver_Resolve_Call) RunAndReturn(run func(context.Context, string) (string, error)) *secretResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// newSecretResolver creates a new instance of secretResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newSecretResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *secretResolver {
	mock := &secretResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
