// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"

	v1 "jute-dash/apps/hub/api/hub/v1"
)

// ServerInterface is an autogenerated mock type for the ServerInterface type
type ServerInterface struct {
	mock.Mock
}

type ServerInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *ServerInterface) EXPECT() *ServerInterface_Expecter {
	return &ServerInterface_Expecter{mock: &_m.Mock}
}

// GetAgents provides a mock function with given fields: ctx
func (_m *ServerInterface) GetAgents(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAgents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAgents'
type ServerInterface_GetAgents_Call struct {
	*mock.Call
}

// GetAgents is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetAgents(ctx interface{}) *ServerInterface_GetAgents_Call {
	return &ServerInterface_GetAgents_Call{Call: _e.mock.On("GetAgents", ctx)}
}

func (_c *ServerInterface_GetAgents_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetAgents_Call) Return(_a0 error) *ServerInterface_GetAgents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetAgents_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetAgents_Call {
	_c.Call.Return(run)
	return _c
}

// GetBackgrounds provides a mock function with given fields: ctx
func (_m *ServerInterface) GetBackgrounds(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetBackgrounds")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetBackgrounds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBackgrounds'
type ServerInterface_GetBackgrounds_Call struct {
	*mock.Call
}

// GetBackgrounds is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetBackgrounds(ctx interface{}) *ServerInterface_GetBackgrounds_Call {
	return &ServerInterface_GetBackgrounds_Call{Call: _e.mock.On("GetBackgrounds", ctx)}
}

func (_c *ServerInterface_GetBackgrounds_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetBackgrounds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetBackgrounds_Call) Return(_a0 error) *ServerInterface_GetBackgrounds_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetBackgrounds_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetBackgrounds_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function with given fields: ctx
func (_m *ServerInterface) GetConfig(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type ServerInterface_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetConfig(ctx interface{}) *ServerInterface_GetConfig_Call {
	return &ServerInterface_GetConfig_Call{Call: _e.mock.On("GetConfig", ctx)}
}

func (_c *ServerInterface_GetConfig_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetConfig_Call) Return(_a0 error) *ServerInterface_GetConfig_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetConfig_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnectionKinds provides a mock function with given fields: ctx
func (_m *ServerInterface) GetConnectionKinds(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConnectionKinds")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetConnectionKinds_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnectionKinds'
type ServerInterface_GetConnectionKinds_Call struct {
	*mock.Call
}

// GetConnectionKinds is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetConnectionKinds(ctx interface{}) *ServerInterface_GetConnectionKinds_Call {
	return &ServerInterface_GetConnectionKinds_Call{Call: _e.mock.On("GetConnectionKinds", ctx)}
}

func (_c *ServerInterface_GetConnectionKinds_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetConnectionKinds_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetConnectionKinds_Call) Return(_a0 error) *ServerInterface_GetConnectionKinds_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetConnectionKinds_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetConnectionKinds_Call {
	_c.Call.Return(run)
	return _c
}

// GetConnections provides a mock function with given fields: ctx
func (_m *ServerInterface) GetConnections(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetConnections")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConnections'
type ServerInterface_GetConnections_Call struct {
	*mock.Call
}

// GetConnections is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetConnections(ctx interface{}) *ServerInterface_GetConnections_Call {
	return &ServerInterface_GetConnections_Call{Call: _e.mock.On("GetConnections", ctx)}
}

func (_c *ServerInterface_GetConnections_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetConnections_Call) Return(_a0 error) *ServerInterface_GetConnections_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetConnections_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetConnections_Call {
	_c.Call.Return(run)
	return _c
}

// GetEvents provides a mock function with given fields: ctx
func (_m *ServerInterface) GetEvents(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetEvents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEvents'
type ServerInterface_GetEvents_Call struct {
	*mock.Call
}

// GetEvents is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetEvents(ctx interface{}) *ServerInterface_GetEvents_Call {
	return &ServerInterface_GetEvents_Call{Call: _e.mock.On("GetEvents", ctx)}
}

func (_c *ServerInterface_GetEvents_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetEvents_Call) Return(_a0 error) *ServerInterface_GetEvents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetEvents_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetEvents_Call {
	_c.Call.Return(run)
	return _c
}

// GetHealth provides a mock function with given fields: ctx
func (_m *ServerInterface) GetHealth(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetHealth")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetHealth_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHealth'
type ServerInterface_GetHealth_Call struct {
	*mock.Call
}

// GetHealth is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetHealth(ctx interface{}) *ServerInterface_GetHealth_Call {
	return &ServerInterface_GetHealth_Call{Call: _e.mock.On("GetHealth", ctx)}
}

func (_c *ServerInterface_GetHealth_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetHealth_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetHealth_Call) Return(_a0 error) *ServerInterface_GetHealth_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetHealth_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetHealth_Call {
	_c.Call.Return(run)
	return _c
}

// GetHome provides a mock function with given fields: ctx
func (_m *ServerInterface) GetHome(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetHome")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetHome_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHome'
type ServerInterface_GetHome_Call struct {
	*mock.Call
}

// GetHome is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetHome(ctx interface{}) *ServerInterface_GetHome_Call {
	return &ServerInterface_GetHome_Call{Call: _e.mock.On("GetHome", ctx)}
}

func (_c *ServerInterface_GetHome_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetHome_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetHome_Call) Return(_a0 error) *ServerInterface_GetHome_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetHome_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetHome_Call {
	_c.Call.Return(run)
	return _c
}

// GetHouseholdSettings provides a mock function with given fields: ctx
func (_m *ServerInterface) GetHouseholdSettings(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetHouseholdSettings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetHouseholdSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetHouseholdSettings'
type ServerInterface_GetHouseholdSettings_Call struct {
	*mock.Call
}

// GetHouseholdSettings is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetHouseholdSettings(ctx interface{}) *ServerInterface_GetHouseholdSettings_Call {
	return &ServerInterface_GetHouseholdSettings_Call{Call: _e.mock.On("GetHouseholdSettings", ctx)}
}

func (_c *ServerInterface_GetHouseholdSettings_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetHouseholdSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetHouseholdSettings_Call) Return(_a0 error) *ServerInterface_GetHouseholdSettings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetHouseholdSettings_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetHouseholdSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetRooms provides a mock function with given fields: ctx
func (_m *ServerInterface) GetRooms(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRooms")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRooms'
type ServerInterface_GetRooms_Call struct {
	*mock.Call
}

// GetRooms is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetRooms(ctx interface{}) *ServerInterface_GetRooms_Call {
	return &ServerInterface_GetRooms_Call{Call: _e.mock.On("GetRooms", ctx)}
}

func (_c *ServerInterface_GetRooms_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetRooms_Call) Return(_a0 error) *ServerInterface_GetRooms_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetRooms_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetRooms_Call {
	_c.Call.Return(run)
	return _c
}

// GetSetupStatus provides a mock function with given fields: ctx
func (_m *ServerInterface) GetSetupStatus(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSetupStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetSetupStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSetupStatus'
type ServerInterface_GetSetupStatus_Call struct {
	*mock.Call
}

// GetSetupStatus is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetSetupStatus(ctx interface{}) *ServerInterface_GetSetupStatus_Call {
	return &ServerInterface_GetSetupStatus_Call{Call: _e.mock.On("GetSetupStatus", ctx)}
}

func (_c *ServerInterface_GetSetupStatus_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetSetupStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetSetupStatus_Call) Return(_a0 error) *ServerInterface_GetSetupStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetSetupStatus_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetSetupStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function with given fields: ctx
func (_m *ServerInterface) GetStatus(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type ServerInterface_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetStatus(ctx interface{}) *ServerInterface_GetStatus_Call {
	return &ServerInterface_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx)}
}

func (_c *ServerInterface_GetStatus_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetStatus_Call) Return(_a0 error) *ServerInterface_GetStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetStatus_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetTTSVoices provides a mock function with given fields: ctx, params
func (_m *ServerInterface) GetTTSVoices(ctx echo.Context, params v1.GetTTSVoicesParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetTTSVoices")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, v1.GetTTSVoicesParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetTTSVoices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTTSVoices'
type ServerInterface_GetTTSVoices_Call struct {
	*mock.Call
}

// GetTTSVoices is a helper method to define mock.On call
//   - ctx echo.Context
//   - params v1.GetTTSVoicesParams
func (_e *ServerInterface_Expecter) GetTTSVoices(ctx interface{}, params interface{}) *ServerInterface_GetTTSVoices_Call {
	return &ServerInterface_GetTTSVoices_Call{Call: _e.mock.On("GetTTSVoices", ctx, params)}
}

func (_c *ServerInterface_GetTTSVoices_Call) Run(run func(ctx echo.Context, params v1.GetTTSVoicesParams)) *ServerInterface_GetTTSVoices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context), args[1].(v1.GetTTSVoicesParams))
	})
	return _c
}

func (_c *ServerInterface_GetTTSVoices_Call) Return(_a0 error) *ServerInterface_GetTTSVoices_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetTTSVoices_Call) RunAndReturn(run func(echo.Context, v1.GetTTSVoicesParams) error) *ServerInterface_GetTTSVoices_Call {
	_c.Call.Return(run)
	return _c
}

// GetTiles provides a mock function with given fields: ctx
func (_m *ServerInterface) GetTiles(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetTiles")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetTiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTiles'
type ServerInterface_GetTiles_Call struct {
	*mock.Call
}

// GetTiles is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetTiles(ctx interface{}) *ServerInterface_GetTiles_Call {
	return &ServerInterface_GetTiles_Call{Call: _e.mock.On("GetTiles", ctx)}
}

func (_c *ServerInterface_GetTiles_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetTiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetTiles_Call) Return(_a0 error) *ServerInterface_GetTiles_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetTiles_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetTiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetVoiceProviders provides a mock function with given fields: ctx
func (_m *ServerInterface) GetVoiceProviders(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetVoiceProviders")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetVoiceProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVoiceProviders'
type ServerInterface_GetVoiceProviders_Call struct {
	*mock.Call
}

// GetVoiceProviders is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetVoiceProviders(ctx interface{}) *ServerInterface_GetVoiceProviders_Call {
	return &ServerInterface_GetVoiceProviders_Call{Call: _e.mock.On("GetVoiceProviders", ctx)}
}

func (_c *ServerInterface_GetVoiceProviders_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetVoiceProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetVoiceProviders_Call) Return(_a0 error) *ServerInterface_GetVoiceProviders_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetVoiceProviders_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetVoiceProviders_Call {
	_c.Call.Return(run)
	return _c
}

// GetVoiceStatus provides a mock function with given fields: ctx
func (_m *ServerInterface) GetVoiceStatus(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetVoiceStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetVoiceStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVoiceStatus'
type ServerInterface_GetVoiceStatus_Call struct {
	*mock.Call
}

// GetVoiceStatus is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetVoiceStatus(ctx interface{}) *ServerInterface_GetVoiceStatus_Call {
	return &ServerInterface_GetVoiceStatus_Call{Call: _e.mock.On("GetVoiceStatus", ctx)}
}

func (_c *ServerInterface_GetVoiceStatus_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetVoiceStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetVoiceStatus_Call) Return(_a0 error) *ServerInterface_GetVoiceStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetVoiceStatus_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetVoiceStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetWidgetCatalog provides a mock function with given fields: ctx
func (_m *ServerInterface) GetWidgetCatalog(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetWidgetCatalog")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetWidgetCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWidgetCatalog'
type ServerInterface_GetWidgetCatalog_Call struct {
	*mock.Call
}

// GetWidgetCatalog is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) GetWidgetCatalog(ctx interface{}) *ServerInterface_GetWidgetCatalog_Call {
	return &ServerInterface_GetWidgetCatalog_Call{Call: _e.mock.On("GetWidgetCatalog", ctx)}
}

func (_c *ServerInterface_GetWidgetCatalog_Call) Run(run func(ctx echo.Context)) *ServerInterface_GetWidgetCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_GetWidgetCatalog_Call) Return(_a0 error) *ServerInterface_GetWidgetCatalog_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetWidgetCatalog_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_GetWidgetCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// GetWidgetLayout provides a mock function with given fields: ctx, params
func (_m *ServerInterface) GetWidgetLayout(ctx echo.Context, params v1.GetWidgetLayoutParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for GetWidgetLayout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, v1.GetWidgetLayoutParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_GetWidgetLayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWidgetLayout'
type ServerInterface_GetWidgetLayout_Call struct {
	*mock.Call
}

// GetWidgetLayout is a helper method to define mock.On call
//   - ctx echo.Context
//   - params v1.GetWidgetLayoutParams
func (_e *ServerInterface_Expecter) GetWidgetLayout(ctx interface{}, params interface{}) *ServerInterface_GetWidgetLayout_Call {
	return &ServerInterface_GetWidgetLayout_Call{Call: _e.mock.On("GetWidgetLayout", ctx, params)}
}

func (_c *ServerInterface_GetWidgetLayout_Call) Run(run func(ctx echo.Context, params v1.GetWidgetLayoutParams)) *ServerInterface_GetWidgetLayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context), args[1].(v1.GetWidgetLayoutParams))
	})
	return _c
}

func (_c *ServerInterface_GetWidgetLayout_Call) Return(_a0 error) *ServerInterface_GetWidgetLayout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_GetWidgetLayout_Call) RunAndReturn(run func(echo.Context, v1.GetWidgetLayoutParams) error) *ServerInterface_GetWidgetLayout_Call {
	_c.Call.Return(run)
	return _c
}

// PatchHouseholdSettings provides a mock function with given fields: ctx
func (_m *ServerInterface) PatchHouseholdSettings(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PatchHouseholdSettings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_PatchHouseholdSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchHouseholdSettings'
type ServerInterface_PatchHouseholdSettings_Call struct {
	*mock.Call
}

// PatchHouseholdSettings is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) PatchHouseholdSettings(ctx interface{}) *ServerInterface_PatchHouseholdSettings_Call {
	return &ServerInterface_PatchHouseholdSettings_Call{Call: _e.mock.On("PatchHouseholdSettings", ctx)}
}

func (_c *ServerInterface_PatchHouseholdSettings_Call) Run(run func(ctx echo.Context)) *ServerInterface_PatchHouseholdSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_PatchHouseholdSettings_Call) Return(_a0 error) *ServerInterface_PatchHouseholdSettings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_PatchHouseholdSettings_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_PatchHouseholdSettings_Call {
	_c.Call.Return(run)
	return _c
}

// PatchVoiceSettings provides a mock function with given fields: ctx
func (_m *ServerInterface) PatchVoiceSettings(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PatchVoiceSettings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_PatchVoiceSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchVoiceSettings'
type ServerInterface_PatchVoiceSettings_Call struct {
	*mock.Call
}

// PatchVoiceSettings is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) PatchVoiceSettings(ctx interface{}) *ServerInterface_PatchVoiceSettings_Call {
	return &ServerInterface_PatchVoiceSettings_Call{Call: _e.mock.On("PatchVoiceSettings", ctx)}
}

func (_c *ServerInterface_PatchVoiceSettings_Call) Run(run func(ctx echo.Context)) *ServerInterface_PatchVoiceSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_PatchVoiceSettings_Call) Return(_a0 error) *ServerInterface_PatchVoiceSettings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_PatchVoiceSettings_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_PatchVoiceSettings_Call {
	_c.Call.Return(run)
	return _c
}

// PatchWidgetLayoutActiveScreen provides a mock function with given fields: ctx
func (_m *ServerInterface) PatchWidgetLayoutActiveScreen(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PatchWidgetLayoutActiveScreen")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_PatchWidgetLayoutActiveScreen_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PatchWidgetLayoutActiveScreen'
type ServerInterface_PatchWidgetLayoutActiveScreen_Call struct {
	*mock.Call
}

// PatchWidgetLayoutActiveScreen is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) PatchWidgetLayoutActiveScreen(ctx interface{}) *ServerInterface_PatchWidgetLayoutActiveScreen_Call {
	return &ServerInterface_PatchWidgetLayoutActiveScreen_Call{Call: _e.mock.On("PatchWidgetLayoutActiveScreen", ctx)}
}

func (_c *ServerInterface_PatchWidgetLayoutActiveScreen_Call) Run(run func(ctx echo.Context)) *ServerInterface_PatchWidgetLayoutActiveScreen_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_PatchWidgetLayoutActiveScreen_Call) Return(_a0 error) *ServerInterface_PatchWidgetLayoutActiveScreen_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_PatchWidgetLayoutActiveScreen_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_PatchWidgetLayoutActiveScreen_Call {
	_c.Call.Return(run)
	return _c
}

// PostAgentConversation provides a mock function with given fields: ctx
func (_m *ServerInterface) PostAgentConversation(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PostAgentConversation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_PostAgentConversation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostAgentConversation'
type ServerInterface_PostAgentConversation_Call struct {
	*mock.Call
}

// PostAgentConversation is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) PostAgentConversation(ctx interface{}) *ServerInterface_PostAgentConversation_Call {
	return &ServerInterface_PostAgentConversation_Call{Call: _e.mock.On("PostAgentConversation", ctx)}
}

func (_c *ServerInterface_PostAgentConversation_Call) Run(run func(ctx echo.Context)) *ServerInterface_PostAgentConversation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_PostAgentConversation_Call) Return(_a0 error) *ServerInterface_PostAgentConversation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_PostAgentConversation_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_PostAgentConversation_Call {
	_c.Call.Return(run)
	return _c
}

// PostBackground provides a mock function with given fields: ctx
func (_m *ServerInterface) PostBackground(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PostBackground")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_PostBackground_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostBackground'
type ServerInterface_PostBackground_Call struct {
	*mock.Call
}

// PostBackground is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) PostBackground(ctx interface{}) *ServerInterface_PostBackground_Call {
	return &ServerInterface_PostBackground_Call{Call: _e.mock.On("PostBackground", ctx)}
}

func (_c *ServerInterface_PostBackground_Call) Run(run func(ctx echo.Context)) *ServerInterface_PostBackground_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_PostBackground_Call) Return(_a0 error) *ServerInterface_PostBackground_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_PostBackground_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_PostBackground_Call {
	_c.Call.Return(run)
	return _c
}

// PostConnection provides a mock function with given fields: ctx
func (_m *ServerInterface) PostConnection(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PostConnection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_PostConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostConnection'
type ServerInterface_PostConnection_Call struct {
	*mock.Call
}

// PostConnection is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) PostConnection(ctx interface{}) *ServerInterface_PostConnection_Call {
	return &ServerInterface_PostConnection_Call{Call: _e.mock.On("PostConnection", ctx)}
}

func (_c *ServerInterface_PostConnection_Call) Run(run func(ctx echo.Context)) *ServerInterface_PostConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_PostConnection_Call) Return(_a0 error) *ServerInterface_PostConnection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_PostConnection_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_PostConnection_Call {
	_c.Call.Return(run)
	return _c
}

// PostTTSSpeak provides a mock function with given fields: ctx
func (_m *ServerInterface) PostTTSSpeak(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PostTTSSpeak")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_PostTTSSpeak_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostTTSSpeak'
type ServerInterface_PostTTSSpeak_Call struct {
	*mock.Call
}

// PostTTSSpeak is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) PostTTSSpeak(ctx interface{}) *ServerInterface_PostTTSSpeak_Call {
	return &ServerInterface_PostTTSSpeak_Call{Call: _e.mock.On("PostTTSSpeak", ctx)}
}

func (_c *ServerInterface_PostTTSSpeak_Call) Run(run func(ctx echo.Context)) *ServerInterface_PostTTSSpeak_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_PostTTSSpeak_Call) Return(_a0 error) *ServerInterface_PostTTSSpeak_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_PostTTSSpeak_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_PostTTSSpeak_Call {
	_c.Call.Return(run)
	return _c
}

// PostTTSStop provides a mock function with given fields: ctx
func (_m *ServerInterface) PostTTSStop(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PostTTSStop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_PostTTSStop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostTTSStop'
type ServerInterface_PostTTSStop_Call struct {
	*mock.Call
}

// PostTTSStop is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) PostTTSStop(ctx interface{}) *ServerInterface_PostTTSStop_Call {
	return &ServerInterface_PostTTSStop_Call{Call: _e.mock.On("PostTTSStop", ctx)}
}

func (_c *ServerInterface_PostTTSStop_Call) Run(run func(ctx echo.Context)) *ServerInterface_PostTTSStop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_PostTTSStop_Call) Return(_a0 error) *ServerInterface_PostTTSStop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_PostTTSStop_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_PostTTSStop_Call {
	_c.Call.Return(run)
	return _c
}

// PostVoiceCancel provides a mock function with given fields: ctx
func (_m *ServerInterface) PostVoiceCancel(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PostVoiceCancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_PostVoiceCancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostVoiceCancel'
type ServerInterface_PostVoiceCancel_Call struct {
	*mock.Call
}

// PostVoiceCancel is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) PostVoiceCancel(ctx interface{}) *ServerInterface_PostVoiceCancel_Call {
	return &ServerInterface_PostVoiceCancel_Call{Call: _e.mock.On("PostVoiceCancel", ctx)}
}

func (_c *ServerInterface_PostVoiceCancel_Call) Run(run func(ctx echo.Context)) *ServerInterface_PostVoiceCancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_PostVoiceCancel_Call) Return(_a0 error) *ServerInterface_PostVoiceCancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_PostVoiceCancel_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_PostVoiceCancel_Call {
	_c.Call.Return(run)
	return _c
}

// PostVoiceFinalTranscript provides a mock function with given fields: ctx
func (_m *ServerInterface) PostVoiceFinalTranscript(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PostVoiceFinalTranscript")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_PostVoiceFinalTranscript_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostVoiceFinalTranscript'
type ServerInterface_PostVoiceFinalTranscript_Call struct {
	*mock.Call
}

// PostVoiceFinalTranscript is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) PostVoiceFinalTranscript(ctx interface{}) *ServerInterface_PostVoiceFinalTranscript_Call {
	return &ServerInterface_PostVoiceFinalTranscript_Call{Call: _e.mock.On("PostVoiceFinalTranscript", ctx)}
}

func (_c *ServerInterface_PostVoiceFinalTranscript_Call) Run(run func(ctx echo.Context)) *ServerInterface_PostVoiceFinalTranscript_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_PostVoiceFinalTranscript_Call) Return(_a0 error) *ServerInterface_PostVoiceFinalTranscript_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_PostVoiceFinalTranscript_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_PostVoiceFinalTranscript_Call {
	_c.Call.Return(run)
	return _c
}

// PostVoiceMute provides a mock function with given fields: ctx
func (_m *ServerInterface) PostVoiceMute(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PostVoiceMute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_PostVoiceMute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostVoiceMute'
type ServerInterface_PostVoiceMute_Call struct {
	*mock.Call
}

// PostVoiceMute is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) PostVoiceMute(ctx interface{}) *ServerInterface_PostVoiceMute_Call {
	return &ServerInterface_PostVoiceMute_Call{Call: _e.mock.On("PostVoiceMute", ctx)}
}

func (_c *ServerInterface_PostVoiceMute_Call) Run(run func(ctx echo.Context)) *ServerInterface_PostVoiceMute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_PostVoiceMute_Call) Return(_a0 error) *ServerInterface_PostVoiceMute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_PostVoiceMute_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_PostVoiceMute_Call {
	_c.Call.Return(run)
	return _c
}

// PostVoiceUnmute provides a mock function with given fields: ctx
func (_m *ServerInterface) PostVoiceUnmute(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PostVoiceUnmute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_PostVoiceUnmute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostVoiceUnmute'
type ServerInterface_PostVoiceUnmute_Call struct {
	*mock.Call
}

// PostVoiceUnmute is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) PostVoiceUnmute(ctx interface{}) *ServerInterface_PostVoiceUnmute_Call {
	return &ServerInterface_PostVoiceUnmute_Call{Call: _e.mock.On("PostVoiceUnmute", ctx)}
}

func (_c *ServerInterface_PostVoiceUnmute_Call) Run(run func(ctx echo.Context)) *ServerInterface_PostVoiceUnmute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_PostVoiceUnmute_Call) Return(_a0 error) *ServerInterface_PostVoiceUnmute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_PostVoiceUnmute_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_PostVoiceUnmute_Call {
	_c.Call.Return(run)
	return _c
}

// PostWidgetLayoutReset provides a mock function with given fields: ctx, params
func (_m *ServerInterface) PostWidgetLayoutReset(ctx echo.Context, params v1.PostWidgetLayoutResetParams) error {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for PostWidgetLayoutReset")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context, v1.PostWidgetLayoutResetParams) error); ok {
		r0 = rf(ctx, params)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_PostWidgetLayoutReset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostWidgetLayoutReset'
type ServerInterface_PostWidgetLayoutReset_Call struct {
	*mock.Call
}

// PostWidgetLayoutReset is a helper method to define mock.On call
//   - ctx echo.Context
//   - params v1.PostWidgetLayoutResetParams
func (_e *ServerInterface_Expecter) PostWidgetLayoutReset(ctx interface{}, params interface{}) *ServerInterface_PostWidgetLayoutReset_Call {
	return &ServerInterface_PostWidgetLayoutReset_Call{Call: _e.mock.On("PostWidgetLayoutReset", ctx, params)}
}

func (_c *ServerInterface_PostWidgetLayoutReset_Call) Run(run func(ctx echo.Context, params v1.PostWidgetLayoutResetParams)) *ServerInterface_PostWidgetLayoutReset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context), args[1].(v1.PostWidgetLayoutResetParams))
	})
	return _c
}

func (_c *ServerInterface_PostWidgetLayoutReset_Call) Return(_a0 error) *ServerInterface_PostWidgetLayoutReset_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_PostWidgetLayoutReset_Call) RunAndReturn(run func(echo.Context, v1.PostWidgetLayoutResetParams) error) *ServerInterface_PostWidgetLayoutReset_Call {
	_c.Call.Return(run)
	return _c
}

// PutRooms provides a mock function with given fields: ctx
func (_m *ServerInterface) PutRooms(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PutRooms")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_PutRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutRooms'
type ServerInterface_PutRooms_Call struct {
	*mock.Call
}

// PutRooms is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) PutRooms(ctx interface{}) *ServerInterface_PutRooms_Call {
	return &ServerInterface_PutRooms_Call{Call: _e.mock.On("PutRooms", ctx)}
}

func (_c *ServerInterface_PutRooms_Call) Run(run func(ctx echo.Context)) *ServerInterface_PutRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_PutRooms_Call) Return(_a0 error) *ServerInterface_PutRooms_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_PutRooms_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_PutRooms_Call {
	_c.Call.Return(run)
	return _c
}

// PutTiles provides a mock function with given fields: ctx
func (_m *ServerInterface) PutTiles(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PutTiles")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_PutTiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutTiles'
type ServerInterface_PutTiles_Call struct {
	*mock.Call
}

// PutTiles is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) PutTiles(ctx interface{}) *ServerInterface_PutTiles_Call {
	return &ServerInterface_PutTiles_Call{Call: _e.mock.On("PutTiles", ctx)}
}

func (_c *ServerInterface_PutTiles_Call) Run(run func(ctx echo.Context)) *ServerInterface_PutTiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_PutTiles_Call) Return(_a0 error) *ServerInterface_PutTiles_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_PutTiles_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_PutTiles_Call {
	_c.Call.Return(run)
	return _c
}

// PutWidgetLayout provides a mock function with given fields: ctx
func (_m *ServerInterface) PutWidgetLayout(ctx echo.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for PutWidgetLayout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServerInterface_PutWidgetLayout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutWidgetLayout'
type ServerInterface_PutWidgetLayout_Call struct {
	*mock.Call
}

// PutWidgetLayout is a helper method to define mock.On call
//   - ctx echo.Context
func (_e *ServerInterface_Expecter) PutWidgetLayout(ctx interface{}) *ServerInterface_PutWidgetLayout_Call {
	return &ServerInterface_PutWidgetLayout_Call{Call: _e.mock.On("PutWidgetLayout", ctx)}
}

func (_c *ServerInterface_PutWidgetLayout_Call) Run(run func(ctx echo.Context)) *ServerInterface_PutWidgetLayout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(echo.Context))
	})
	return _c
}

func (_c *ServerInterface_PutWidgetLayout_Call) Return(_a0 error) *ServerInterface_PutWidgetLayout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerInterface_PutWidgetLayout_Call) RunAndReturn(run func(echo.Context) error) *ServerInterface_PutWidgetLayout_Call {
	_c.Call.Return(run)
	return _c
}

// NewServerInterface creates a new instance of ServerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ServerInterface {
	mock := &ServerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
