// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	widgetskills "jute-dash/apps/hub/pkg/widgetskills"
)

// SnapshotProvider is an autogenerated mock type for the SnapshotProvider type
type SnapshotProvider struct {
	mock.Mock
}

type SnapshotProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *SnapshotProvider) EXPECT() *SnapshotProvider_Expecter {
	return &SnapshotProvider_Expecter{mock: &_m.Mock}
}

// Snapshot provides a mock function with given fields: _a0
func (_m *SnapshotProvider) Snapshot(_a0 context.Context) (widgetskills.Snapshot, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Snapshot")
	}

	var r0 widgetskills.Snapshot
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (widgetskills.Snapshot, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) widgetskills.Snapshot); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(widgetskills.Snapshot)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SnapshotProvider_Snapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Snapshot'
type SnapshotProvider_Snapshot_Call struct {
	*mock.Call
}

// Snapshot is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *SnapshotProvider_Expecter) Snapshot(_a0 interface{}) *SnapshotProvider_Snapshot_Call {
	return &SnapshotProvider_Snapshot_Call{Call: _e.mock.On("Snapshot", _a0)}
}

func (_c *SnapshotProvider_Snapshot_Call) Run(run func(_a0 context.Context)) *SnapshotProvider_Snapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SnapshotProvider_Snapshot_Call) Return(_a0 widgetskills.Snapshot, _a1 error) *SnapshotProvider_Snapshot_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SnapshotProvider_Snapshot_Call) RunAndReturn(run func(context.Context) (widgetskills.Snapshot, error)) *SnapshotProvider_Snapshot_Call {
	_c.Call.Return(run)
	return _c
}

// NewSnapshotProvider creates a new instance of SnapshotProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSnapshotProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *SnapshotProvider {
	mock := &SnapshotProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
