// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "jute-dash/apps/hub/internal/app/model"

	mock "github.com/stretchr/testify/mock"

	widgetskills "jute-dash/apps/hub/pkg/widgetskills"
)

// SnapshotBuilder is an autogenerated mock type for the SnapshotBuilder type
type SnapshotBuilder struct {
	mock.Mock
}

type SnapshotBuilder_Expecter struct {
	mock *mock.Mock
}

func (_m *SnapshotBuilder) EXPECT() *SnapshotBuilder_Expecter {
	return &SnapshotBuilder_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, layout
func (_m *SnapshotBuilder) Execute(ctx context.Context, layout model.WidgetLayout) widgetskills.Snapshot {
	ret := _m.Called(ctx, layout)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 widgetskills.Snapshot
	if rf, ok := ret.Get(0).(func(context.Context, model.WidgetLayout) widgetskills.Snapshot); ok {
		r0 = rf(ctx, layout)
	} else {
		r0 = ret.Get(0).(widgetskills.Snapshot)
	}

	return r0
}

// SnapshotBuilder_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type SnapshotBuilder_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - layout model.WidgetLayout
func (_e *SnapshotBuilder_Expecter) Execute(ctx interface{}, layout interface{}) *SnapshotBuilder_Execute_Call {
	return &SnapshotBuilder_Execute_Call{Call: _e.mock.On("Execute", ctx, layout)}
}

func (_c *SnapshotBuilder_Execute_Call) Run(run func(ctx context.Context, layout model.WidgetLayout)) *SnapshotBuilder_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.WidgetLayout))
	})
	return _c
}

func (_c *SnapshotBuilder_Execute_Call) Return(_a0 widgetskills.Snapshot) *SnapshotBuilder_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *SnapshotBuilder_Execute_Call) RunAndReturn(run func(context.Context, model.WidgetLayout) widgetskills.Snapshot) *SnapshotBuilder_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewSnapshotBuilder creates a new instance of SnapshotBuilder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSnapshotBuilder(t interface {
	mock.TestingT
	Cleanup(func())
}) *SnapshotBuilder {
	mock := &SnapshotBuilder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
