// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	a2a "jute-dash/apps/hub/internal/pkg/a2a"

	mock "github.com/stretchr/testify/mock"
)

// TaskHistoryClient is an autogenerated mock type for the TaskHistoryClient type
type TaskHistoryClient struct {
	mock.Mock
}

type TaskHistoryClient_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskHistoryClient) EXPECT() *TaskHistoryClient_Expecter {
	return &TaskHistoryClient_Expecter{mock: &_m.Mock}
}

// GetTask provides a mock function with given fields: ctx, req
func (_m *TaskHistoryClient) GetTask(ctx context.Context, req a2a.GetTaskRequest) (a2a.TaskRecord, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 a2a.TaskRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, a2a.GetTaskRequest) (a2a.TaskRecord, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, a2a.GetTaskRequest) a2a.TaskRecord); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(a2a.TaskRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, a2a.GetTaskRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskHistoryClient_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type TaskHistoryClient_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - req a2a.GetTaskRequest
func (_e *TaskHistoryClient_Expecter) GetTask(ctx interface{}, req interface{}) *TaskHistoryClient_GetTask_Call {
	return &TaskHistoryClient_GetTask_Call{Call: _e.mock.On("GetTask", ctx, req)}
}

func (_c *TaskHistoryClient_GetTask_Call) Run(run func(ctx context.Context, req a2a.GetTaskRequest)) *TaskHistoryClient_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(a2a.GetTaskRequest))
	})
	return _c
}

func (_c *TaskHistoryClient_GetTask_Call) Return(_a0 a2a.TaskRecord, _a1 error) *TaskHistoryClient_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskHistoryClient_GetTask_Call) RunAndReturn(run func(context.Context, a2a.GetTaskRequest) (a2a.TaskRecord, error)) *TaskHistoryClient_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function with given fields: ctx, req
func (_m *TaskHistoryClient) ListTasks(ctx context.Context, req a2a.ListTasksRequest) (a2a.ListTasksResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 a2a.ListTasksResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, a2a.ListTasksRequest) (a2a.ListTasksResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, a2a.ListTasksRequest) a2a.ListTasksResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(a2a.ListTasksResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, a2a.ListTasksRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskHistoryClient_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type TaskHistoryClient_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - req a2a.ListTasksRequest
func (_e *TaskHistoryClient_Expecter) ListTasks(ctx interface{}, req interface{}) *TaskHistoryClient_ListTasks_Call {
	return &TaskHistoryClient_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx, req)}
}

func (_c *TaskHistoryClient_ListTasks_Call) Run(run func(ctx context.Context, req a2a.ListTasksRequest)) *TaskHistoryClient_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(a2a.ListTasksRequest))
	})
	return _c
}

func (_c *TaskHistoryClient_ListTasks_Call) Return(_a0 a2a.ListTasksResult, _a1 error) *TaskHistoryClient_ListTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TaskHistoryClient_ListTasks_Call) RunAndReturn(run func(context.Context, a2a.ListTasksRequest) (a2a.ListTasksResult, error)) *TaskHistoryClient_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// NewTaskHistoryClient creates a new instance of TaskHistoryClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskHistoryClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskHistoryClient {
	mock := &TaskHistoryClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
