// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mcp "jute-dash/apps/hub/internal/pkg/mcp"

	mock "github.com/stretchr/testify/mock"
)

// ToolRoute is an autogenerated mock type for the ToolRoute type
type ToolRoute struct {
	mock.Mock
}

type ToolRoute_Expecter struct {
	mock *mock.Mock
}

func (_m *ToolRoute) EXPECT() *ToolRoute_Expecter {
	return &ToolRoute_Expecter{mock: &_m.Mock}
}

// Call provides a mock function with given fields: ctx, args
func (_m *ToolRoute) Call(ctx mcp.RouteContext, args map[string]interface{}) (interface{}, error) {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for Call")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(mcp.RouteContext, map[string]interface{}) (interface{}, error)); ok {
		return rf(ctx, args)
	}
	if rf, ok := ret.Get(0).(func(mcp.RouteContext, map[string]interface{}) interface{}); ok {
		r0 = rf(ctx, args)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(mcp.RouteContext, map[string]interface{}) error); ok {
		r1 = rf(ctx, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ToolRoute_Call_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Call'
type ToolRoute_Call_Call struct {
	*mock.Call
}

// Call is a helper method to define mock.On call
//   - ctx mcp.RouteContext
//   - args map[string]interface{}
func (_e *ToolRoute_Expecter) Call(ctx interface{}, args interface{}) *ToolRoute_Call_Call {
	return &ToolRoute_Call_Call{Call: _e.mock.On("Call", ctx, args)}
}

func (_c *ToolRoute_Call_Call) Run(run func(ctx mcp.RouteContext, args map[string]interface{})) *ToolRoute_Call_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(mcp.RouteContext), args[1].(map[string]interface{}))
	})
	return _c
}

func (_c *ToolRoute_Call_Call) Return(_a0 interface{}, _a1 error) *ToolRoute_Call_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ToolRoute_Call_Call) RunAndReturn(run func(mcp.RouteContext, map[string]interface{}) (interface{}, error)) *ToolRoute_Call_Call {
	_c.Call.Return(run)
	return _c
}

// Description provides a mock function with no fields
func (_m *ToolRoute) Description() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ToolRoute_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type ToolRoute_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *ToolRoute_Expecter) Description() *ToolRoute_Description_Call {
	return &ToolRoute_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *ToolRoute_Description_Call) Run(run func()) *ToolRoute_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolRoute_Description_Call) Return(_a0 string) *ToolRoute_Description_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ToolRoute_Description_Call) RunAndReturn(run func() string) *ToolRoute_Description_Call {
	_c.Call.Return(run)
	return _c
}

// InputSchema provides a mock function with no fields
func (_m *ToolRoute) InputSchema() map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for InputSchema")
	}

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func() map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}

// ToolRoute_InputSchema_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InputSchema'
type ToolRoute_InputSchema_Call struct {
	*mock.Call
}

// InputSchema is a helper method to define mock.On call
func (_e *ToolRoute_Expecter) InputSchema() *ToolRoute_InputSchema_Call {
	return &ToolRoute_InputSchema_Call{Call: _e.mock.On("InputSchema")}
}

func (_c *ToolRoute_InputSchema_Call) Run(run func()) *ToolRoute_InputSchema_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolRoute_InputSchema_Call) Return(_a0 map[string]interface{}) *ToolRoute_InputSchema_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ToolRoute_InputSchema_Call) RunAndReturn(run func() map[string]interface{}) *ToolRoute_InputSchema_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *ToolRoute) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ToolRoute_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type ToolRoute_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *ToolRoute_Expecter) Name() *ToolRoute_Name_Call {
	return &ToolRoute_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *ToolRoute_Name_Call) Run(run func()) *ToolRoute_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolRoute_Name_Call) Return(_a0 string) *ToolRoute_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ToolRoute_Name_Call) RunAndReturn(run func() string) *ToolRoute_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Scope provides a mock function with no fields
func (_m *ToolRoute) Scope() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Scope")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ToolRoute_Scope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scope'
type ToolRoute_Scope_Call struct {
	*mock.Call
}

// Scope is a helper method to define mock.On call
func (_e *ToolRoute_Expecter) Scope() *ToolRoute_Scope_Call {
	return &ToolRoute_Scope_Call{Call: _e.mock.On("Scope")}
}

func (_c *ToolRoute_Scope_Call) Run(run func()) *ToolRoute_Scope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolRoute_Scope_Call) Return(_a0 string) *ToolRoute_Scope_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ToolRoute_Scope_Call) RunAndReturn(run func() string) *ToolRoute_Scope_Call {
	_c.Call.Return(run)
	return _c
}

// Title provides a mock function with no fields
func (_m *ToolRoute) Title() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Title")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ToolRoute_Title_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Title'
type ToolRoute_Title_Call struct {
	*mock.Call
}

// Title is a helper method to define mock.On call
func (_e *ToolRoute_Expecter) Title() *ToolRoute_Title_Call {
	return &ToolRoute_Title_Call{Call: _e.mock.On("Title")}
}

func (_c *ToolRoute_Title_Call) Run(run func()) *ToolRoute_Title_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ToolRoute_Title_Call) Return(_a0 string) *ToolRoute_Title_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ToolRoute_Title_Call) RunAndReturn(run func() string) *ToolRoute_Title_Call {
	_c.Call.Return(run)
	return _c
}

// NewToolRoute creates a new instance of ToolRoute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewToolRoute(t interface {
	mock.TestingT
	Cleanup(func())
}) *ToolRoute {
	mock := &ToolRoute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
