// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	service "jute-dash/apps/hub/internal/app/service"

	mock "github.com/stretchr/testify/mock"
)

// TTSProvider is an autogenerated mock type for the TTSProvider type
type TTSProvider struct {
	mock.Mock
}

type TTSProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *TTSProvider) EXPECT() *TTSProvider_Expecter {
	return &TTSProvider_Expecter{mock: &_m.Mock}
}

// Synthesize provides a mock function with given fields: ctx, req
func (_m *TTSProvider) Synthesize(ctx context.Context, req service.TTSRequest) (service.TTSAudioResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Synthesize")
	}

	var r0 service.TTSAudioResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.TTSRequest) (service.TTSAudioResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.TTSRequest) service.TTSAudioResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(service.TTSAudioResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.TTSRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TTSProvider_Synthesize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Synthesize'
type TTSProvider_Synthesize_Call struct {
	*mock.Call
}

// Synthesize is a helper method to define mock.On call
//   - ctx context.Context
//   - req service.TTSRequest
func (_e *TTSProvider_Expecter) Synthesize(ctx interface{}, req interface{}) *TTSProvider_Synthesize_Call {
	return &TTSProvider_Synthesize_Call{Call: _e.mock.On("Synthesize", ctx, req)}
}

func (_c *TTSProvider_Synthesize_Call) Run(run func(ctx context.Context, req service.TTSRequest)) *TTSProvider_Synthesize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(service.TTSRequest))
	})
	return _c
}

func (_c *TTSProvider_Synthesize_Call) Return(_a0 service.TTSAudioResult, _a1 error) *TTSProvider_Synthesize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TTSProvider_Synthesize_Call) RunAndReturn(run func(context.Context, service.TTSRequest) (service.TTSAudioResult, error)) *TTSProvider_Synthesize_Call {
	_c.Call.Return(run)
	return _c
}

// NewTTSProvider creates a new instance of TTSProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTTSProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *TTSProvider {
	mock := &TTSProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
