// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	service "jute-dash/apps/hub/internal/app/service"

	mock "github.com/stretchr/testify/mock"
)

// VoiceDisplayEmitter is an autogenerated mock type for the VoiceDisplayEmitter type
type VoiceDisplayEmitter struct {
	mock.Mock
}

type VoiceDisplayEmitter_Expecter struct {
	mock *mock.Mock
}

func (_m *VoiceDisplayEmitter) EXPECT() *VoiceDisplayEmitter_Expecter {
	return &VoiceDisplayEmitter_Expecter{mock: &_m.Mock}
}

// EmitConversationEvent provides a mock function with given fields: eventType, deviceID, conversationID, payload
func (_m *VoiceDisplayEmitter) EmitConversationEvent(eventType string, deviceID string, conversationID string, payload interface{}) service.VoiceEvent {
	ret := _m.Called(eventType, deviceID, conversationID, payload)

	if len(ret) == 0 {
		panic("no return value specified for EmitConversationEvent")
	}

	var r0 service.VoiceEvent
	if rf, ok := ret.Get(0).(func(string, string, string, interface{}) service.VoiceEvent); ok {
		r0 = rf(eventType, deviceID, conversationID, payload)
	} else {
		r0 = ret.Get(0).(service.VoiceEvent)
	}

	return r0
}

// VoiceDisplayEmitter_EmitConversationEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmitConversationEvent'
type VoiceDisplayEmitter_EmitConversationEvent_Call struct {
	*mock.Call
}

// EmitConversationEvent is a helper method to define mock.On call
//   - eventType string
//   - deviceID string
//   - conversationID string
//   - payload interface{}
func (_e *VoiceDisplayEmitter_Expecter) EmitConversationEvent(eventType interface{}, deviceID interface{}, conversationID interface{}, payload interface{}) *VoiceDisplayEmitter_EmitConversationEvent_Call {
	return &VoiceDisplayEmitter_EmitConversationEvent_Call{Call: _e.mock.On("EmitConversationEvent", eventType, deviceID, conversationID, payload)}
}

func (_c *VoiceDisplayEmitter_EmitConversationEvent_Call) Run(run func(eventType string, deviceID string, conversationID string, payload interface{})) *VoiceDisplayEmitter_EmitConversationEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(string), args[3].(interface{}))
	})
	return _c
}

func (_c *VoiceDisplayEmitter_EmitConversationEvent_Call) Return(_a0 service.VoiceEvent) *VoiceDisplayEmitter_EmitConversationEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VoiceDisplayEmitter_EmitConversationEvent_Call) RunAndReturn(run func(string, string, string, interface{}) service.VoiceEvent) *VoiceDisplayEmitter_EmitConversationEvent_Call {
	_c.Call.Return(run)
	return _c
}

// EmitTTSEvent provides a mock function with given fields: eventType, deviceID, response
func (_m *VoiceDisplayEmitter) EmitTTSEvent(eventType string, deviceID string, response service.TTSActionResponse) service.VoiceEvent {
	ret := _m.Called(eventType, deviceID, response)

	if len(ret) == 0 {
		panic("no return value specified for EmitTTSEvent")
	}

	var r0 service.VoiceEvent
	if rf, ok := ret.Get(0).(func(string, string, service.TTSActionResponse) service.VoiceEvent); ok {
		r0 = rf(eventType, deviceID, response)
	} else {
		r0 = ret.Get(0).(service.VoiceEvent)
	}

	return r0
}

// VoiceDisplayEmitter_EmitTTSEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmitTTSEvent'
type VoiceDisplayEmitter_EmitTTSEvent_Call struct {
	*mock.Call
}

// EmitTTSEvent is a helper method to define mock.On call
//   - eventType string
//   - deviceID string
//   - response service.TTSActionResponse
func (_e *VoiceDisplayEmitter_Expecter) EmitTTSEvent(eventType interface{}, deviceID interface{}, response interface{}) *VoiceDisplayEmitter_EmitTTSEvent_Call {
	return &VoiceDisplayEmitter_EmitTTSEvent_Call{Call: _e.mock.On("EmitTTSEvent", eventType, deviceID, response)}
}

func (_c *VoiceDisplayEmitter_EmitTTSEvent_Call) Run(run func(eventType string, deviceID string, response service.TTSActionResponse)) *VoiceDisplayEmitter_EmitTTSEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string), args[2].(service.TTSActionResponse))
	})
	return _c
}

func (_c *VoiceDisplayEmitter_EmitTTSEvent_Call) Return(_a0 service.VoiceEvent) *VoiceDisplayEmitter_EmitTTSEvent_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VoiceDisplayEmitter_EmitTTSEvent_Call) RunAndReturn(run func(string, string, service.TTSActionResponse) service.VoiceEvent) *VoiceDisplayEmitter_EmitTTSEvent_Call {
	_c.Call.Return(run)
	return _c
}

// EmitVoiceStateChanged provides a mock function with given fields: deviceProfileID, payload
func (_m *VoiceDisplayEmitter) EmitVoiceStateChanged(deviceProfileID string, payload service.VoiceStatePayload) service.VoiceEvent {
	ret := _m.Called(deviceProfileID, payload)

	if len(ret) == 0 {
		panic("no return value specified for EmitVoiceStateChanged")
	}

	var r0 service.VoiceEvent
	if rf, ok := ret.Get(0).(func(string, service.VoiceStatePayload) service.VoiceEvent); ok {
		r0 = rf(deviceProfileID, payload)
	} else {
		r0 = ret.Get(0).(service.VoiceEvent)
	}

	return r0
}

// VoiceDisplayEmitter_EmitVoiceStateChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmitVoiceStateChanged'
type VoiceDisplayEmitter_EmitVoiceStateChanged_Call struct {
	*mock.Call
}

// EmitVoiceStateChanged is a helper method to define mock.On call
//   - deviceProfileID string
//   - payload service.VoiceStatePayload
func (_e *VoiceDisplayEmitter_Expecter) EmitVoiceStateChanged(deviceProfileID interface{}, payload interface{}) *VoiceDisplayEmitter_EmitVoiceStateChanged_Call {
	return &VoiceDisplayEmitter_EmitVoiceStateChanged_Call{Call: _e.mock.On("EmitVoiceStateChanged", deviceProfileID, payload)}
}

func (_c *VoiceDisplayEmitter_EmitVoiceStateChanged_Call) Run(run func(deviceProfileID string, payload service.VoiceStatePayload)) *VoiceDisplayEmitter_EmitVoiceStateChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(service.VoiceStatePayload))
	})
	return _c
}

func (_c *VoiceDisplayEmitter_EmitVoiceStateChanged_Call) Return(_a0 service.VoiceEvent) *VoiceDisplayEmitter_EmitVoiceStateChanged_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VoiceDisplayEmitter_EmitVoiceStateChanged_Call) RunAndReturn(run func(string, service.VoiceStatePayload) service.VoiceEvent) *VoiceDisplayEmitter_EmitVoiceStateChanged_Call {
	_c.Call.Return(run)
	return _c
}

// NewVoiceDisplayEmitter creates a new instance of VoiceDisplayEmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoiceDisplayEmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *VoiceDisplayEmitter {
	mock := &VoiceDisplayEmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
