// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	service "jute-dash/apps/hub/internal/app/service"

	mock "github.com/stretchr/testify/mock"
)

// VoiceActivityDetector is an autogenerated mock type for the VoiceActivityDetector type
type VoiceActivityDetector struct {
	mock.Mock
}

type VoiceActivityDetector_Expecter struct {
	mock *mock.Mock
}

func (_m *VoiceActivityDetector) EXPECT() *VoiceActivityDetector_Expecter {
	return &VoiceActivityDetector_Expecter{mock: &_m.Mock}
}

// Speech provides a mock function with given fields: frame
func (_m *VoiceActivityDetector) Speech(frame service.AudioFrame) bool {
	ret := _m.Called(frame)

	if len(ret) == 0 {
		panic("no return value specified for Speech")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(service.AudioFrame) bool); ok {
		r0 = rf(frame)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// VoiceActivityDetector_Speech_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Speech'
type VoiceActivityDetector_Speech_Call struct {
	*mock.Call
}

// Speech is a helper method to define mock.On call
//   - frame service.AudioFrame
func (_e *VoiceActivityDetector_Expecter) Speech(frame interface{}) *VoiceActivityDetector_Speech_Call {
	return &VoiceActivityDetector_Speech_Call{Call: _e.mock.On("Speech", frame)}
}

func (_c *VoiceActivityDetector_Speech_Call) Run(run func(frame service.AudioFrame)) *VoiceActivityDetector_Speech_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(service.AudioFrame))
	})
	return _c
}

func (_c *VoiceActivityDetector_Speech_Call) Return(_a0 bool) *VoiceActivityDetector_Speech_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *VoiceActivityDetector_Speech_Call) RunAndReturn(run func(service.AudioFrame) bool) *VoiceActivityDetector_Speech_Call {
	_c.Call.Return(run)
	return _c
}

// NewVoiceActivityDetector creates a new instance of VoiceActivityDetector. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoiceActivityDetector(t interface {
	mock.TestingT
	Cleanup(func())
}) *VoiceActivityDetector {
	mock := &VoiceActivityDetector{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
