// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	model "jute-dash/apps/hub/internal/app/model"

	mock "github.com/stretchr/testify/mock"
)

// VoiceStore is an autogenerated mock type for the VoiceStore type
type VoiceStore struct {
	mock.Mock
}

type VoiceStore_Expecter struct {
	mock *mock.Mock
}

func (_m *VoiceStore) EXPECT() *VoiceStore_Expecter {
	return &VoiceStore_Expecter{mock: &_m.Mock}
}

// VoiceSettings provides a mock function with given fields: ctx, deviceProfileID
func (_m *VoiceStore) VoiceSettings(ctx context.Context, deviceProfileID string) (model.VoiceSettings, error) {
	ret := _m.Called(ctx, deviceProfileID)

	if len(ret) == 0 {
		panic("no return value specified for VoiceSettings")
	}

	var r0 model.VoiceSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (model.VoiceSettings, error)); ok {
		return rf(ctx, deviceProfileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) model.VoiceSettings); ok {
		r0 = rf(ctx, deviceProfileID)
	} else {
		r0 = ret.Get(0).(model.VoiceSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, deviceProfileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// VoiceStore_VoiceSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VoiceSettings'
type VoiceStore_VoiceSettings_Call struct {
	*mock.Call
}

// VoiceSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - deviceProfileID string
func (_e *VoiceStore_Expecter) VoiceSettings(ctx interface{}, deviceProfileID interface{}) *VoiceStore_VoiceSettings_Call {
	return &VoiceStore_VoiceSettings_Call{Call: _e.mock.On("VoiceSettings", ctx, deviceProfileID)}
}

func (_c *VoiceStore_VoiceSettings_Call) Run(run func(ctx context.Context, deviceProfileID string)) *VoiceStore_VoiceSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *VoiceStore_VoiceSettings_Call) Return(_a0 model.VoiceSettings, _a1 error) *VoiceStore_VoiceSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *VoiceStore_VoiceSettings_Call) RunAndReturn(run func(context.Context, string) (model.VoiceSettings, error)) *VoiceStore_VoiceSettings_Call {
	_c.Call.Return(run)
	return _c
}

// NewVoiceStore creates a new instance of VoiceStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVoiceStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *VoiceStore {
	mock := &VoiceStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
