// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	voice "jute-dash/apps/hub/internal/app/service/voice"

	mock "github.com/stretchr/testify/mock"
)

// WakeEventEmitter is an autogenerated mock type for the WakeEventEmitter type
type WakeEventEmitter struct {
	mock.Mock
}

type WakeEventEmitter_Expecter struct {
	mock *mock.Mock
}

func (_m *WakeEventEmitter) EXPECT() *WakeEventEmitter_Expecter {
	return &WakeEventEmitter_Expecter{mock: &_m.Mock}
}

// EmitVoiceStateChanged provides a mock function with given fields: deviceID, payload
func (_m *WakeEventEmitter) EmitVoiceStateChanged(deviceID string, payload voice.VoiceStatePayload) voice.VoiceEvent {
	ret := _m.Called(deviceID, payload)

	if len(ret) == 0 {
		panic("no return value specified for EmitVoiceStateChanged")
	}

	var r0 voice.VoiceEvent
	if rf, ok := ret.Get(0).(func(string, voice.VoiceStatePayload) voice.VoiceEvent); ok {
		r0 = rf(deviceID, payload)
	} else {
		r0 = ret.Get(0).(voice.VoiceEvent)
	}

	return r0
}

// WakeEventEmitter_EmitVoiceStateChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmitVoiceStateChanged'
type WakeEventEmitter_EmitVoiceStateChanged_Call struct {
	*mock.Call
}

// EmitVoiceStateChanged is a helper method to define mock.On call
//   - deviceID string
//   - payload voice.VoiceStatePayload
func (_e *WakeEventEmitter_Expecter) EmitVoiceStateChanged(deviceID interface{}, payload interface{}) *WakeEventEmitter_EmitVoiceStateChanged_Call {
	return &WakeEventEmitter_EmitVoiceStateChanged_Call{Call: _e.mock.On("EmitVoiceStateChanged", deviceID, payload)}
}

func (_c *WakeEventEmitter_EmitVoiceStateChanged_Call) Run(run func(deviceID string, payload voice.VoiceStatePayload)) *WakeEventEmitter_EmitVoiceStateChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(voice.VoiceStatePayload))
	})
	return _c
}

func (_c *WakeEventEmitter_EmitVoiceStateChanged_Call) Return(_a0 voice.VoiceEvent) *WakeEventEmitter_EmitVoiceStateChanged_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WakeEventEmitter_EmitVoiceStateChanged_Call) RunAndReturn(run func(string, voice.VoiceStatePayload) voice.VoiceEvent) *WakeEventEmitter_EmitVoiceStateChanged_Call {
	_c.Call.Return(run)
	return _c
}

// EmitVoiceWakeDetected provides a mock function with given fields: deviceID, conversationID
func (_m *WakeEventEmitter) EmitVoiceWakeDetected(deviceID string, conversationID string) voice.VoiceEvent {
	ret := _m.Called(deviceID, conversationID)

	if len(ret) == 0 {
		panic("no return value specified for EmitVoiceWakeDetected")
	}

	var r0 voice.VoiceEvent
	if rf, ok := ret.Get(0).(func(string, string) voice.VoiceEvent); ok {
		r0 = rf(deviceID, conversationID)
	} else {
		r0 = ret.Get(0).(voice.VoiceEvent)
	}

	return r0
}

// WakeEventEmitter_EmitVoiceWakeDetected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmitVoiceWakeDetected'
type WakeEventEmitter_EmitVoiceWakeDetected_Call struct {
	*mock.Call
}

// EmitVoiceWakeDetected is a helper method to define mock.On call
//   - deviceID string
//   - conversationID string
func (_e *WakeEventEmitter_Expecter) EmitVoiceWakeDetected(deviceID interface{}, conversationID interface{}) *WakeEventEmitter_EmitVoiceWakeDetected_Call {
	return &WakeEventEmitter_EmitVoiceWakeDetected_Call{Call: _e.mock.On("EmitVoiceWakeDetected", deviceID, conversationID)}
}

func (_c *WakeEventEmitter_EmitVoiceWakeDetected_Call) Run(run func(deviceID string, conversationID string)) *WakeEventEmitter_EmitVoiceWakeDetected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *WakeEventEmitter_EmitVoiceWakeDetected_Call) Return(_a0 voice.VoiceEvent) *WakeEventEmitter_EmitVoiceWakeDetected_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WakeEventEmitter_EmitVoiceWakeDetected_Call) RunAndReturn(run func(string, string) voice.VoiceEvent) *WakeEventEmitter_EmitVoiceWakeDetected_Call {
	_c.Call.Return(run)
	return _c
}

// NewWakeEventEmitter creates a new instance of WakeEventEmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWakeEventEmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *WakeEventEmitter {
	mock := &WakeEventEmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
