// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	voice "jute-dash/apps/hub/internal/app/service/voice"

	mock "github.com/stretchr/testify/mock"
)

// WakeProvider is an autogenerated mock type for the WakeProvider type
type WakeProvider struct {
	mock.Mock
}

type WakeProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *WakeProvider) EXPECT() *WakeProvider_Expecter {
	return &WakeProvider_Expecter{mock: &_m.Mock}
}

// DetectWake provides a mock function with given fields: ctx, utterance
func (_m *WakeProvider) DetectWake(ctx context.Context, utterance voice.CapturedUtterance) (voice.WakeDetection, error) {
	ret := _m.Called(ctx, utterance)

	if len(ret) == 0 {
		panic("no return value specified for DetectWake")
	}

	var r0 voice.WakeDetection
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, voice.CapturedUtterance) (voice.WakeDetection, error)); ok {
		return rf(ctx, utterance)
	}
	if rf, ok := ret.Get(0).(func(context.Context, voice.CapturedUtterance) voice.WakeDetection); ok {
		r0 = rf(ctx, utterance)
	} else {
		r0 = ret.Get(0).(voice.WakeDetection)
	}

	if rf, ok := ret.Get(1).(func(context.Context, voice.CapturedUtterance) error); ok {
		r1 = rf(ctx, utterance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WakeProvider_DetectWake_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DetectWake'
type WakeProvider_DetectWake_Call struct {
	*mock.Call
}

// DetectWake is a helper method to define mock.On call
//   - ctx context.Context
//   - utterance voice.CapturedUtterance
func (_e *WakeProvider_Expecter) DetectWake(ctx interface{}, utterance interface{}) *WakeProvider_DetectWake_Call {
	return &WakeProvider_DetectWake_Call{Call: _e.mock.On("DetectWake", ctx, utterance)}
}

func (_c *WakeProvider_DetectWake_Call) Run(run func(ctx context.Context, utterance voice.CapturedUtterance)) *WakeProvider_DetectWake_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(voice.CapturedUtterance))
	})
	return _c
}

func (_c *WakeProvider_DetectWake_Call) Return(_a0 voice.WakeDetection, _a1 error) *WakeProvider_DetectWake_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WakeProvider_DetectWake_Call) RunAndReturn(run func(context.Context, voice.CapturedUtterance) (voice.WakeDetection, error)) *WakeProvider_DetectWake_Call {
	_c.Call.Return(run)
	return _c
}

// NewWakeProvider creates a new instance of WakeProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWakeProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *WakeProvider {
	mock := &WakeProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
