// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// WidgetActionDispatcher is an autogenerated mock type for the WidgetActionDispatcher type
type WidgetActionDispatcher struct {
	mock.Mock
}

type WidgetActionDispatcher_Expecter struct {
	mock *mock.Mock
}

func (_m *WidgetActionDispatcher) EXPECT() *WidgetActionDispatcher_Expecter {
	return &WidgetActionDispatcher_Expecter{mock: &_m.Mock}
}

// InvokeWidgetAction provides a mock function with given fields: ctx, widgetInstanceID, actionID, arguments, actor, confirmed
func (_m *WidgetActionDispatcher) InvokeWidgetAction(ctx context.Context, widgetInstanceID string, actionID string, arguments map[string]interface{}, actor string, confirmed bool) (map[string]interface{}, error) {
	ret := _m.Called(ctx, widgetInstanceID, actionID, arguments, actor, confirmed)

	if len(ret) == 0 {
		panic("no return value specified for InvokeWidgetAction")
	}

	var r0 map[string]interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]interface{}, string, bool) (map[string]interface{}, error)); ok {
		return rf(ctx, widgetInstanceID, actionID, arguments, actor, confirmed)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, map[string]interface{}, string, bool) map[string]interface{}); ok {
		r0 = rf(ctx, widgetInstanceID, actionID, arguments, actor, confirmed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, map[string]interface{}, string, bool) error); ok {
		r1 = rf(ctx, widgetInstanceID, actionID, arguments, actor, confirmed)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WidgetActionDispatcher_InvokeWidgetAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvokeWidgetAction'
type WidgetActionDispatcher_InvokeWidgetAction_Call struct {
	*mock.Call
}

// InvokeWidgetAction is a helper method to define mock.On call
//   - ctx context.Context
//   - widgetInstanceID string
//   - actionID string
//   - arguments map[string]interface{}
//   - actor string
//   - confirmed bool
func (_e *WidgetActionDispatcher_Expecter) InvokeWidgetAction(ctx interface{}, widgetInstanceID interface{}, actionID interface{}, arguments interface{}, actor interface{}, confirmed interface{}) *WidgetActionDispatcher_InvokeWidgetAction_Call {
	return &WidgetActionDispatcher_InvokeWidgetAction_Call{Call: _e.mock.On("InvokeWidgetAction", ctx, widgetInstanceID, actionID, arguments, actor, confirmed)}
}

func (_c *WidgetActionDispatcher_InvokeWidgetAction_Call) Run(run func(ctx context.Context, widgetInstanceID string, actionID string, arguments map[string]interface{}, actor string, confirmed bool)) *WidgetActionDispatcher_InvokeWidgetAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(map[string]interface{}), args[4].(string), args[5].(bool))
	})
	return _c
}

func (_c *WidgetActionDispatcher_InvokeWidgetAction_Call) Return(_a0 map[string]interface{}, _a1 error) *WidgetActionDispatcher_InvokeWidgetAction_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *WidgetActionDispatcher_InvokeWidgetAction_Call) RunAndReturn(run func(context.Context, string, string, map[string]interface{}, string, bool) (map[string]interface{}, error)) *WidgetActionDispatcher_InvokeWidgetAction_Call {
	_c.Call.Return(run)
	return _c
}

// NewWidgetActionDispatcher creates a new instance of WidgetActionDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWidgetActionDispatcher(t interface {
	mock.TestingT
	Cleanup(func())
}) *WidgetActionDispatcher {
	mock := &WidgetActionDispatcher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
