// Code generated by mockery v2.53.6. DO NOT EDIT.

package agents

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AgentSyncer is an autogenerated mock type for the Syncer type
type AgentSyncer struct {
	mock.Mock
}

type AgentSyncer_Expecter struct {
	mock *mock.Mock
}

func (_m *AgentSyncer) EXPECT() *AgentSyncer_Expecter {
	return &AgentSyncer_Expecter{mock: &_m.Mock}
}

// AgentsConfig provides a mock function with given fields: ctx
func (_m *AgentSyncer) AgentsConfig(ctx context.Context) ([]AgentConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AgentsConfig")
	}

	var r0 []AgentConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]AgentConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []AgentConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]AgentConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AgentSyncer_AgentsConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AgentsConfig'
type AgentSyncer_AgentsConfig_Call struct {
	*mock.Call
}

// AgentsConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AgentSyncer_Expecter) AgentsConfig(ctx interface{}) *AgentSyncer_AgentsConfig_Call {
	return &AgentSyncer_AgentsConfig_Call{Call: _e.mock.On("AgentsConfig", ctx)}
}

func (_c *AgentSyncer_AgentsConfig_Call) Run(run func(ctx context.Context)) *AgentSyncer_AgentsConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AgentSyncer_AgentsConfig_Call) Return(_a0 []AgentConfig, _a1 error) *AgentSyncer_AgentsConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AgentSyncer_AgentsConfig_Call) RunAndReturn(run func(context.Context) ([]AgentConfig, error)) *AgentSyncer_AgentsConfig_Call {
	_c.Call.Return(run)
	return _c
}

// SyncAgents provides a mock function with given fields: ctx, configs
func (_m *AgentSyncer) SyncAgents(ctx context.Context, configs []AgentConfig) error {
	ret := _m.Called(ctx, configs)

	if len(ret) == 0 {
		panic("no return value specified for SyncAgents")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []AgentConfig) error); ok {
		r0 = rf(ctx, configs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// AgentSyncer_SyncAgents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncAgents'
type AgentSyncer_SyncAgents_Call struct {
	*mock.Call
}

// SyncAgents is a helper method to define mock.On call
//   - ctx context.Context
//   - configs []AgentConfig
func (_e *AgentSyncer_Expecter) SyncAgents(ctx interface{}, configs interface{}) *AgentSyncer_SyncAgents_Call {
	return &AgentSyncer_SyncAgents_Call{Call: _e.mock.On("SyncAgents", ctx, configs)}
}

func (_c *AgentSyncer_SyncAgents_Call) Run(run func(ctx context.Context, configs []AgentConfig)) *AgentSyncer_SyncAgents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]AgentConfig))
	})
	return _c
}

func (_c *AgentSyncer_SyncAgents_Call) Return(_a0 error) *AgentSyncer_SyncAgents_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AgentSyncer_SyncAgents_Call) RunAndReturn(run func(context.Context, []AgentConfig) error) *AgentSyncer_SyncAgents_Call {
	_c.Call.Return(run)
	return _c
}

// NewAgentSyncer creates a new instance of AgentSyncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAgentSyncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *AgentSyncer {
	mock := &AgentSyncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
