// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	voice "jute-dash/apps/hub/internal/app/voice"

	mock "github.com/stretchr/testify/mock"
)

// AudioCapture is an autogenerated mock type for the AudioCapture type
type AudioCapture struct {
	mock.Mock
}

type AudioCapture_Expecter struct {
	mock *mock.Mock
}

func (_m *AudioCapture) EXPECT() *AudioCapture_Expecter {
	return &AudioCapture_Expecter{mock: &_m.Mock}
}

// Capture provides a mock function with given fields: ctx
func (_m *AudioCapture) Capture(ctx context.Context) (<-chan voice.AudioFrame, <-chan error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Capture")
	}

	var r0 <-chan voice.AudioFrame
	var r1 <-chan error
	if rf, ok := ret.Get(0).(func(context.Context) (<-chan voice.AudioFrame, <-chan error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) <-chan voice.AudioFrame); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan voice.AudioFrame)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) <-chan error); ok {
		r1 = rf(ctx)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(<-chan error)
		}
	}

	return r0, r1
}

// AudioCapture_Capture_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Capture'
type AudioCapture_Capture_Call struct {
	*mock.Call
}

// Capture is a helper method to define mock.On call
//   - ctx context.Context
func (_e *AudioCapture_Expecter) Capture(ctx interface{}) *AudioCapture_Capture_Call {
	return &AudioCapture_Capture_Call{Call: _e.mock.On("Capture", ctx)}
}

func (_c *AudioCapture_Capture_Call) Run(run func(ctx context.Context)) *AudioCapture_Capture_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *AudioCapture_Capture_Call) Return(_a0 <-chan voice.AudioFrame, _a1 <-chan error) *AudioCapture_Capture_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AudioCapture_Capture_Call) RunAndReturn(run func(context.Context) (<-chan voice.AudioFrame, <-chan error)) *AudioCapture_Capture_Call {
	_c.Call.Return(run)
	return _c
}

// NewAudioCapture creates a new instance of AudioCapture. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAudioCapture(t interface {
	mock.TestingT
	Cleanup(func())
}) *AudioCapture {
	mock := &AudioCapture{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
