// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	a2a "jute-dash/apps/hub/internal/pkg/a2a"

	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// GetTask provides a mock function with given fields: ctx, req
func (_m *Client) GetTask(ctx context.Context, req a2a.GetTaskRequest) (a2a.TaskRecord, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 a2a.TaskRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, a2a.GetTaskRequest) (a2a.TaskRecord, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, a2a.GetTaskRequest) a2a.TaskRecord); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(a2a.TaskRecord)
	}

	if rf, ok := ret.Get(1).(func(context.Context, a2a.GetTaskRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_GetTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTask'
type Client_GetTask_Call struct {
	*mock.Call
}

// GetTask is a helper method to define mock.On call
//   - ctx context.Context
//   - req a2a.GetTaskRequest
func (_e *Client_Expecter) GetTask(ctx interface{}, req interface{}) *Client_GetTask_Call {
	return &Client_GetTask_Call{Call: _e.mock.On("GetTask", ctx, req)}
}

func (_c *Client_GetTask_Call) Run(run func(ctx context.Context, req a2a.GetTaskRequest)) *Client_GetTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(a2a.GetTaskRequest))
	})
	return _c
}

func (_c *Client_GetTask_Call) Return(_a0 a2a.TaskRecord, _a1 error) *Client_GetTask_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_GetTask_Call) RunAndReturn(run func(context.Context, a2a.GetTaskRequest) (a2a.TaskRecord, error)) *Client_GetTask_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function with given fields: ctx, req
func (_m *Client) ListTasks(ctx context.Context, req a2a.ListTasksRequest) (a2a.ListTasksResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 a2a.ListTasksResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, a2a.ListTasksRequest) (a2a.ListTasksResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, a2a.ListTasksRequest) a2a.ListTasksResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(a2a.ListTasksResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, a2a.ListTasksRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type Client_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
//   - ctx context.Context
//   - req a2a.ListTasksRequest
func (_e *Client_Expecter) ListTasks(ctx interface{}, req interface{}) *Client_ListTasks_Call {
	return &Client_ListTasks_Call{Call: _e.mock.On("ListTasks", ctx, req)}
}

func (_c *Client_ListTasks_Call) Run(run func(ctx context.Context, req a2a.ListTasksRequest)) *Client_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(a2a.ListTasksRequest))
	})
	return _c
}

func (_c *Client_ListTasks_Call) Return(_a0 a2a.ListTasksResult, _a1 error) *Client_ListTasks_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_ListTasks_Call) RunAndReturn(run func(context.Context, a2a.ListTasksRequest) (a2a.ListTasksResult, error)) *Client_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function with given fields: ctx, req
func (_m *Client) SendMessage(ctx context.Context, req a2a.SendMessageRequest) (a2a.SendMessageResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 a2a.SendMessageResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, a2a.SendMessageRequest) (a2a.SendMessageResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, a2a.SendMessageRequest) a2a.SendMessageResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(a2a.SendMessageResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, a2a.SendMessageRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type Client_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - req a2a.SendMessageRequest
func (_e *Client_Expecter) SendMessage(ctx interface{}, req interface{}) *Client_SendMessage_Call {
	return &Client_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, req)}
}

func (_c *Client_SendMessage_Call) Run(run func(ctx context.Context, req a2a.SendMessageRequest)) *Client_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(a2a.SendMessageRequest))
	})
	return _c
}

func (_c *Client_SendMessage_Call) Return(_a0 a2a.SendMessageResult, _a1 error) *Client_SendMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_SendMessage_Call) RunAndReturn(run func(context.Context, a2a.SendMessageRequest) (a2a.SendMessageResult, error)) *Client_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// StreamMessage provides a mock function with given fields: ctx, req, handler
func (_m *Client) StreamMessage(ctx context.Context, req a2a.SendMessageRequest, handler a2a.StreamHandler) error {
	ret := _m.Called(ctx, req, handler)

	if len(ret) == 0 {
		panic("no return value specified for StreamMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, a2a.SendMessageRequest, a2a.StreamHandler) error); ok {
		r0 = rf(ctx, req, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Client_StreamMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamMessage'
type Client_StreamMessage_Call struct {
	*mock.Call
}

// StreamMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - req a2a.SendMessageRequest
//   - handler a2a.StreamHandler
func (_e *Client_Expecter) StreamMessage(ctx interface{}, req interface{}, handler interface{}) *Client_StreamMessage_Call {
	return &Client_StreamMessage_Call{Call: _e.mock.On("StreamMessage", ctx, req, handler)}
}

func (_c *Client_StreamMessage_Call) Run(run func(ctx context.Context, req a2a.SendMessageRequest, handler a2a.StreamHandler)) *Client_StreamMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(a2a.SendMessageRequest), args[2].(a2a.StreamHandler))
	})
	return _c
}

func (_c *Client_StreamMessage_Call) Return(_a0 error) *Client_StreamMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Client_StreamMessage_Call) RunAndReturn(run func(context.Context, a2a.SendMessageRequest, a2a.StreamHandler) error) *Client_StreamMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
