// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	config "jute-dash/apps/hub/internal/app/config"

	mock "github.com/stretchr/testify/mock"
)

// ConfigStore is an autogenerated mock type for the ConfigStore type
type ConfigStore struct {
	mock.Mock
}

type ConfigStore_Expecter struct {
	mock *mock.Mock
}

func (_m *ConfigStore) EXPECT() *ConfigStore_Expecter {
	return &ConfigStore_Expecter{mock: &_m.Mock}
}

// Config provides a mock function with given fields: ctx
func (_m *ConfigStore) Config(ctx context.Context) (config.Config, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (config.Config, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) config.Config); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(config.Config)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigStore_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type ConfigStore_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ConfigStore_Expecter) Config(ctx interface{}) *ConfigStore_Config_Call {
	return &ConfigStore_Config_Call{Call: _e.mock.On("Config", ctx)}
}

func (_c *ConfigStore_Config_Call) Run(run func(ctx context.Context)) *ConfigStore_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ConfigStore_Config_Call) Return(_a0 config.Config, _a1 error) *ConfigStore_Config_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ConfigStore_Config_Call) RunAndReturn(run func(context.Context) (config.Config, error)) *ConfigStore_Config_Call {
	_c.Call.Return(run)
	return _c
}

// NewConfigStore creates a new instance of ConfigStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigStore {
	mock := &ConfigStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
