// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	displayactions "jute-dash/apps/hub/internal/pkg/displayactions"

	mock "github.com/stretchr/testify/mock"
)

// DisplayEmitter is an autogenerated mock type for the DisplayEmitter type
type DisplayEmitter struct {
	mock.Mock
}

type DisplayEmitter_Expecter struct {
	mock *mock.Mock
}

func (_m *DisplayEmitter) EXPECT() *DisplayEmitter_Expecter {
	return &DisplayEmitter_Expecter{mock: &_m.Mock}
}

// EmitVoiceStateChanged provides a mock function with given fields: deviceProfileID, payload
func (_m *DisplayEmitter) EmitVoiceStateChanged(deviceProfileID string, payload displayactions.VoiceStatePayload) displayactions.VoiceEvent {
	ret := _m.Called(deviceProfileID, payload)

	if len(ret) == 0 {
		panic("no return value specified for EmitVoiceStateChanged")
	}

	var r0 displayactions.VoiceEvent
	if rf, ok := ret.Get(0).(func(string, displayactions.VoiceStatePayload) displayactions.VoiceEvent); ok {
		r0 = rf(deviceProfileID, payload)
	} else {
		r0 = ret.Get(0).(displayactions.VoiceEvent)
	}

	return r0
}

// DisplayEmitter_EmitVoiceStateChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EmitVoiceStateChanged'
type DisplayEmitter_EmitVoiceStateChanged_Call struct {
	*mock.Call
}

// EmitVoiceStateChanged is a helper method to define mock.On call
//   - deviceProfileID string
//   - payload displayactions.VoiceStatePayload
func (_e *DisplayEmitter_Expecter) EmitVoiceStateChanged(deviceProfileID interface{}, payload interface{}) *DisplayEmitter_EmitVoiceStateChanged_Call {
	return &DisplayEmitter_EmitVoiceStateChanged_Call{Call: _e.mock.On("EmitVoiceStateChanged", deviceProfileID, payload)}
}

func (_c *DisplayEmitter_EmitVoiceStateChanged_Call) Run(run func(deviceProfileID string, payload displayactions.VoiceStatePayload)) *DisplayEmitter_EmitVoiceStateChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(displayactions.VoiceStatePayload))
	})
	return _c
}

func (_c *DisplayEmitter_EmitVoiceStateChanged_Call) Return(_a0 displayactions.VoiceEvent) *DisplayEmitter_EmitVoiceStateChanged_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DisplayEmitter_EmitVoiceStateChanged_Call) RunAndReturn(run func(string, displayactions.VoiceStatePayload) displayactions.VoiceEvent) *DisplayEmitter_EmitVoiceStateChanged_Call {
	_c.Call.Return(run)
	return _c
}

// NewDisplayEmitter creates a new instance of DisplayEmitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDisplayEmitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *DisplayEmitter {
	mock := &DisplayEmitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
