// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	displayactions "jute-dash/apps/hub/internal/pkg/displayactions"

	mock "github.com/stretchr/testify/mock"
)

// EventSource is an autogenerated mock type for the EventSource type
type EventSource struct {
	mock.Mock
}

type EventSource_Expecter struct {
	mock *mock.Mock
}

func (_m *EventSource) EXPECT() *EventSource_Expecter {
	return &EventSource_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function with given fields: ctx
func (_m *EventSource) Subscribe(ctx context.Context) <-chan displayactions.Event {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan displayactions.Event
	if rf, ok := ret.Get(0).(func(context.Context) <-chan displayactions.Event); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan displayactions.Event)
		}
	}

	return r0
}

// EventSource_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type EventSource_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
func (_e *EventSource_Expecter) Subscribe(ctx interface{}) *EventSource_Subscribe_Call {
	return &EventSource_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx)}
}

func (_c *EventSource_Subscribe_Call) Run(run func(ctx context.Context)) *EventSource_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *EventSource_Subscribe_Call) Return(_a0 <-chan displayactions.Event) *EventSource_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventSource_Subscribe_Call) RunAndReturn(run func(context.Context) <-chan displayactions.Event) *EventSource_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventSource creates a new instance of EventSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventSource {
	mock := &EventSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
