// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	voice "jute-dash/apps/hub/internal/app/voice"

	mock "github.com/stretchr/testify/mock"
)

// FinalTranscriptSink is an autogenerated mock type for the FinalTranscriptSink type
type FinalTranscriptSink struct {
	mock.Mock
}

type FinalTranscriptSink_Expecter struct {
	mock *mock.Mock
}

func (_m *FinalTranscriptSink) EXPECT() *FinalTranscriptSink_Expecter {
	return &FinalTranscriptSink_Expecter{mock: &_m.Mock}
}

// SubmitFinalTranscript provides a mock function with given fields: ctx, transcript
func (_m *FinalTranscriptSink) SubmitFinalTranscript(ctx context.Context, transcript voice.FinalTranscript) error {
	ret := _m.Called(ctx, transcript)

	if len(ret) == 0 {
		panic("no return value specified for SubmitFinalTranscript")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, voice.FinalTranscript) error); ok {
		r0 = rf(ctx, transcript)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FinalTranscriptSink_SubmitFinalTranscript_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubmitFinalTranscript'
type FinalTranscriptSink_SubmitFinalTranscript_Call struct {
	*mock.Call
}

// SubmitFinalTranscript is a helper method to define mock.On call
//   - ctx context.Context
//   - transcript voice.FinalTranscript
func (_e *FinalTranscriptSink_Expecter) SubmitFinalTranscript(ctx interface{}, transcript interface{}) *FinalTranscriptSink_SubmitFinalTranscript_Call {
	return &FinalTranscriptSink_SubmitFinalTranscript_Call{Call: _e.mock.On("SubmitFinalTranscript", ctx, transcript)}
}

func (_c *FinalTranscriptSink_SubmitFinalTranscript_Call) Run(run func(ctx context.Context, transcript voice.FinalTranscript)) *FinalTranscriptSink_SubmitFinalTranscript_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(voice.FinalTranscript))
	})
	return _c
}

func (_c *FinalTranscriptSink_SubmitFinalTranscript_Call) Return(_a0 error) *FinalTranscriptSink_SubmitFinalTranscript_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *FinalTranscriptSink_SubmitFinalTranscript_Call) RunAndReturn(run func(context.Context, voice.FinalTranscript) error) *FinalTranscriptSink_SubmitFinalTranscript_Call {
	_c.Call.Return(run)
	return _c
}

// NewFinalTranscriptSink creates a new instance of FinalTranscriptSink. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFinalTranscriptSink(t interface {
	mock.TestingT
	Cleanup(func())
}) *FinalTranscriptSink {
	mock := &FinalTranscriptSink{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
