// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MasterKeyProvider is an autogenerated mock type for the MasterKeyProvider type
type MasterKeyProvider struct {
	mock.Mock
}

type MasterKeyProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MasterKeyProvider) EXPECT() *MasterKeyProvider_Expecter {
	return &MasterKeyProvider_Expecter{mock: &_m.Mock}
}

// MasterKey provides a mock function with given fields: ctx
func (_m *MasterKeyProvider) MasterKey(ctx context.Context) ([]byte, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for MasterKey")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]byte, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []byte); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MasterKeyProvider_MasterKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MasterKey'
type MasterKeyProvider_MasterKey_Call struct {
	*mock.Call
}

// MasterKey is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MasterKeyProvider_Expecter) MasterKey(ctx interface{}) *MasterKeyProvider_MasterKey_Call {
	return &MasterKeyProvider_MasterKey_Call{Call: _e.mock.On("MasterKey", ctx)}
}

func (_c *MasterKeyProvider_MasterKey_Call) Run(run func(ctx context.Context)) *MasterKeyProvider_MasterKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MasterKeyProvider_MasterKey_Call) Return(_a0 []byte, _a1 error) *MasterKeyProvider_MasterKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MasterKeyProvider_MasterKey_Call) RunAndReturn(run func(context.Context) ([]byte, error)) *MasterKeyProvider_MasterKey_Call {
	_c.Call.Return(run)
	return _c
}

// NewMasterKeyProvider creates a new instance of MasterKeyProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMasterKeyProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MasterKeyProvider {
	mock := &MasterKeyProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
