// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	a2a "jute-dash/apps/hub/internal/pkg/a2a"

	mock "github.com/stretchr/testify/mock"
)

// MessageSender is an autogenerated mock type for the MessageSender type
type MessageSender struct {
	mock.Mock
}

type MessageSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MessageSender) EXPECT() *MessageSender_Expecter {
	return &MessageSender_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function with given fields: ctx, req
func (_m *MessageSender) SendMessage(ctx context.Context, req a2a.SendMessageRequest) (a2a.SendMessageResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 a2a.SendMessageResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, a2a.SendMessageRequest) (a2a.SendMessageResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, a2a.SendMessageRequest) a2a.SendMessageResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(a2a.SendMessageResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, a2a.SendMessageRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MessageSender_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MessageSender_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - req a2a.SendMessageRequest
func (_e *MessageSender_Expecter) SendMessage(ctx interface{}, req interface{}) *MessageSender_SendMessage_Call {
	return &MessageSender_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, req)}
}

func (_c *MessageSender_SendMessage_Call) Run(run func(ctx context.Context, req a2a.SendMessageRequest)) *MessageSender_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(a2a.SendMessageRequest))
	})
	return _c
}

func (_c *MessageSender_SendMessage_Call) Return(_a0 a2a.SendMessageResult, _a1 error) *MessageSender_SendMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MessageSender_SendMessage_Call) RunAndReturn(run func(context.Context, a2a.SendMessageRequest) (a2a.SendMessageResult, error)) *MessageSender_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMessageSender creates a new instance of MessageSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessageSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessageSender {
	mock := &MessageSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
