// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	mcp "jute-dash/apps/hub/internal/app/mcp"

	mock "github.com/stretchr/testify/mock"
)

// PromptRoute is an autogenerated mock type for the PromptRoute type
type PromptRoute struct {
	mock.Mock
}

type PromptRoute_Expecter struct {
	mock *mock.Mock
}

func (_m *PromptRoute) EXPECT() *PromptRoute_Expecter {
	return &PromptRoute_Expecter{mock: &_m.Mock}
}

// Arguments provides a mock function with no fields
func (_m *PromptRoute) Arguments() []map[string]interface{} {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Arguments")
	}

	var r0 []map[string]interface{}
	if rf, ok := ret.Get(0).(func() []map[string]interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]map[string]interface{})
		}
	}

	return r0
}

// PromptRoute_Arguments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Arguments'
type PromptRoute_Arguments_Call struct {
	*mock.Call
}

// Arguments is a helper method to define mock.On call
func (_e *PromptRoute_Expecter) Arguments() *PromptRoute_Arguments_Call {
	return &PromptRoute_Arguments_Call{Call: _e.mock.On("Arguments")}
}

func (_c *PromptRoute_Arguments_Call) Run(run func()) *PromptRoute_Arguments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PromptRoute_Arguments_Call) Return(_a0 []map[string]interface{}) *PromptRoute_Arguments_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PromptRoute_Arguments_Call) RunAndReturn(run func() []map[string]interface{}) *PromptRoute_Arguments_Call {
	_c.Call.Return(run)
	return _c
}

// Description provides a mock function with no fields
func (_m *PromptRoute) Description() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PromptRoute_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type PromptRoute_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *PromptRoute_Expecter) Description() *PromptRoute_Description_Call {
	return &PromptRoute_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *PromptRoute_Description_Call) Run(run func()) *PromptRoute_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PromptRoute_Description_Call) Return(_a0 string) *PromptRoute_Description_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PromptRoute_Description_Call) RunAndReturn(run func() string) *PromptRoute_Description_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, args
func (_m *PromptRoute) Get(ctx mcp.RouteContext, name string, args map[string]interface{}) (string, error) {
	ret := _m.Called(ctx, name, args)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(mcp.RouteContext, string, map[string]interface{}) (string, error)); ok {
		return rf(ctx, name, args)
	}
	if rf, ok := ret.Get(0).(func(mcp.RouteContext, string, map[string]interface{}) string); ok {
		r0 = rf(ctx, name, args)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(mcp.RouteContext, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, name, args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PromptRoute_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type PromptRoute_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx mcp.RouteContext
//   - name string
//   - args map[string]interface{}
func (_e *PromptRoute_Expecter) Get(ctx interface{}, name interface{}, args interface{}) *PromptRoute_Get_Call {
	return &PromptRoute_Get_Call{Call: _e.mock.On("Get", ctx, name, args)}
}

func (_c *PromptRoute_Get_Call) Run(run func(ctx mcp.RouteContext, name string, args map[string]interface{})) *PromptRoute_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(mcp.RouteContext), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *PromptRoute_Get_Call) Return(_a0 string, _a1 error) *PromptRoute_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PromptRoute_Get_Call) RunAndReturn(run func(mcp.RouteContext, string, map[string]interface{}) (string, error)) *PromptRoute_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *PromptRoute) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PromptRoute_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type PromptRoute_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *PromptRoute_Expecter) Name() *PromptRoute_Name_Call {
	return &PromptRoute_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *PromptRoute_Name_Call) Run(run func()) *PromptRoute_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PromptRoute_Name_Call) Return(_a0 string) *PromptRoute_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PromptRoute_Name_Call) RunAndReturn(run func() string) *PromptRoute_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Scope provides a mock function with no fields
func (_m *PromptRoute) Scope() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Scope")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PromptRoute_Scope_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scope'
type PromptRoute_Scope_Call struct {
	*mock.Call
}

// Scope is a helper method to define mock.On call
func (_e *PromptRoute_Expecter) Scope() *PromptRoute_Scope_Call {
	return &PromptRoute_Scope_Call{Call: _e.mock.On("Scope")}
}

func (_c *PromptRoute_Scope_Call) Run(run func()) *PromptRoute_Scope_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PromptRoute_Scope_Call) Return(_a0 string) *PromptRoute_Scope_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PromptRoute_Scope_Call) RunAndReturn(run func() string) *PromptRoute_Scope_Call {
	_c.Call.Return(run)
	return _c
}

// Title provides a mock function with no fields
func (_m *PromptRoute) Title() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Title")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// PromptRoute_Title_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Title'
type PromptRoute_Title_Call struct {
	*mock.Call
}

// Title is a helper method to define mock.On call
func (_e *PromptRoute_Expecter) Title() *PromptRoute_Title_Call {
	return &PromptRoute_Title_Call{Call: _e.mock.On("Title")}
}

func (_c *PromptRoute_Title_Call) Run(run func()) *PromptRoute_Title_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PromptRoute_Title_Call) Return(_a0 string) *PromptRoute_Title_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PromptRoute_Title_Call) RunAndReturn(run func() string) *PromptRoute_Title_Call {
	_c.Call.Return(run)
	return _c
}

// NewPromptRoute creates a new instance of PromptRoute. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPromptRoute(t interface {
	mock.TestingT
	Cleanup(func())
}) *PromptRoute {
	mock := &PromptRoute{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
