// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// secretStore is an autogenerated mock type for the secretStore type
type secretStore struct {
	mock.Mock
}

type secretStore_Expecter struct {
	mock *mock.Mock
}

func (_m *secretStore) EXPECT() *secretStore_Expecter {
	return &secretStore_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function with given fields: ctx, id
func (_m *secretStore) Resolve(ctx context.Context, id string) (string, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// secretStore_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type secretStore_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *secretStore_Expecter) Resolve(ctx interface{}, id interface{}) *secretStore_Resolve_Call {
	return &secretStore_Resolve_Call{Call: _e.mock.On("Resolve", ctx, id)}
}

func (_c *secretStore_Resolve_Call) Run(run func(ctx context.Context, id string)) *secretStore_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *secretStore_Resolve_Call) Return(_a0 string, _a1 error) *secretStore_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *secretStore_Resolve_Call) RunAndReturn(run func(context.Context, string) (string, error)) *secretStore_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, id, kind, value
func (_m *secretStore) Store(ctx context.Context, id string, kind string, value string) error {
	ret := _m.Called(ctx, id, kind, value)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, id, kind, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// secretStore_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type secretStore_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - kind string
//   - value string
func (_e *secretStore_Expecter) Store(ctx interface{}, id interface{}, kind interface{}, value interface{}) *secretStore_Store_Call {
	return &secretStore_Store_Call{Call: _e.mock.On("Store", ctx, id, kind, value)}
}

func (_c *secretStore_Store_Call) Run(run func(ctx context.Context, id string, kind string, value string)) *secretStore_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *secretStore_Store_Call) Return(_a0 error) *secretStore_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *secretStore_Store_Call) RunAndReturn(run func(context.Context, string, string, string) error) *secretStore_Store_Call {
	_c.Call.Return(run)
	return _c
}

// newSecretStore creates a new instance of secretStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newSecretStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *secretStore {
	mock := &secretStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
