// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	homestate "jute-dash/apps/hub/internal/app/homestate"

	mock "github.com/stretchr/testify/mock"
)

// SettingsStore is an autogenerated mock type for the SettingsStore type
type SettingsStore struct {
	mock.Mock
}

type SettingsStore_Expecter struct {
	mock *mock.Mock
}

func (_m *SettingsStore) EXPECT() *SettingsStore_Expecter {
	return &SettingsStore_Expecter{mock: &_m.Mock}
}

// HouseholdSettings provides a mock function with given fields: ctx
func (_m *SettingsStore) HouseholdSettings(ctx context.Context) (homestate.HouseholdSettings, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for HouseholdSettings")
	}

	var r0 homestate.HouseholdSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (homestate.HouseholdSettings, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) homestate.HouseholdSettings); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(homestate.HouseholdSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SettingsStore_HouseholdSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HouseholdSettings'
type SettingsStore_HouseholdSettings_Call struct {
	*mock.Call
}

// HouseholdSettings is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SettingsStore_Expecter) HouseholdSettings(ctx interface{}) *SettingsStore_HouseholdSettings_Call {
	return &SettingsStore_HouseholdSettings_Call{Call: _e.mock.On("HouseholdSettings", ctx)}
}

func (_c *SettingsStore_HouseholdSettings_Call) Run(run func(ctx context.Context)) *SettingsStore_HouseholdSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SettingsStore_HouseholdSettings_Call) Return(_a0 homestate.HouseholdSettings, _a1 error) *SettingsStore_HouseholdSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SettingsStore_HouseholdSettings_Call) RunAndReturn(run func(context.Context) (homestate.HouseholdSettings, error)) *SettingsStore_HouseholdSettings_Call {
	_c.Call.Return(run)
	return _c
}

// Rooms provides a mock function with given fields: ctx
func (_m *SettingsStore) Rooms(ctx context.Context) ([]homestate.RoomConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rooms")
	}

	var r0 []homestate.RoomConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]homestate.RoomConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []homestate.RoomConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]homestate.RoomConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SettingsStore_Rooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rooms'
type SettingsStore_Rooms_Call struct {
	*mock.Call
}

// Rooms is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SettingsStore_Expecter) Rooms(ctx interface{}) *SettingsStore_Rooms_Call {
	return &SettingsStore_Rooms_Call{Call: _e.mock.On("Rooms", ctx)}
}

func (_c *SettingsStore_Rooms_Call) Run(run func(ctx context.Context)) *SettingsStore_Rooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SettingsStore_Rooms_Call) Return(_a0 []homestate.RoomConfig, _a1 error) *SettingsStore_Rooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SettingsStore_Rooms_Call) RunAndReturn(run func(context.Context) ([]homestate.RoomConfig, error)) *SettingsStore_Rooms_Call {
	_c.Call.Return(run)
	return _c
}

// SaveHouseholdSettings provides a mock function with given fields: ctx, settings
func (_m *SettingsStore) SaveHouseholdSettings(ctx context.Context, settings homestate.HouseholdSettings) (homestate.HouseholdSettings, error) {
	ret := _m.Called(ctx, settings)

	if len(ret) == 0 {
		panic("no return value specified for SaveHouseholdSettings")
	}

	var r0 homestate.HouseholdSettings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, homestate.HouseholdSettings) (homestate.HouseholdSettings, error)); ok {
		return rf(ctx, settings)
	}
	if rf, ok := ret.Get(0).(func(context.Context, homestate.HouseholdSettings) homestate.HouseholdSettings); ok {
		r0 = rf(ctx, settings)
	} else {
		r0 = ret.Get(0).(homestate.HouseholdSettings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, homestate.HouseholdSettings) error); ok {
		r1 = rf(ctx, settings)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SettingsStore_SaveHouseholdSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveHouseholdSettings'
type SettingsStore_SaveHouseholdSettings_Call struct {
	*mock.Call
}

// SaveHouseholdSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - settings homestate.HouseholdSettings
func (_e *SettingsStore_Expecter) SaveHouseholdSettings(ctx interface{}, settings interface{}) *SettingsStore_SaveHouseholdSettings_Call {
	return &SettingsStore_SaveHouseholdSettings_Call{Call: _e.mock.On("SaveHouseholdSettings", ctx, settings)}
}

func (_c *SettingsStore_SaveHouseholdSettings_Call) Run(run func(ctx context.Context, settings homestate.HouseholdSettings)) *SettingsStore_SaveHouseholdSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(homestate.HouseholdSettings))
	})
	return _c
}

func (_c *SettingsStore_SaveHouseholdSettings_Call) Return(_a0 homestate.HouseholdSettings, _a1 error) *SettingsStore_SaveHouseholdSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SettingsStore_SaveHouseholdSettings_Call) RunAndReturn(run func(context.Context, homestate.HouseholdSettings) (homestate.HouseholdSettings, error)) *SettingsStore_SaveHouseholdSettings_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRooms provides a mock function with given fields: ctx, rooms
func (_m *SettingsStore) SaveRooms(ctx context.Context, rooms []homestate.RoomConfig) ([]homestate.RoomConfig, error) {
	ret := _m.Called(ctx, rooms)

	if len(ret) == 0 {
		panic("no return value specified for SaveRooms")
	}

	var r0 []homestate.RoomConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []homestate.RoomConfig) ([]homestate.RoomConfig, error)); ok {
		return rf(ctx, rooms)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []homestate.RoomConfig) []homestate.RoomConfig); ok {
		r0 = rf(ctx, rooms)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]homestate.RoomConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []homestate.RoomConfig) error); ok {
		r1 = rf(ctx, rooms)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SettingsStore_SaveRooms_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRooms'
type SettingsStore_SaveRooms_Call struct {
	*mock.Call
}

// SaveRooms is a helper method to define mock.On call
//   - ctx context.Context
//   - rooms []homestate.RoomConfig
func (_e *SettingsStore_Expecter) SaveRooms(ctx interface{}, rooms interface{}) *SettingsStore_SaveRooms_Call {
	return &SettingsStore_SaveRooms_Call{Call: _e.mock.On("SaveRooms", ctx, rooms)}
}

func (_c *SettingsStore_SaveRooms_Call) Run(run func(ctx context.Context, rooms []homestate.RoomConfig)) *SettingsStore_SaveRooms_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]homestate.RoomConfig))
	})
	return _c
}

func (_c *SettingsStore_SaveRooms_Call) Return(_a0 []homestate.RoomConfig, _a1 error) *SettingsStore_SaveRooms_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SettingsStore_SaveRooms_Call) RunAndReturn(run func(context.Context, []homestate.RoomConfig) ([]homestate.RoomConfig, error)) *SettingsStore_SaveRooms_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTiles provides a mock function with given fields: ctx, tiles
func (_m *SettingsStore) SaveTiles(ctx context.Context, tiles []homestate.TileConfig) ([]homestate.TileConfig, error) {
	ret := _m.Called(ctx, tiles)

	if len(ret) == 0 {
		panic("no return value specified for SaveTiles")
	}

	var r0 []homestate.TileConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []homestate.TileConfig) ([]homestate.TileConfig, error)); ok {
		return rf(ctx, tiles)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []homestate.TileConfig) []homestate.TileConfig); ok {
		r0 = rf(ctx, tiles)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]homestate.TileConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []homestate.TileConfig) error); ok {
		r1 = rf(ctx, tiles)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SettingsStore_SaveTiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTiles'
type SettingsStore_SaveTiles_Call struct {
	*mock.Call
}

// SaveTiles is a helper method to define mock.On call
//   - ctx context.Context
//   - tiles []homestate.TileConfig
func (_e *SettingsStore_Expecter) SaveTiles(ctx interface{}, tiles interface{}) *SettingsStore_SaveTiles_Call {
	return &SettingsStore_SaveTiles_Call{Call: _e.mock.On("SaveTiles", ctx, tiles)}
}

func (_c *SettingsStore_SaveTiles_Call) Run(run func(ctx context.Context, tiles []homestate.TileConfig)) *SettingsStore_SaveTiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]homestate.TileConfig))
	})
	return _c
}

func (_c *SettingsStore_SaveTiles_Call) Return(_a0 []homestate.TileConfig, _a1 error) *SettingsStore_SaveTiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SettingsStore_SaveTiles_Call) RunAndReturn(run func(context.Context, []homestate.TileConfig) ([]homestate.TileConfig, error)) *SettingsStore_SaveTiles_Call {
	_c.Call.Return(run)
	return _c
}

// SetupStatus provides a mock function with given fields: ctx
func (_m *SettingsStore) SetupStatus(ctx context.Context) (homestate.SetupStatus, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SetupStatus")
	}

	var r0 homestate.SetupStatus
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (homestate.SetupStatus, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) homestate.SetupStatus); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(homestate.SetupStatus)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SettingsStore_SetupStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetupStatus'
type SettingsStore_SetupStatus_Call struct {
	*mock.Call
}

// SetupStatus is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SettingsStore_Expecter) SetupStatus(ctx interface{}) *SettingsStore_SetupStatus_Call {
	return &SettingsStore_SetupStatus_Call{Call: _e.mock.On("SetupStatus", ctx)}
}

func (_c *SettingsStore_SetupStatus_Call) Run(run func(ctx context.Context)) *SettingsStore_SetupStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SettingsStore_SetupStatus_Call) Return(_a0 homestate.SetupStatus, _a1 error) *SettingsStore_SetupStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SettingsStore_SetupStatus_Call) RunAndReturn(run func(context.Context) (homestate.SetupStatus, error)) *SettingsStore_SetupStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Tiles provides a mock function with given fields: ctx
func (_m *SettingsStore) Tiles(ctx context.Context) ([]homestate.TileConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Tiles")
	}

	var r0 []homestate.TileConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]homestate.TileConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []homestate.TileConfig); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]homestate.TileConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SettingsStore_Tiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tiles'
type SettingsStore_Tiles_Call struct {
	*mock.Call
}

// Tiles is a helper method to define mock.On call
//   - ctx context.Context
func (_e *SettingsStore_Expecter) Tiles(ctx interface{}) *SettingsStore_Tiles_Call {
	return &SettingsStore_Tiles_Call{Call: _e.mock.On("Tiles", ctx)}
}

func (_c *SettingsStore_Tiles_Call) Run(run func(ctx context.Context)) *SettingsStore_Tiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *SettingsStore_Tiles_Call) Return(_a0 []homestate.TileConfig, _a1 error) *SettingsStore_Tiles_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *SettingsStore_Tiles_Call) RunAndReturn(run func(context.Context) ([]homestate.TileConfig, error)) *SettingsStore_Tiles_Call {
	_c.Call.Return(run)
	return _c
}

// NewSettingsStore creates a new instance of SettingsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSettingsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *SettingsStore {
	mock := &SettingsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
