// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	voice "jute-dash/apps/hub/internal/app/voice"

	mock "github.com/stretchr/testify/mock"
)

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// CancelVoice provides a mock function with given fields: ctx, deviceProfileID
func (_m *Store) CancelVoice(ctx context.Context, deviceProfileID string) (voice.Settings, error) {
	ret := _m.Called(ctx, deviceProfileID)

	if len(ret) == 0 {
		panic("no return value specified for CancelVoice")
	}

	var r0 voice.Settings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (voice.Settings, error)); ok {
		return rf(ctx, deviceProfileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) voice.Settings); ok {
		r0 = rf(ctx, deviceProfileID)
	} else {
		r0 = ret.Get(0).(voice.Settings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, deviceProfileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_CancelVoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelVoice'
type Store_CancelVoice_Call struct {
	*mock.Call
}

// CancelVoice is a helper method to define mock.On call
//   - ctx context.Context
//   - deviceProfileID string
func (_e *Store_Expecter) CancelVoice(ctx interface{}, deviceProfileID interface{}) *Store_CancelVoice_Call {
	return &Store_CancelVoice_Call{Call: _e.mock.On("CancelVoice", ctx, deviceProfileID)}
}

func (_c *Store_CancelVoice_Call) Run(run func(ctx context.Context, deviceProfileID string)) *Store_CancelVoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_CancelVoice_Call) Return(_a0 voice.Settings, _a1 error) *Store_CancelVoice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_CancelVoice_Call) RunAndReturn(run func(context.Context, string) (voice.Settings, error)) *Store_CancelVoice_Call {
	_c.Call.Return(run)
	return _c
}

// SetVoiceMuted provides a mock function with given fields: ctx, deviceProfileID, muted
func (_m *Store) SetVoiceMuted(ctx context.Context, deviceProfileID string, muted bool) (voice.Settings, error) {
	ret := _m.Called(ctx, deviceProfileID, muted)

	if len(ret) == 0 {
		panic("no return value specified for SetVoiceMuted")
	}

	var r0 voice.Settings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) (voice.Settings, error)); ok {
		return rf(ctx, deviceProfileID, muted)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, bool) voice.Settings); ok {
		r0 = rf(ctx, deviceProfileID, muted)
	} else {
		r0 = ret.Get(0).(voice.Settings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = rf(ctx, deviceProfileID, muted)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_SetVoiceMuted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVoiceMuted'
type Store_SetVoiceMuted_Call struct {
	*mock.Call
}

// SetVoiceMuted is a helper method to define mock.On call
//   - ctx context.Context
//   - deviceProfileID string
//   - muted bool
func (_e *Store_Expecter) SetVoiceMuted(ctx interface{}, deviceProfileID interface{}, muted interface{}) *Store_SetVoiceMuted_Call {
	return &Store_SetVoiceMuted_Call{Call: _e.mock.On("SetVoiceMuted", ctx, deviceProfileID, muted)}
}

func (_c *Store_SetVoiceMuted_Call) Run(run func(ctx context.Context, deviceProfileID string, muted bool)) *Store_SetVoiceMuted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(bool))
	})
	return _c
}

func (_c *Store_SetVoiceMuted_Call) Return(_a0 voice.Settings, _a1 error) *Store_SetVoiceMuted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_SetVoiceMuted_Call) RunAndReturn(run func(context.Context, string, bool) (voice.Settings, error)) *Store_SetVoiceMuted_Call {
	_c.Call.Return(run)
	return _c
}

// VoiceProviders provides a mock function with given fields: ctx
func (_m *Store) VoiceProviders(ctx context.Context) ([]voice.ProviderPack, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for VoiceProviders")
	}

	var r0 []voice.ProviderPack
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]voice.ProviderPack, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []voice.ProviderPack); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]voice.ProviderPack)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_VoiceProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VoiceProviders'
type Store_VoiceProviders_Call struct {
	*mock.Call
}

// VoiceProviders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Store_Expecter) VoiceProviders(ctx interface{}) *Store_VoiceProviders_Call {
	return &Store_VoiceProviders_Call{Call: _e.mock.On("VoiceProviders", ctx)}
}

func (_c *Store_VoiceProviders_Call) Run(run func(ctx context.Context)) *Store_VoiceProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Store_VoiceProviders_Call) Return(_a0 []voice.ProviderPack, _a1 error) *Store_VoiceProviders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_VoiceProviders_Call) RunAndReturn(run func(context.Context) ([]voice.ProviderPack, error)) *Store_VoiceProviders_Call {
	_c.Call.Return(run)
	return _c
}

// VoiceSettings provides a mock function with given fields: ctx, deviceProfileID
func (_m *Store) VoiceSettings(ctx context.Context, deviceProfileID string) (voice.Settings, error) {
	ret := _m.Called(ctx, deviceProfileID)

	if len(ret) == 0 {
		panic("no return value specified for VoiceSettings")
	}

	var r0 voice.Settings
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (voice.Settings, error)); ok {
		return rf(ctx, deviceProfileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) voice.Settings); ok {
		r0 = rf(ctx, deviceProfileID)
	} else {
		r0 = ret.Get(0).(voice.Settings)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, deviceProfileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store_VoiceSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VoiceSettings'
type Store_VoiceSettings_Call struct {
	*mock.Call
}

// VoiceSettings is a helper method to define mock.On call
//   - ctx context.Context
//   - deviceProfileID string
func (_e *Store_Expecter) VoiceSettings(ctx interface{}, deviceProfileID interface{}) *Store_VoiceSettings_Call {
	return &Store_VoiceSettings_Call{Call: _e.mock.On("VoiceSettings", ctx, deviceProfileID)}
}

func (_c *Store_VoiceSettings_Call) Run(run func(ctx context.Context, deviceProfileID string)) *Store_VoiceSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Store_VoiceSettings_Call) Return(_a0 voice.Settings, _a1 error) *Store_VoiceSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Store_VoiceSettings_Call) RunAndReturn(run func(context.Context, string) (voice.Settings, error)) *Store_VoiceSettings_Call {
	_c.Call.Return(run)
	return _c
}

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
