// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	a2a "jute-dash/apps/hub/internal/pkg/a2a"

	mock "github.com/stretchr/testify/mock"
)

// StreamHandler is an autogenerated mock type for the StreamHandler type
type StreamHandler struct {
	mock.Mock
}

type StreamHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *StreamHandler) EXPECT() *StreamHandler_Expecter {
	return &StreamHandler_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *StreamHandler) Execute(_a0 a2a.StreamEvent) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(a2a.StreamEvent) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StreamHandler_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type StreamHandler_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 a2a.StreamEvent
func (_e *StreamHandler_Expecter) Execute(_a0 interface{}) *StreamHandler_Execute_Call {
	return &StreamHandler_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *StreamHandler_Execute_Call) Run(run func(_a0 a2a.StreamEvent)) *StreamHandler_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(a2a.StreamEvent))
	})
	return _c
}

func (_c *StreamHandler_Execute_Call) Return(_a0 error) *StreamHandler_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamHandler_Execute_Call) RunAndReturn(run func(a2a.StreamEvent) error) *StreamHandler_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewStreamHandler creates a new instance of StreamHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStreamHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *StreamHandler {
	mock := &StreamHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
