// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	a2a "jute-dash/apps/hub/internal/pkg/a2a"

	mock "github.com/stretchr/testify/mock"
)

// StreamingMessageSender is an autogenerated mock type for the StreamingMessageSender type
type StreamingMessageSender struct {
	mock.Mock
}

type StreamingMessageSender_Expecter struct {
	mock *mock.Mock
}

func (_m *StreamingMessageSender) EXPECT() *StreamingMessageSender_Expecter {
	return &StreamingMessageSender_Expecter{mock: &_m.Mock}
}

// SendMessage provides a mock function with given fields: ctx, req
func (_m *StreamingMessageSender) SendMessage(ctx context.Context, req a2a.SendMessageRequest) (a2a.SendMessageResult, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 a2a.SendMessageResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, a2a.SendMessageRequest) (a2a.SendMessageResult, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, a2a.SendMessageRequest) a2a.SendMessageResult); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(a2a.SendMessageResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, a2a.SendMessageRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StreamingMessageSender_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type StreamingMessageSender_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - req a2a.SendMessageRequest
func (_e *StreamingMessageSender_Expecter) SendMessage(ctx interface{}, req interface{}) *StreamingMessageSender_SendMessage_Call {
	return &StreamingMessageSender_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, req)}
}

func (_c *StreamingMessageSender_SendMessage_Call) Run(run func(ctx context.Context, req a2a.SendMessageRequest)) *StreamingMessageSender_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(a2a.SendMessageRequest))
	})
	return _c
}

func (_c *StreamingMessageSender_SendMessage_Call) Return(_a0 a2a.SendMessageResult, _a1 error) *StreamingMessageSender_SendMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StreamingMessageSender_SendMessage_Call) RunAndReturn(run func(context.Context, a2a.SendMessageRequest) (a2a.SendMessageResult, error)) *StreamingMessageSender_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// StreamMessage provides a mock function with given fields: ctx, req, handler
func (_m *StreamingMessageSender) StreamMessage(ctx context.Context, req a2a.SendMessageRequest, handler a2a.StreamHandler) error {
	ret := _m.Called(ctx, req, handler)

	if len(ret) == 0 {
		panic("no return value specified for StreamMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, a2a.SendMessageRequest, a2a.StreamHandler) error); ok {
		r0 = rf(ctx, req, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StreamingMessageSender_StreamMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamMessage'
type StreamingMessageSender_StreamMessage_Call struct {
	*mock.Call
}

// StreamMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - req a2a.SendMessageRequest
//   - handler a2a.StreamHandler
func (_e *StreamingMessageSender_Expecter) StreamMessage(ctx interface{}, req interface{}, handler interface{}) *StreamingMessageSender_StreamMessage_Call {
	return &StreamingMessageSender_StreamMessage_Call{Call: _e.mock.On("StreamMessage", ctx, req, handler)}
}

func (_c *StreamingMessageSender_StreamMessage_Call) Run(run func(ctx context.Context, req a2a.SendMessageRequest, handler a2a.StreamHandler)) *StreamingMessageSender_StreamMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(a2a.SendMessageRequest), args[2].(a2a.StreamHandler))
	})
	return _c
}

func (_c *StreamingMessageSender_StreamMessage_Call) Return(_a0 error) *StreamingMessageSender_StreamMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StreamingMessageSender_StreamMessage_Call) RunAndReturn(run func(context.Context, a2a.SendMessageRequest, a2a.StreamHandler) error) *StreamingMessageSender_StreamMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewStreamingMessageSender creates a new instance of StreamingMessageSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStreamingMessageSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *StreamingMessageSender {
	mock := &StreamingMessageSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
