// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	voice "jute-dash/apps/hub/internal/app/voice"

	mock "github.com/stretchr/testify/mock"
)

// STTProvider is an autogenerated mock type for the STTProvider type
type STTProvider struct {
	mock.Mock
}

type STTProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *STTProvider) EXPECT() *STTProvider_Expecter {
	return &STTProvider_Expecter{mock: &_m.Mock}
}

// Transcribe provides a mock function with given fields: ctx, utterance
func (_m *STTProvider) Transcribe(ctx context.Context, utterance voice.CapturedUtterance) (voice.STTResult, error) {
	ret := _m.Called(ctx, utterance)

	if len(ret) == 0 {
		panic("no return value specified for Transcribe")
	}

	var r0 voice.STTResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, voice.CapturedUtterance) (voice.STTResult, error)); ok {
		return rf(ctx, utterance)
	}
	if rf, ok := ret.Get(0).(func(context.Context, voice.CapturedUtterance) voice.STTResult); ok {
		r0 = rf(ctx, utterance)
	} else {
		r0 = ret.Get(0).(voice.STTResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, voice.CapturedUtterance) error); ok {
		r1 = rf(ctx, utterance)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// STTProvider_Transcribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transcribe'
type STTProvider_Transcribe_Call struct {
	*mock.Call
}

// Transcribe is a helper method to define mock.On call
//   - ctx context.Context
//   - utterance voice.CapturedUtterance
func (_e *STTProvider_Expecter) Transcribe(ctx interface{}, utterance interface{}) *STTProvider_Transcribe_Call {
	return &STTProvider_Transcribe_Call{Call: _e.mock.On("Transcribe", ctx, utterance)}
}

func (_c *STTProvider_Transcribe_Call) Run(run func(ctx context.Context, utterance voice.CapturedUtterance)) *STTProvider_Transcribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(voice.CapturedUtterance))
	})
	return _c
}

func (_c *STTProvider_Transcribe_Call) Return(_a0 voice.STTResult, _a1 error) *STTProvider_Transcribe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *STTProvider_Transcribe_Call) RunAndReturn(run func(context.Context, voice.CapturedUtterance) (voice.STTResult, error)) *STTProvider_Transcribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewSTTProvider creates a new instance of STTProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSTTProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *STTProvider {
	mock := &STTProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
