// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	dashboard "jute-dash/apps/hub/internal/app/dashboard"

	mock "github.com/stretchr/testify/mock"
)

// Syncer is an autogenerated mock type for the Syncer type
type Syncer struct {
	mock.Mock
}

type Syncer_Expecter struct {
	mock *mock.Mock
}

func (_m *Syncer) EXPECT() *Syncer_Expecter {
	return &Syncer_Expecter{mock: &_m.Mock}
}

// DashboardConfig provides a mock function with given fields: ctx
func (_m *Syncer) DashboardConfig(ctx context.Context) (dashboard.DashboardConfig, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DashboardConfig")
	}

	var r0 dashboard.DashboardConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (dashboard.DashboardConfig, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) dashboard.DashboardConfig); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(dashboard.DashboardConfig)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Syncer_DashboardConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DashboardConfig'
type Syncer_DashboardConfig_Call struct {
	*mock.Call
}

// DashboardConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *Syncer_Expecter) DashboardConfig(ctx interface{}) *Syncer_DashboardConfig_Call {
	return &Syncer_DashboardConfig_Call{Call: _e.mock.On("DashboardConfig", ctx)}
}

func (_c *Syncer_DashboardConfig_Call) Run(run func(ctx context.Context)) *Syncer_DashboardConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *Syncer_DashboardConfig_Call) Return(_a0 dashboard.DashboardConfig, _a1 error) *Syncer_DashboardConfig_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Syncer_DashboardConfig_Call) RunAndReturn(run func(context.Context) (dashboard.DashboardConfig, error)) *Syncer_DashboardConfig_Call {
	_c.Call.Return(run)
	return _c
}

// SyncDashboard provides a mock function with given fields: ctx, cfg
func (_m *Syncer) SyncDashboard(ctx context.Context, cfg dashboard.DashboardConfig) error {
	ret := _m.Called(ctx, cfg)

	if len(ret) == 0 {
		panic("no return value specified for SyncDashboard")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, dashboard.DashboardConfig) error); ok {
		r0 = rf(ctx, cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Syncer_SyncDashboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncDashboard'
type Syncer_SyncDashboard_Call struct {
	*mock.Call
}

// SyncDashboard is a helper method to define mock.On call
//   - ctx context.Context
//   - cfg dashboard.DashboardConfig
func (_e *Syncer_Expecter) SyncDashboard(ctx interface{}, cfg interface{}) *Syncer_SyncDashboard_Call {
	return &Syncer_SyncDashboard_Call{Call: _e.mock.On("SyncDashboard", ctx, cfg)}
}

func (_c *Syncer_SyncDashboard_Call) Run(run func(ctx context.Context, cfg dashboard.DashboardConfig)) *Syncer_SyncDashboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(dashboard.DashboardConfig))
	})
	return _c
}

func (_c *Syncer_SyncDashboard_Call) Return(_a0 error) *Syncer_SyncDashboard_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Syncer_SyncDashboard_Call) RunAndReturn(run func(context.Context, dashboard.DashboardConfig) error) *Syncer_SyncDashboard_Call {
	_c.Call.Return(run)
	return _c
}

// NewSyncer creates a new instance of Syncer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSyncer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Syncer {
	mock := &Syncer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
