// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	voice "jute-dash/apps/hub/internal/app/voice"

	mock "github.com/stretchr/testify/mock"
)

// WakeProvider is an autogenerated mock type for the WakeProvider type
type WakeProvider struct {
	mock.Mock
}

type WakeProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *WakeProvider) EXPECT() *WakeProvider_Expecter {
	return &WakeProvider_Expecter{mock: &_m.Mock}
}

// RunOnce provides a mock function with given fields: ctx, emitter
func (_m *WakeProvider) RunOnce(ctx context.Context, emitter voice.WakeEventEmitter) error {
	ret := _m.Called(ctx, emitter)

	if len(ret) == 0 {
		panic("no return value specified for RunOnce")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, voice.WakeEventEmitter) error); ok {
		r0 = rf(ctx, emitter)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WakeProvider_RunOnce_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunOnce'
type WakeProvider_RunOnce_Call struct {
	*mock.Call
}

// RunOnce is a helper method to define mock.On call
//   - ctx context.Context
//   - emitter voice.WakeEventEmitter
func (_e *WakeProvider_Expecter) RunOnce(ctx interface{}, emitter interface{}) *WakeProvider_RunOnce_Call {
	return &WakeProvider_RunOnce_Call{Call: _e.mock.On("RunOnce", ctx, emitter)}
}

func (_c *WakeProvider_RunOnce_Call) Run(run func(ctx context.Context, emitter voice.WakeEventEmitter)) *WakeProvider_RunOnce_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(voice.WakeEventEmitter))
	})
	return _c
}

func (_c *WakeProvider_RunOnce_Call) Return(_a0 error) *WakeProvider_RunOnce_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *WakeProvider_RunOnce_Call) RunAndReturn(run func(context.Context, voice.WakeEventEmitter) error) *WakeProvider_RunOnce_Call {
	_c.Call.Return(run)
	return _c
}

// NewWakeProvider creates a new instance of WakeProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWakeProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *WakeProvider {
	mock := &WakeProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
